AWS Error checker utility
panther-labs/panther pull request #1522
Opened 2020-09-11 07:16 UTC by kostaspap

## Background

Backporting a small function to help check for AWS error codes. 

## Changes

- Backported from Enterprise

## Testing

- `mage test:ci`

2020-09-11 07:23 UTC, kostaspap commented on tools/mage/clients/aws.go
> +		if awsutils.IsAnyError(err, "NoCredentialProviders") {
There are more places in the code were we make such checks. Updated some to demonstrate how this function can be used.

2020-09-11 10:37 UTC, giorgosp approved these changes

2020-09-11 16:48 UTC, austinbyers requested changes

2020-09-11 16:48 UTC, austinbyers commented on pkg/awsutils/awsutils.go
> +	awserror, ok := err.(awserr.Error)
Careful: this will *not* work if the error is wrapped with the `errors` package. This led to some serious bugs: #1517 

To be safe, use `errors.As` instead of checking the type explicitly:

```go
    var awserror
    if errors.As(err, &awserror) {
```

This function will work whether the error is wrapped or not, or if it's nil. So it's safer overall

2020-09-11 16:50 UTC, austinbyers commented on pkg/awsutils/awsutils.go
> +	awserror, ok := err.(awserr.Error)
I know it adds a dependency to this library that isn't technically needed, but we use the `errors` package throughout most of our code - I don't want a helper library that will silently fail for a large class of our own errors

2020-09-12 19:24 UTC, rleighton approved these changes

2020-09-12 19:24 UTC, rleighton commented on pkg/awsutils/awsutils.go
> +	awserror, ok := err.(awserr.Error)
Good suggestion.

2020-09-14 07:38 UTC, kostaspap commented on pkg/awsutils/awsutils.go
> +	awserror, ok := err.(awserr.Error)
I was thinking it might make sense to have two methods : `IsAnyError` and `ContainsAnyError`. The first checks if the `error` provided matches any of the provided codes. The second checks if any of the errors in the chain match the provided codes. I was thinking there might be a case where we want to distinguish between the two scenarios. 
Do you think it makes sense? Or will we end up using the `Contains` all the time? 
I made a comment about this [here](https://github.com/panther-labs/panther/pull/1517#discussion_r486823329)

2020-09-14 19:49 UTC, austinbyers commented on pkg/awsutils/awsutils.go
> +	awserror, ok := err.(awserr.Error)
Most of the time, we're checking for a single AWS error code. But sometimes that's not sufficient and we have to instead check the error message. Very rarely, we check for more than one error code. Personally I think the helper function is overkill for this, but doesn't really matter to me either way. I was just want to make sure this:

```go
if awsErr, ok := err.(awserr.Error)
```

doesn't appear anywhere in the codebase, since it will not work with the `errors` package

2020-09-14 19:50 UTC, austinbyers approved these changes
Looks good after fixing the type check

2020-09-15 11:16 UTC, kostaspap commented
> Looks good after fixing the type check

Updated check.

2020-09-15 11:27 UTC, merged