Add Cloudflare parsers for http requests, Spectrum and firewall events
panther-labs/panther pull request #1558
Opened 2020-09-17 13:23 UTC by giorgosp

## Background

Cloudflare parsers for http requests, Spectrum and firewall events.

## Changes

- List your changes here in more detail

## Testing

- unit tests

2020-09-21 10:28 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	}
Cloudflare logs could be off by a fix seconds or minutes (time syncing can be hard). I think this check is a bit too strict...
To avoid calling a `time.Now()` function on every parsing, I think it would be safe to pick a 'fixed' date in the future e.g. `var `future = time.Date(2100, 0, 0, 0, 0, 0, 0, time.UTC).Unix()` . If the time is greater than that, it means it is (most likely) defined in nanos.

2020-09-21 10:28 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	}
Shouldn't we report an error in this case? Same error handling as in here: https://github.com/panther-labs/panther/blob/b60ee537f738d86dcfd191a9aa5d76329d649bef/internal/log_analysis/log_processor/pantherlog/tcodec/tcodec.go#L164-L168

2020-09-21 10:28 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	OriginResponseHTTPLastModified pantherlog.String   `json:"OriginResponseHTTPLastModified" description:"Value of the origin 'last-modified' header in RFC1123 format"`
These two should be of `pantherlog.Time` type.

2020-09-21 10:28 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	EdgeEndTimestamp               pantherlog.Time     `json:"EdgeEndTimestamp" description:"Timestamp at which the edge finished sending response to the client"`
This should have a codec specified (`rfc3339`)?

2020-09-21 10:28 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	EdgeResponseCompressionRatio   pantherlog.Float64  `json:"EdgeResponseCompressionRatio" description:"Edge response compression ratio	"`
extra space in description.

2020-09-21 10:28 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	EdgeResponseStatus             pantherlog.Int64    `json:"EdgeResponseStatus" description:"HTTP status code returned by Cloudflare to the client"`
`int64` seems a bit too much. Int16 should be enough.

2020-09-21 10:28 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	OriginResponseStatus           pantherlog.Int64    `json:"OriginResponseStatus" description:"Status returned by the origin server"`
int16 should be enough.

2020-09-21 10:28 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	ClientMatchedIPFirewall        pantherlog.String `json:"ClientMatchedIpFirewall" panther:"ip" description:"Whether the connection matched any IP Firewall rules; UNKNOWN | ALLOW | BLOCK_ERROR | BLOCK
`panther:"ip"` seems not needed based on the description.

2020-09-21 10:28 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	ClientPort                     pantherlog.Int64  `json:"ClientPort" description:"Client port"`
for ports int32 should be enough.

2020-09-21 10:28 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	OriginPort                     pantherlog.Int64  `json:"OriginPort" description:"Origin port"`
int16

2020-09-21 10:28 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	EdgeResponseStatus     pantherlog.Int64  `json:"EdgeResponseStatus" description:"HTTP response status code returned to browser"`
int16 should be enough.

2020-09-21 10:28 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	OriginResponseStatus   pantherlog.Int64  `json:"OriginResponseStatus" description:"HTTP origin response status code returned to browser"`
int16

2020-09-21 10:28 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +type NanosOrSecondsDecoder struct{}
Can we write unit tests to verify that this works as expected?

2020-09-21 11:28 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	Metadata               interface{}       `json:"Metadata" description:"Additional product-specific information. Metadata is organized in key:value pairs. Key and Value formats can vary by Cloudflare
Actually, judging by the description this could be `map[string]string` or maybe `map[string]pantherlog.RawMessage`? The benefit of defining it as a map, is that it simplifies access to the contents of it. Someone could write `SELECT metadata["myKey"] from cloudflare.http` to get some data

2020-09-21 13:21 UTC, alxarch requested changes
Please update the timstamp codec for cloudflare timestamps as we discussed in Slack.
Also add the appropriate `tcodec:"layout=Mon, 02 Jan 2006 15:04:05 -0700" to the edge timstamps.
Finally we need to have some required fields that differentiate these logs for use in classification.

2020-09-21 13:21 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +type HTTPRequest struct {
Also please move the registrations and the time codec to a `cloudflarelogs.go` file. We would like to have some consistency in the file structure for the new parsers so it's easier to pick up how to write a new one

2020-09-21 13:21 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	EdgeEndTimestamp               pantherlog.Time     `json:"EdgeEndTimestamp" description:"Timestamp at which the edge finished sending response to the client"`
The default for `tcodec` is to use rfc3339 as it's the most common format for timestamps in JSON. It wouldn't hurt to specify it explicitly.

2020-09-21 13:21 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	EdgeResponseCompressionRatio   pantherlog.Float64  `json:"EdgeResponseCompressionRatio" description:"Edge response compression ratio	"`
Float32 should suffice (it would preserve some storage space in millions of log events)

2020-09-21 13:21 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	OriginResponseHTTPLastModified pantherlog.String   `json:"OriginResponseHTTPLastModified" description:"Value of the origin 'last-modified' header in RFC1123 format"`
Depending on the values we should use the [RFC1123/Z format](https://golang.org/pkg/time/#pkg-constants). If we find other logs using them, I can add these in the defaults of `tcodec` package.

2020-09-21 13:21 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	ClientPort                     pantherlog.Int64  `json:"ClientPort" description:"Client port"`
We can use `pantherlog.Uint16` (`0 <= n < 65536`). This is mapped to int32 in glue.

2020-09-21 13:21 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	OriginPort                     pantherlog.Int64  `json:"OriginPort" description:"Origin port"`
`pantherlog.Uint16`

2020-09-21 13:21 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +var cloudflareCodec = tcodec.Join(
After some offline chat on this, I think it's best to use a specific codec for cloudflare to avoid wasting cycles parsing the timestamp in both string and numeric format in the case of unix timestamps. Some other changes we discussed should cover the codec for the cloudflare timestamps.

2020-09-21 14:09 UTC, giorgosp commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +type HTTPRequest struct {
fixed

2020-09-21 14:09 UTC, giorgosp commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	EdgeEndTimestamp               pantherlog.Time     `json:"EdgeEndTimestamp" description:"Timestamp at which the edge finished sending response to the client"`
It should have the `cloudflare` codec. Fixed

2020-09-21 14:09 UTC, giorgosp commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	EdgeResponseCompressionRatio   pantherlog.Float64  `json:"EdgeResponseCompressionRatio" description:"Edge response compression ratio	"`
fixed

2020-09-21 14:09 UTC, giorgosp commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	OriginResponseHTTPLastModified pantherlog.String   `json:"OriginResponseHTTPLastModified" description:"Value of the origin 'last-modified' header in RFC1123 format"`
fixed

2020-09-21 14:09 UTC, giorgosp commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	ClientPort                     pantherlog.Int64  `json:"ClientPort" description:"Client port"`
fixed

2020-09-21 14:09 UTC, giorgosp commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	OriginPort                     pantherlog.Int64  `json:"OriginPort" description:"Origin port"`
fixed

2020-09-21 14:09 UTC, giorgosp commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +var cloudflareCodec = tcodec.Join(
Updated the codec

2020-09-21 14:16 UTC, alxarch commented on internal/log_analysis/log_processor/pantherlog/tcodec/tcodec.go
> +		if child.Error == nil || child.Error == io.EOF {
IIRC this is a quirk of `jsoniter` when parsing scalar JSON values. I am not sure io.EOF happens when reading both string and numbers though.

2020-09-21 14:16 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/access.go
> +	Metadata               interface{}       `json:"Metadata" description:"Additional product-specific information. Metadata is organized in key:value pairs. Key and Value formats can vary by Cloudflare
We generally don't use `interface{}` - we use the `pantherlog.RawMessage`. There are several occurrences of `jsoniter.RawMessage` in the codebase if you are interested to look at it. This type is reserved for fields that can have "varying" structure.

2020-09-21 14:22 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/http_request_test.go
> +	"OriginResponseHTTPLastModified": "Fri, 21 Oct 2016 07:28:00 GMT",
Clarification (maybe from @alxarch ). Shouldn't the timestamps in the expected output be all of the same format?

2020-09-21 14:24 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/firewall.go
> +// Note: No field is marked "required" because Cloudflare allows the user to select which fields to include in the logs.
This applies to *all* fields? Are there any 'core' ones that the user cannot omit?

2020-09-21 14:27 UTC, giorgosp commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/http_request_test.go
> +	"OriginResponseHTTPLastModified": "Fri, 21 Oct 2016 07:28:00 GMT",
They are all transformed later for consistency

2020-09-21 14:28 UTC, giorgosp commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/firewall.go
> +// Note: No field is marked "required" because Cloudflare allows the user to select which fields to include in the logs.
No. We could try to pick 1 or 2 though and make clear in the docs that they are required.

2020-09-21 14:29 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/firewall.go
> +// Note: No field is marked "required" because Cloudflare allows the user to select which fields to include in the logs.
AFAIK, the `Datetime` field should always be there, so we should be able to mark that as required.

2020-09-21 14:32 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/http_request_test.go
> +	"OriginResponseHTTPLastModified": "Fri, 21 Oct 2016 07:28:00 GMT",
Yes, the log processor handles this. For the fields we try to keep the same input/output so tests are easy to write. In the particular case of cloudflare timestamps (not these two) we are using `RFC3339` output for both unix and RFC3339 input timestamps. It would not be possible to keep the original format.

2020-09-21 15:30 UTC, giorgosp commented
Added some required fields. Search for `required` because I amended the commit and force pushed.

2020-09-22 08:43 UTC, kostaspap approved these changes
LGTM, feel free to ship once you have verified E2E (e.g. by sending samples using SQS integration)

2020-09-22 08:47 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/cloudflarelogs/http_request.go
> +	CacheResponseStatus            pantherlog.Int64    `json:"CacheResponseStatus" description:"HTTP status code returned by the cache to the edge; all requests (including non-cacheable ones) go through
Should be in16

2020-09-24 10:11 UTC, alxarch approved these changes
Added some unit tests for the time decoder

2020-09-24 10:51 UTC, kostaspap approved these changes

2020-09-24 10:51 UTC, kostaspap commented on internal/log_analysis/awsglue/schema.go
> +	if mapGlueType, found := customMappingsTable[mapOfType.String()]; found {
Can you add a unit test case for this one?

2020-09-24 11:42 UTC, giorgosp commented on internal/log_analysis/awsglue/schema.go
> +	if mapGlueType, found := customMappingsTable[mapOfType.String()]; found {
Done

2020-09-24 11:47 UTC, merged