API endpoint for most active rules
panther-labs/panther pull request #1584
Opened 2020-09-22 15:37 UTC by lindsey-w

## Background

Request to display information about the most active rules ranked by the number of alerts they sent in a certain time frame.  This change includes both the data generation and the API update.  Closes #1402 

## Changes

- Log the `AlertsTriggered` metric in the alert forwarder.
- Add `alertsByRuleID` metric to the metrics API.  This metric returns time series data. Where the label is the RuleID and the values represent the number of times the rule fired for the given timeframe.

## Testing

- Added new integration test to verify 

input:
```
{
    "GetMetrics": {
        "fromDate": "2020-09-20T23:55:00Z",
        "toDate": "2020-09-21T23:55:00Z",
        "metricNames": [
            "alertsByRuleID"
        ],
        "intervalMinutes": 1440
    }
}
```

response:
```
{
    "alertsByRuleID": {
        "seriesData": {
            "series": [
                {
                    "label": "AWS.S3.ServiceAccess.UnknownRequester",
                    "values": [
                        19
                    ]
                },
                {
                    "label": "AWS.IAM.PolicyModified",
                    "values": [
                        10
                    ]
                },
                {
                    "label": "AWS.EC2.RouteTableModified",
                    "values": [
                        1
                    ]
                }
            ],
            "timestamps": [
                "2020-09-20T23:55:00Z"
            ]
        }
    },
    "fromDate": "2020-09-20T23:55:00Z",
    "intervalMinutes": 1440,
    "toDate": "2020-09-21T23:55:00Z"
}
```

The input will by default return the top 10 rules that have triggered alerts.  This can be modified to return more/less using the `limit` option:
```
{
    "GetMetrics": {
        "fromDate": "2020-09-20T23:55:00Z",
        "intervalMinutes": 1440,
        "limit": 2,
        "metricNames": [
            "alertsByRuleID"
        ],
        "toDate": "2020-09-21T23:55:00Z"
    }
}
```

2020-09-22 15:51 UTC, 3nvi commented on api/lambda/metrics/models/api.go
> +	AlertsByRuleID   *MetricResult `json:"alertsByRuleID,omitempty"`
looks good @lindsey-w 🎉

2020-09-22 17:49 UTC, nhakmiller reviewed
I see this is still in draft, but thought I'd drop a few early comments in!

2020-09-22 17:49 UTC, nhakmiller commented on internal/core/metrics_api/api/alert_metrics.go
> +	zap.L().Warn("found applicable metrics", zap.Any("metrics", listMetricsResponse))
I don't think this should be a `Warn` level message. `Info` at best, but possibly even `Debug`.

2020-09-22 17:49 UTC, nhakmiller commented on internal/core/metrics_api/api/alert_metrics.go
> +	zap.L().Warn("prepared metric queries", zap.Any("queries", queries), zap.Any("toDate", input.ToDate), zap.Any("fromDate", input.FromDate))
Same comment as above, we use `Warn` for messages that indicate something that is not supposed to happen is happening, but it's not bad enough to stop processing (which would be an `Error`).

2020-09-22 17:49 UTC, nhakmiller commented on internal/core/metrics_api/api/alert_metrics.go
> +		return err
We probably want to log this error and then return a generic internal server error like on line 175. If you copied this from an existing metric, we should probably update it there as well.

2020-09-22 17:49 UTC, nhakmiller commented on internal/core/metrics_api/api/alert_metrics.go
> +	limit := 10
Each metric that gets generated in a single request shares the input struct, where `limit` is defined. In general, do we think that the limit should default to 10? If so, it may be worthwhile to set this default value higher up in the call stack (for example in `GetMetrics` near where we set the default namespace) that way other metrics that need to support the `limit` functionality don't need to remember to set the default value to 10.

This will also still allow individual metrics to overwrite the default at their discretion, if they waant.

2020-09-22 17:49 UTC, nhakmiller commented on internal/core/metrics_api/api/alert_metrics.go
> +}
This could probably live in a helper file somewhere, in the same package but just some file called `helpers.go` or something.

2020-09-22 17:49 UTC, nhakmiller commented on internal/log_analysis/alert_forwarder/forwarder/metrics.go
> +	}
So I haven't mucked around with these metrics in a minute, but I _think_ you can re-use the existing metric logger and just add a new dimension, then in the applicable metric generators (in the metrics API) you may just be able to specify which dimension sets you care about for a given query. Could be wrong on that, but worth a look.

2020-09-22 22:39 UTC, lindsey-w commented on internal/core/metrics_api/api/alert_metrics.go
> +		return err
I did use another method as an example when putting this together - but I think we aren't logging right here because the `getMetricData` does the error logging for us (if there is a need) as well as returning `metricsInternalError` or `metricsNodataError`.  Or should we also log something here / return a generic internal error here?

2020-09-23 17:57 UTC, lindsey-w commented on internal/log_analysis/alert_forwarder/forwarder/metrics.go
> +	}
Apparently I just needed to tell you I couldn't get this to work - for it to start working. :) Let me know if my latest update isn't what you were expecting. It did seem to simply things quite a bit.

2020-09-23 18:46 UTC, nhakmiller commented on internal/core/metrics_api/api/alert_metrics.go
> +		return err
Ah you're right, yes returning the error as is there is good 👍

2020-09-24 00:17 UTC, nhakmiller reviewed
The code looks good and I would normally approve, but I want to get confirmation from the frontend end team about whether this should be time series data or not. @3nvi if we could get just a yes/no on that I would really appreciate it.

2020-09-24 00:17 UTC, nhakmiller commented on internal/log_analysis/alert_forwarder/forwarder/metrics.go
> +	StaticLogger = metrics.MustStaticLogger([]metrics.DimensionSet{
This looks great! Exactly what I had in mind for this part.

2020-09-24 00:17 UTC, nhakmiller commented on internal/core/metrics_api/api/helpers.go
> +func totalValue(values []*float64) float64 {
I know it probably seems very trivial, but ideally we could add one or two unit tests just around this function since it is a standalone function that is easily testable.

2020-09-24 00:17 UTC, nhakmiller commented on internal/core/metrics_api/api/get_metrics.go
> +		"alertsByRuleID":   getAlertsByRuleID,
nit: lets alphabetize these.

2020-09-24 00:17 UTC, nhakmiller commented on internal/core/metrics_api/api/alert_metrics.go
> +// This is a time series metric.
Hey @3nvi, @alexmylonas, @vorillaz, can we get confirmation on whether we need this metric to return time series data (e.g. a list of values with corresponding timestamps) or just a single value for each rule?

2020-09-24 00:17 UTC, nhakmiller commented on internal/core/metrics_api/api/alert_metrics.go
> +		return totalValue(values[i].Values) > totalValue(values[j].Values)
I don't know if it is worth optimizing this, but won't this re-compute the `totalValue` potentially many times for the same metric? We could remember what was computed and cache it keyed by ruleID.

Realistically even with hundreds of rules & hundreds of data points this will just take a few nanaseconds, but it may be worth benchmarking something. @austinbyers has done some go benchmarking before, not sure if he thinks its worth our time to try to optimize it but if so he could give some pointers on benchmarking.

2020-09-24 16:13 UTC, nhakmiller approved these changes
@alexmylonas confirmed that time series data is preferred.

2020-09-24 17:09 UTC, alexmylonas requested changes
Talked with @lindsey-w about how we will need this response to be single value instead of timeseries as it's more appropriate for this metric.

Also discussed of renaming the `limit` field to something more explicit for this metric.

Sorry again for not identifying this earlier!

2020-09-24 21:00 UTC, lindsey-w commented
I updated this endpoint to return single value metrics.  

Regarding the name change for the `limit` option.  I was thinking that limiting the number of results would be useful for more than just this `alertsByRuleID` metric.  (e.g. only return top N ‘chatty’ logtypes for the events processed metric).  So it seems there could be a couple of options:

1. It only applies to the `alertsByRuleID` and only requires a simple name change
2. If this applies to more than just the `alertsByRuleID` metric, the re-naming/re-evaluating how it would be added to all the relevant endpoints should be done at the same time (in another issue)
3. Potentially add `options` to the GetMetricsInput where we could define different structs for options on a per-metric basis.  

For example:
```
{
    "GetMetrics": {
        "fromDate": "2020-09-20T23:55:00Z",
        "toDate": "2020-09-21T23:55:00Z",
        "metricNames": [
            "alertsByRuleID"
        ],
        "intervalMinutes": 1440, 
         “options”: { 
              “alertsByRuleIDOptions”: { 
                  “limit”:1,
                  ”order”:”ascending”
               }
          } 
    }
}
```
Or 
```
{
    "GetMetrics": {
        "fromDate": "2020-09-20T23:55:00Z",
        "toDate": "2020-09-21T23:55:00Z",
        "metricNames": [
            "alertsByRuleID"
        ],
        "intervalMinutes": 1440, 
        “alertsByRuleIDOptions”: { 
             “limit”:1,
              ”order”:”ascending”
         } 
    }
}
```

Either way, since this issue originally said "optionally return only a fixed number of results (10 or 20) since the chart will only showcase 5 or 10” - I went ahead and removed the limit option for now. Does that work?

2020-09-25 11:10 UTC, alexmylonas approved these changes
Thanks @lindsey-w for the change, solid work! I agree we can re-visit the options field in the future.
Both solution seems acceptable to me.

2020-09-25 15:52 UTC, merged

2020-09-28 07:15 UTC, kostaspap commented on internal/log_analysis/alert_forwarder/forwarder/forwarder.go
> +		metrics.Dimension{Name: "RuleID", Value: string(rule.ID)},
@lindsey-w can you change this from `RuleID` to `AnalysisID`? 
We use the `AnalysisDimension` to differentiate between rules and policies. 
This will make it simpler to generate metrics for policies in the future. 
Someone can see the number of alerts for a rule by specifying as `AnalysisType`-> `Rule` and `AnalysisID`-> `RuleID`.

2020-09-29 15:30 UTC, lindsey-w commented on internal/log_analysis/alert_forwarder/forwarder/forwarder.go
> +		metrics.Dimension{Name: "RuleID", Value: string(rule.ID)},
Addressed here: https://github.com/panther-labs/panther/pull/1627