Parser for Sophos Central logs
panther-labs/panther pull request #1770
Opened 2020-10-15 19:24 UTC by rynjms

## Background

I wanted Panther to be able to alert on endpoint events collected by Sophos Central.

I previously created issue https://github.com/panther-labs/panther/issues/1661 for this.

## Testing

YAML test cases are included for the main types of logs seen.

2020-10-15 19:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/panther-labs/panther?pullRequest=1770) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/panther-labs/panther?pullRequest=1770) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/panther-labs/panther?pullRequest=1770) it.</sub>

2020-10-16 11:18 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/sophoslogs/central.go
> +	Time         pantherlog.Time   `json:"end" validate:"required" panther:"event_time" description:"Time the event occurred on the endpoint"`
The `panther:"event_time"` should change to `event_time:"true"`. Since the timestamp uses the `rfc3339` format the `tcodec:"rfc3339"` tag can be omitted but would be good to add this also so that anyone looking at this in the future does not have to look into the test files to figure it out.

2020-10-16 11:21 UTC, alxarch requested changes
Apart from the minor issue with `event_time` this looks great! I assume the tests will pass on master once this is fixed.

2020-10-16 11:22 UTC, alxarch commented
Thanks for this exemplary PR!

2020-10-16 11:24 UTC, alxarch approved these changes

2020-10-16 11:25 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/sophoslogs/central.go
> +	Time         pantherlog.Time   `json:"end" validate:"required" panther:"event_time" description:"Time the event occurred on the endpoint"`
Went ahead and made this minor change myself so we can merge this.

2020-10-16 13:55 UTC, alxarch commented
So, it appears there's a glitch in our CI pipeline that prevents a PR from a fork to be merged. I am working on a solution on this in #1067. We will be merging this ASAP

2020-10-19 08:52 UTC, kostaspap approved these changes
Thanks for the awesome contribution @rynjms !

2020-10-19 09:03 UTC, merged

2020-10-19 09:30 UTC, 3nvi commented
@all-contributors please add @rynjms for Code