Remove unnecessary CFN references
panther-labs/panther pull request #1884
Opened 2020-10-29 05:01 UTC by austinbyers

## Background

Every resource dependency (`!Ref`, `!Sub`, or `!GetAtt`) slows down both Panther deployment and teardown, because CloudFormation has to wait for the first resource to completely finish before moving on to the next.

In our 3 main stacks (core, cloud-security, log-analysis), I noticed we have many references that are really just sharing names:

- Alarm groups (custom resources) are passed the function/queue/table name
- IAM policies for Lambda functions
- Environment variables for Lambda functions

In all of these cases, the reference can be replaced with the explicit resource name; it doesn't matter what order they are created in. You can create alarms, policies, and environment variables even if the associated resource doesn't exist yet.

----

Here's an example of flattening the dependency tree by removing unnecessary dependencies. Today, we have:

- LogProcessorDLQ
   - LogProcessorDLQAlarms
   - LogProcessorQueue
      - LogProcessorQueueAlarms
      - LogProcessorFunction
        - LogProcessorAlarms

But all of the alarms (and the function's IAM role) can be created immediately because we know what the queue and function names will be:

- LogProcessorDLQ
  - LogProcessorQueue
    - LogProcessorFunction
- LogProcessorDLQAlarms
- LogProcessorQueueAlarms
- LogProcessorAlarms

(If the queue weren't an event source for the function, the function itself could also be created at the beginning.) Besides removing one level of the dependency tree, it pushes most resources to the beginning, which allows CFN to parallelize everything more efficiently.

---

What will bother developers is the duplication of the resource names - the same Dynamo table name, for example, now has to be copied to everywhere else in the template that references that table. Personally, I don't think that's a big deal:

- We already have to list the resource name explicitly for "cross-stack" references
- Typos are caught very easily during deployment (functions will fail fast if their permissions/environment variables are not correct)
- Typing `!Ref MyQueue` vs `panther-my-queue` is about the same amount of work and both options are susceptible to copy-pasta bugs
- If the duplication really bugs everyone, we can use Mappings to copy the same value everywhere, like we already do with Timeout and Memory.

## Changes

- Remove all resource references that aren't necessary for dependency ordering

## Testing

- Deployed to `us-east-1`, app works fine, no CW alarms
- Deploy time is slightly improved for all 3 stacks:

![Deploy Time](https://user-images.githubusercontent.com/3608925/97527627-2446e180-1982-11eb-889b-2548fc5a6422.png)

- Teardown time is about the same:
![Teardown Time](https://user-images.githubusercontent.com/3608925/97527628-2446e180-1982-11eb-8b67-56245cdc7198.png)

These were tested in us-east-1 as fresh deploy/teardowns. Certainly not scientifically rigorous and subject to AWS "weather," but certainly suggests an overall improvement

2020-10-29 08:56 UTC, kostaspap approved these changes
LGTM

2020-10-29 08:56 UTC, kostaspap commented on deployments/cloud_security.yml
> +      QueueName: panther-alert-processor-queue
Interesting. So CW will not fail if you try to setup alarms for a queue that doesn't exist? I assume you have check the custom-resources Lambda for errors during deployment?

2020-10-29 08:56 UTC, kostaspap commented on deployments/cloud_security.yml
> +          SNAPSHOT_QUEUE_URL: !Ref SnapshotQueue # queue is an event source; needs to exist first
I see that `PollerFunction` has a dependency on `SnapshotQueue` declared in line 1339. Doesn't this mean you could also construct the ARN here as you do in other cases?

2020-10-29 14:32 UTC, nhakmiller approved these changes

2020-10-29 14:32 UTC, nhakmiller commented on deployments/cloud_security.yml
>          - Id: KeyValueStore
It's not that big of a deal, but for the rules engine you condensed these four separate inlined policies (resource lookup, KeyValueStore, GetPantherPolicySecrets, GetPantherAnalysisSecrets) into a single inline policy with three statements. For consistency's sake you could do that here as well.

2020-10-30 18:30 UTC, austinbyers commented on deployments/cloud_security.yml
> +      QueueName: panther-alert-processor-queue
> So CW will not fail if you try to setup alarms for a queue that doesn't exist?

Correct - CloudWatch alarms are just thresholds on _metrics_, they don't care if the associated infrastructure exists yet.

 > I assume you have checked the custom-resources Lambda for errors during deployment?

I checked for CW alarms, and there were none, but I should also search the logs as well, good idea. I'll deploy again and check logs to make sure there weren't any warnings or errors I might have missed

2020-10-30 18:32 UTC, austinbyers commented on deployments/cloud_security.yml
> +          SNAPSHOT_QUEUE_URL: !Ref SnapshotQueue # queue is an event source; needs to exist first
Yeah, here it doesn't matter whether we do the `!Ref` or the explicit construction because there is already a dependency in the events. I'll go ahead and switch it to be explicit just to be consistent - that way we only use `!Ref` when we really need it

2020-10-30 18:32 UTC, austinbyers commented on deployments/cloud_security.yml
>          - Id: KeyValueStore
Sure! Good idea. I might do another pass of all the IAM policies in general, we have a bad habit of making a new inline policy for every individual action

2020-10-30 20:20 UTC, austinbyers commented
I'm running out of time today; since this could introduce subtle bugs and I'll be out next week, I'm going to wait to finish this until I get back

2020-11-09 18:53 UTC, austinbyers commented
Holding off on merging until I finish removing gateways

2020-11-24 22:08 UTC, austinbyers commented
This is once again ready for review. I've updated the branch (wow, it's almost been a month already), addressed the feedback, and am doing a fresh deploy to make sure there are no problems.

I'll make sure each page of the web app still works, integration tests pass, and no CloudWatch alarms were triggered during deployment

2020-11-24 22:08 UTC, austinbyers commented on deployments/cloud_security.yml
>          - Id: KeyValueStore
Done

2020-11-24 22:10 UTC, austinbyers commented on deployments/cloud_security.yml
> +          SNAPSHOT_QUEUE_URL: !Ref SnapshotQueue # queue is an event source; needs to exist first
I updated all the environment variables to construct the resource explicitly, even if the same resource has to be referenced as an event source.

Besides being consistent, the event source may actually become a separate resource, in which case this will help the Lambda functions deploy faster

2020-11-25 08:57 UTC, kostaspap approved these changes

2020-11-25 13:57 UTC, rleighton requested changes
Nice clean up! 

I have concerns about losing dependencies of the lambda functions on tables and queues. Couldn't there be cases when a function runs soon after an initial  deploy but a table/queue does not exist? This depends on each function but we did not need to worry about it when we had true dependencies.

Updates of ddb table schema/indexes are another concern when deploying over a running system. Now a lambda could read a ddb table but perhaps it has not been changed to the new version of the schema with an expected added column or index. If we kept dependencies then it is not a concern.

Thoughts?

2020-11-25 13:57 UTC, rleighton commented on deployments/cloud_security.yml
> +          TABLE_NAME: panther-alert-forwarder
I assume this breaks the dependency on the ddb table. If the ddb table schema changes and we do an update to a running system, can't this break things?

2020-11-25 13:57 UTC, rleighton commented on deployments/cloud_security.yml
> +      TableName: panther-alert-forwarder
Not sure about losing dependencies on ddb tables ... see previous comment.

2020-11-25 13:57 UTC, rleighton commented on deployments/cloud_security.yml
> +          COMPLIANCE_TABLE: panther-compliance
Not sure about losing dependencies on ddb tables ... see previous comment.

2020-11-25 13:57 UTC, rleighton commented on deployments/cloud_security.yml
> +          SQS_QUEUE_URL: !Sub https://sqs.${AWS::Region}.${AWS::URLSuffix}/${AWS::AccountId}/panther-remediation-queue
Could this introduce a race during deployment?

2020-11-25 13:57 UTC, rleighton commented on deployments/cloud_security.yml
> +              Resource: !Sub arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:panther-remediation-queue
Another race possible? Lambda executes and no q?

2020-11-25 13:57 UTC, rleighton commented on deployments/cloud_security.yml
>        FunctionName: panther-resources-api
Not sure about losing dependencies on ddb tables ... see previous comment.

2020-11-25 13:57 UTC, rleighton commented on deployments/cloud_security.yml
> +          RESOURCES_QUEUE_URL: !Sub https://sqs.${AWS::Region}.${AWS::URLSuffix}/${AWS::AccountId}/panther-resources-queue
Possible execution race?

2020-11-25 13:57 UTC, rleighton commented on deployments/cloud_security.yml
> -              Action:
No longer used?

2020-11-25 13:57 UTC, rleighton commented on deployments/cloud_security.yml
> +          SNAPSHOT_QUEUE_URL: !Sub https://sqs.${AWS::Region}.${AWS::URLSuffix}/${AWS::AccountId}/panther-snapshot-queue
Race on initial deploy possible?

2020-11-25 13:57 UTC, rleighton commented on deployments/cloud_security.yml
> +          SNAPSHOT_POLLERS_QUEUE_URL: !Sub https://sqs.${AWS::Region}.${AWS::URLSuffix}/${AWS::AccountId}/panther-snapshot-queue
Race on deploy possible?

2020-11-25 13:57 UTC, rleighton commented on deployments/core.yml
> +          ORG_TABLE_NAME: panther-organization
Not sure about losing dependencies on ddb tables ... see previous comment.

2020-11-25 13:57 UTC, rleighton commented on deployments/core.yml
> +          TABLE: panther-analysis
Not sure about losing dependencies on ddb tables ... see previous comment.

2020-11-25 13:57 UTC, rleighton commented on deployments/core.yml
> +          OUTPUTS_TABLE_NAME: panther-outputs
Not sure about losing dependencies on ddb tables ... see previous comment.

2020-11-25 13:57 UTC, rleighton commented on deployments/core.yml
> +          ALERT_QUEUE_URL: !Sub https://sqs.${AWS::Region}.${AWS::URLSuffix}/${AWS::AccountId}/panther-alerts-queue
Race on deploy?

2020-11-25 13:57 UTC, rleighton commented on deployments/core.yml
> +          TABLE_NAME: panther-source-integrations
Not sure about losing dependencies on ddb tables ... see previous comment.

2020-11-25 13:57 UTC, rleighton commented on deployments/core.yml
> +          LOG_TYPES_TABLE_NAME: panther-logtypes
Not sure about losing dependencies on ddb tables ... see previous comment.

2020-11-25 13:57 UTC, rleighton commented on deployments/log_analysis.yml
> +          ALERTS_TABLE_NAME: panther-log-alert-info
Not sure about losing dependencies on ddb tables ... see previous comment.

2020-11-25 13:57 UTC, rleighton commented on deployments/log_analysis.yml
> +          ALERTS_TABLE: panther-log-alert-info
Not sure about losing dependencies on ddb tables ... see previous comment.

2020-11-25 13:57 UTC, rleighton commented on deployments/log_analysis.yml
> +          QUEUE_URL: !Sub https://sqs.${AWS::Region}.${AWS::URLSuffix}/${AWS::AccountId}/panther-datacatalog-updater-queue
Race on initial deploy?

2020-11-25 13:57 UTC, rleighton commented on deployments/log_analysis.yml
> +          ALERTS_DEDUP_TABLE: panther-log-alert-dedup
Not sure about losing dependencies on ddb tables ... see previous comment.

2020-11-25 13:57 UTC, rleighton commented on deployments/log_analysis.yml
> +          STREAM_NAME: panther-forwarder-firehose
Race on initial deploy?

2020-11-25 16:01 UTC, nhakmiller commented on deployments/cloud_security.yml
> +          TABLE_NAME: panther-alert-forwarder
Dynamo tables are schema-less, if a lambda refers to new/old columns dynamo will just return nothing if it has nothing there is my understanding. When we start using new columns, we generally try to make it backwards compatible by treating nothing being there as a default situation, but not always possible.

2020-11-25 19:58 UTC, nhakmiller approved these changes

2020-11-25 20:20 UTC, austinbyers commented on deployments/cloud_security.yml
> +          TABLE_NAME: panther-alert-forwarder
Right, changes to the *schema* would actually require destroying the table, and so we never do schema changes. Adding new columns is managed only in the Lambda functions, not in the Dynamo resource (that's what it means to be noSQL)

However, after chatting offline with @rleighton, he clarified: if we add a new Dynamo index, and update the Lambda functions to use that index, the Lambda update could happen first, and the function would start failing trying to read an index which doesn't exist.

I hadn't thought of that race condition, and there could be others like it. I'm going to go ahead and revert the references in the Lambda functions, but I'll keep the explicit naming in the alarm custom resources. Hopefully, that gives a bit of the extra speed without introducing any new race conditions (the alarm ordering really truly does not matter)

2020-11-25 20:21 UTC, austinbyers commented on deployments/cloud_security.yml
> -              Action:
Ah, no - when you have an event source, the Serverless transform automatically adds the necessary permissions to use it.

Since SQS is feeding this function, we don't need a separate policy to allow reading SQS messages - one will be added automatically

2020-11-25 20:26 UTC, austinbyers commented on deployments/cloud_security.yml
> +      TableName: panther-alert-forwarder
This one is just used for the Dynamo alarm group, no race condition

2020-11-25 20:27 UTC, austinbyers commented on deployments/cloud_security.yml
> +          COMPLIANCE_TABLE: panther-compliance
Will revert

2020-11-25 20:28 UTC, austinbyers commented on deployments/cloud_security.yml
> +          SQS_QUEUE_URL: !Sub https://sqs.${AWS::Region}.${AWS::URLSuffix}/${AWS::AccountId}/panther-remediation-queue
Not likely, but reverting change

2020-11-25 20:29 UTC, austinbyers commented on deployments/cloud_security.yml
> +              Resource: !Sub arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:panther-remediation-queue
Reverted

2020-11-25 20:30 UTC, austinbyers commented on deployments/cloud_security.yml
> +          RESOURCES_QUEUE_URL: !Sub https://sqs.${AWS::Region}.${AWS::URLSuffix}/${AWS::AccountId}/panther-resources-queue
Reverted

2020-11-25 20:31 UTC, austinbyers commented on deployments/cloud_security.yml
>        FunctionName: panther-resources-api
Reverting

2020-11-25 20:33 UTC, austinbyers commented on deployments/cloud_security.yml
> +          SNAPSHOT_QUEUE_URL: !Sub https://sqs.${AWS::Region}.${AWS::URLSuffix}/${AWS::AccountId}/panther-snapshot-queue
No, because the queue is still referenced in the event-source mapping. Reverting nontheless

2020-11-25 20:33 UTC, austinbyers commented on deployments/cloud_security.yml
> +          SNAPSHOT_POLLERS_QUEUE_URL: !Sub https://sqs.${AWS::Region}.${AWS::URLSuffix}/${AWS::AccountId}/panther-snapshot-queue
Reverting

2020-11-25 20:35 UTC, austinbyers commented on deployments/core.yml
> +          ORG_TABLE_NAME: panther-organization
Reverting

2020-11-25 20:35 UTC, austinbyers commented on deployments/core.yml
> +          TABLE: panther-analysis
Reverting

2020-11-25 20:36 UTC, austinbyers commented on deployments/core.yml
> +          OUTPUTS_TABLE_NAME: panther-outputs
Reverting

2020-11-25 20:38 UTC, austinbyers commented on deployments/core.yml
> +          ALERT_QUEUE_URL: !Sub https://sqs.${AWS::Region}.${AWS::URLSuffix}/${AWS::AccountId}/panther-alerts-queue
Reverting

2020-11-25 20:38 UTC, austinbyers commented on deployments/core.yml
> +          TABLE_NAME: panther-source-integrations
Reverting

2020-11-25 20:39 UTC, austinbyers commented on deployments/core.yml
> +          LOG_TYPES_TABLE_NAME: panther-logtypes
Reverting

2020-11-25 20:47 UTC, austinbyers commented
This wasn't a high-priority PR, more of an experiment I played with late one night :) Reverting changes to the Lambda functions, no need to introduce new race conditions just for the sake of slightly faster deploys

But we have hundreds of alarms and those are still building with the explicit resource name. That change alone should be enough to shave a few seconds off of each stack

2020-11-25 21:19 UTC, rleighton approved these changes

2020-11-25 21:30 UTC, merged