Update tables only if integration adds new log types
panther-labs/panther pull request #2006
Opened 2020-11-11 17:37 UTC by kostaspap

## Background

Update tables only if integration adds new log types

## Changes

- Update tables only if integration adds new log types

## Testing

- mage test:ci

2020-11-11 17:43 UTC, giorgosp approved these changes

2020-11-11 17:48 UTC, rleighton commented on internal/core/source_api/api/update_integration.go
> +func slicesEqual(left, right []string) bool {
How about moving this to `pkg/stringset' ?

2020-11-11 17:48 UTC, rleighton commented on internal/core/source_api/api/update_integration.go
> +	if err := updateTables(existingIntegrationItem, input); err != nil {
Why move this? Makes the diff bigger.

2020-11-11 17:48 UTC, rleighton commented on internal/core/source_api/api/update_integration.go
> +func updateTables(item *ddb.Integration, input *models.UpdateIntegrationSettingsInput) error {
Unit test for this to confirm behavior?

2020-11-11 18:00 UTC, kostaspap commented on internal/core/source_api/api/update_integration.go
> +	if err := updateTables(existingIntegrationItem, input); err != nil {
It needs to. The `normalizeIntegration` modifies the `existingIntegrationitem` - replaces old logtypes with what's inside the input. 

Code could take some further cleanup tbh just didn't want to do bigger changes.

2020-11-12 06:57 UTC, kostaspap commented on internal/core/source_api/api/update_integration.go
> +func slicesEqual(left, right []string) bool {
Done

2020-11-12 06:57 UTC, kostaspap commented on internal/core/source_api/api/update_integration.go
> +func updateTables(item *ddb.Integration, input *models.UpdateIntegrationSettingsInput) error {
Done. Fixed a couple of tests on the way.

2020-11-12 07:15 UTC, kostaspap commented on pkg/stringset/stringset.go
> +func SlicesEqual(left, right []string) bool {
Thought of renaming the file to `stringutils` or something, but I thought it could make the PR more difficult to read

2020-11-12 10:59 UTC, rleighton approved these changes

2020-11-12 13:07 UTC, alxarch commented on internal/core/source_api/api/update_integration.go
> +func slicesEqual(left, right []string) bool {
No, why? Stringset is supposed to be only about distinct sets of strings, not any thing involving string slices.

2020-11-12 13:09 UTC, alxarch commented on pkg/stringset/stringset.go
> +func SlicesEqual(left, right []string) bool {
Yes, exactly the reason it is not named utils. It is meant to be strictly about distinct sets of string values.

2020-11-12 13:09 UTC, kostaspap commented on internal/core/source_api/api/update_integration.go
> +func slicesEqual(left, right []string) bool {
@alxarch should I create a new package `stringslices`? Or maybe just rename the package to `stringutils` or something (see [comment](https://github.com/panther-labs/panther/pull/2006#discussion_r521882904))

2020-11-12 13:29 UTC, alxarch commented on internal/core/source_api/api/update_integration.go
> +func slicesEqual(left, right []string) bool {
There is no reason moving this in another package in the first place. Moving any useful little function to another package just fragments the code organisation. My suggestion is to just keep it there and use the rule of 3 to decide if it is worthy of being shared.

2020-11-12 13:46 UTC, alxarch requested changes
Please add unit tests that verify the comparison function for all diff scenarios (add, remove, reorder) and make sure that user input is guaranteed to hold unique values when we check with the values from the existing record.

2020-11-12 13:46 UTC, alxarch commented on pkg/stringset/stringset.go
> +func SlicesEqual(left, right []string) bool {
Are you certain that the method works in all possible diff scenarios (add, remove, reorder)? 
I would sort both slices first and go over comparing each value after. 
It is less performant, but does not assume the slices contain distinct items so it is independent from the arguments.
I think this function assumes each of the slices contain unique items.

2020-11-12 13:55 UTC, kostaspap commented on pkg/stringset/stringset.go
> +func SlicesEqual(left, right []string) bool {
Right that is the assumption since the LogTypes are unique (we store them as stringset in DDB) so I went for a more performant. However performance is not that important here, I can just sort them and do a deep equals for the slices. 
Better safeguard it against future use.

2020-11-12 14:10 UTC, kostaspap commented on internal/core/source_api/api/update_integration.go
> +func slicesEqual(left, right []string) bool {
Fine by me. Moving to `update_integration.go`. Note though that most of the functions in `stringset.go` are also used only in single place (and most of them not even used outside the package).

2020-11-12 15:54 UTC, alxarch commented on internal/core/source_api/api/update_integration.go
> +func slicesEqual(left, right []string) bool {
Yes, I agree. Strigset was moved to pass review in urgency. I think there are places where I have had to write the exact same functions again. I need to find where and replace them with `stringset` calls.

2020-11-12 15:56 UTC, alxarch approved these changes
LGTM

2020-11-12 17:35 UTC, rleighton commented
Probably should run `mage test:integration`

2020-11-12 21:38 UTC, s0l0ist commented
Passes integration tests

2020-11-12 22:32 UTC, s0l0ist commented
Holding for v1.12.1

2020-11-12 23:10 UTC, giorgosp commented on internal/core/source_api/api/update_integration.go
> +	// If log types haven't been updated, return
If the user removes a log type, the code will still send the CreateTablesMessage. Is this expected behavior? If yes, I suggest we add a comment. This way, someone that suspects about this bug won't lose time trying to reproduce/fix/communicate it.

I'd also add this test case to the tests:
```
{
			first:  []string{"a", "b", "c"},
			second: []string{"a", "b"},
			expect: false,
		},
```

Also, `slicesContainSameElements()` could be simplified to (pseudocode):
```
shouldUpdateTables() {
    for lt in newLogTypes
          if lt not in existingLogTypes
                  return False
    return True
}
```

2020-11-13 08:33 UTC, kostaspap commented on internal/core/source_api/api/update_integration.go
> +	// If log types haven't been updated, return
This is a good point. I wrote the PR initially as a quick fix to an issue we were experiencing in a very specific scenario (we were triggering the "Create table" workflow whenever someone was updating an OAuth2 token). But you are right, we don't want to trigger the "Create table" if the just removed a log type. 

Updated.

2020-11-13 09:32 UTC, giorgosp approved these changes

2020-11-13 12:36 UTC, rleighton approved these changes

2020-11-13 12:36 UTC, rleighton commented on internal/core/source_api/api/update_integration_test.go
> +		{
Cab you add a case where the lengths are the same but true:
```
{
			old:    []string{"Log.A", "Log.B"},
			new:    []string{"Log.C", "Log.D"},
			expect: true,
},
```

2020-11-13 12:36 UTC, rleighton commented on internal/core/source_api/api/check_integration.go
> +		health.SqsStatus.Message = "Queue does not exist yet (old time setup)."
Old?

2020-11-13 12:37 UTC, rleighton commented
reminder: @s0l0ist,  I really do not want to give Figma or Boxycharm 1.12 w/out this added.

2020-11-13 12:51 UTC, kostaspap commented on internal/core/source_api/api/check_integration.go
> +		health.SqsStatus.Message = "Queue does not exist yet (old time setup)."
ah, Goland renamed more than it should

2020-11-13 12:54 UTC, kostaspap commented on internal/core/source_api/api/update_integration_test.go
> +		{
Added

2020-11-13 12:54 UTC, kostaspap commented on internal/core/source_api/api/check_integration.go
> +		health.SqsStatus.Message = "Queue does not exist yet (old time setup)."
Fixed

2020-11-13 13:05 UTC, merged