SNS Title Input Validation
panther-labs/panther pull request #2047
Opened 2020-11-18 00:21 UTC by horakj

## Background

Issue sending to SNS destinations sometimes #1947

## Changes

- Added SNS Helper function
     - additional Title Input Validation
     - additional SNS API Call after first attempt failure
          - Second call replaces Title with "Panther New Alert"

## Testing
- Independent main
- mage test:go
- mage test:ci
- dev panther UI

2020-11-18 01:51 UTC, nhakmiller reviewed
Nice first PR! Thanks for grabbing this one.

Can you add a unit test as well? We already have some unit tests around this function, you can just expand those to include at least one case where a newline character is removed.

2020-11-18 01:51 UTC, nhakmiller commented on internal/core/alert_delivery/outputs/sns.go
> +	fmt.Println("Function Here")
Looks like some debugging output, lets remove this.

2020-11-18 01:51 UTC, nhakmiller commented on internal/core/alert_delivery/outputs/sns.go
> +	if err != nil {
Do you know what type of error gets returned when the title is invalid? Ideally we could handle just this type of error specially and for other errors follow the normal path.

We can do this by first trying to force the error into an `awserr.Error`, and then checking its `Code()` or  `Message()` function to see what the error code/message is. See here for an example: https://github.com/panther-labs/panther/blob/master/internal/compliance/snapshot_poller/pollers/aws/iam_user.go#L84-L93.

2020-11-18 01:51 UTC, nhakmiller commented on internal/core/alert_delivery/outputs/sns.go
> +	return result, err
You can re-use these same named variables from above and re-write this to:

```
		result, err = snsClient.Publish(snsMessageInput)
	}
	return result, err
```

2020-11-18 01:51 UTC, nhakmiller commented on internal/core/alert_delivery/outputs/sns.go
> +	// }
Lets cut this dead code here if we don't need it anymore.

2020-11-18 01:51 UTC, nhakmiller commented on internal/core/alert_delivery/outputs/sns.go
> +	// response, err := snsClient.Publish(snsMessageInput)
Cut this as well.

2020-11-18 08:27 UTC, kostaspap commented on internal/core/alert_delivery/outputs/sns.go
> +	// response, err := snsClient.Publish(snsMessageInput)
Another way to do it (I believe more clean) is to create a new function `func formatTitle(string) string` that you just pass it the existing title and it removes the new line characters and truncates it. 
Then the only change required would be to replace line 110 with 
```
Subject: aws.String(formatTitle(title))
```

2020-11-18 08:28 UTC, kostaspap commented on internal/core/alert_delivery/outputs/sns.go
> +		*snsMessageInput.Subject = title[0:100]
1. You can define a local constant `const maxTitleSize = 100` and reuse it
2. Instead of `title[0:100]` you can just write `title[:100]`

2020-11-18 15:46 UTC, horakj commented on internal/core/alert_delivery/outputs/sns.go
> +	// response, err := snsClient.Publish(snsMessageInput)
There are a few rare edge cases according to AWS SNS Documentation that can return a format error, the new line error seems to be most common. With the additional api call we can handle the edge cases which are difficult to filter out via regex or replace method, but you are right with making it cleaner.

2020-11-18 15:46 UTC, horakj commented on internal/core/alert_delivery/outputs/sns.go
> +		*snsMessageInput.Subject = title[0:100]
Thank you. I will make that adjustment.

2020-11-18 15:47 UTC, horakj commented on internal/core/alert_delivery/outputs/sns.go
> +	// response, err := snsClient.Publish(snsMessageInput)
Thank you for the feedback, making adjustment.

2020-11-18 15:47 UTC, horakj commented on internal/core/alert_delivery/outputs/sns.go
> +	// }
Thank you for the feedback, making adjustment.

2020-11-18 15:49 UTC, horakj commented on internal/core/alert_delivery/outputs/sns.go
> +	if err != nil {
Right now it is a catch all control, changing to the specific syntax error would be more exact.

2020-11-18 15:50 UTC, horakj commented on internal/core/alert_delivery/outputs/sns.go
> +	return result, err
Thank you for the feedback, making adjustment.

2020-11-18 15:51 UTC, horakj commented on internal/core/alert_delivery/outputs/sns.go
> +	fmt.Println("Function Here")
How did that get there? Good Catch.

2020-11-18 16:27 UTC, nhakmiller commented on internal/core/alert_delivery/outputs/sns.go
> +	// response, err := snsClient.Publish(snsMessageInput)
Either way, I do really like the "send message, try to catch the error, if there is an invalid parameter error resend with different title" approach that you've done.  Which parts are split out into the helper or not don't matter to me  too  much, but definitely keep with this approach I'd say.

2020-11-18 16:45 UTC, horakj commented on internal/core/alert_delivery/outputs/sns.go
> +	return result, err
Update. GO does not like removing the Line 62 "return result, err" within the if statement  because they are deemed unused variables. Suggestions?

2020-11-18 16:54 UTC, nhakmiller commented on internal/core/alert_delivery/outputs/sns.go
> +	return result, err
Did you also change `:=` to `=` on  line 61? `:=` means "create new variables with the names on the left hand side and assign the values on the right hand side",  whereas  just `=` means "use existing variables with the names on the left hand side and assign to them the values on the right hand side". Kind of a subtle difference there, but one that go will be sure to remind you about.

2020-11-18 17:18 UTC, horakj commented on internal/core/alert_delivery/outputs/sns.go
> +	return result, err
Yep, missed that one, thank you.

2020-11-23 07:37 UTC, kostaspap requested changes

2020-11-23 07:37 UTC, kostaspap commented on pkg/testutils/awsmocks.go
>  	}
The mock shouldn't define such functionality - this code is used by ALL of our codebase. 
In order to mock the SNS client behavior, you should write something like this in your tests: 
```
mockSns := &testutils.SnsMock{}
....
mockSns.On("Publish", mock.Anything).Return(&sns.PublishOutput{}, errors.New"Invalid subject")
```
Not sure how this if condition slipped in or who added it but it shouldn't exist at all. At least, we shouldn't be building on top of it but look to completely remove it if not in this, in a later PR.

2020-11-23 07:37 UTC, kostaspap commented on internal/core/alert_delivery/outputs/sns.go
> +	}
This code should be moved up after line 83 and can be something like:
```
title = strings.ReplaceAll(title, "\n", "")
if len(title) > maxTitleSize {
    title = title[:maxTitleSize-3] + "..." 
}
```
We use the three dots `...` as an indication that input has been truncated in other parts of the code as well.

2020-11-23 07:37 UTC, kostaspap commented on internal/core/alert_delivery/outputs/sns.go
> +					zap.L().Error("Failed to send message to SNS topic", zap.Error(err))
I don't think we need to log an error here? The caller will log the error afaik.

2020-11-23 07:37 UTC, kostaspap commented on internal/core/alert_delivery/outputs/sns.go
> +			zap.L().Error("Failed to send message to SNS topic", zap.Error(err))
See comment above. I believe this should be removed.

2020-11-23 07:37 UTC, kostaspap commented on internal/core/alert_delivery/outputs/sns.go
> +		if reqErr, ok := err.(awserr.RequestFailure); ok {
awserr.Request failure is a pretty broad error here. Is there a specific code returned by AWS when we send invalid request? Then you could be checking that specifically instead of working with HTTP response codes. See e.g. 
https://github.com/panther-labs/panther/blob/0d52197c921541b62afa8f462e5196899b28d1c7/internal/core/custom_resources/resources/cloud_security_tables.go#L58

2020-11-23 07:38 UTC, kostaspap commented on internal/core/alert_delivery/outputs/sns.go
> +		if reqErr, ok := err.(awserr.RequestFailure); ok {
This logic should have a unit test

2020-11-23 14:32 UTC, nhakmiller commented on pkg/testutils/awsmocks.go
>  	}
I think it adds value. This is a limitation enforced by the AWS API, if other parts of the codebase are making this same mistake isn't it better to catch it in unit testing with something like this? In my ideal world, the mocked client would always return an error whenever the actual API would return an error (based on user input at least). It seems like a more realistic mocked client can only be a good thing.

2020-11-23 14:48 UTC, kostaspap commented on pkg/testutils/awsmocks.go
>  	}
I see how this would be useful, however this is just a mocking library. Adding logic like this changes its purpose. The only thing that it should do is return the value that it has been instructed to return by the unit test. The moment we start adding functionality like this it stops being a mock and it becomes an in-memory SNS. 

The unit test doesn't even have send a field containing new line to verify that we handle it properly. It just has to instruct the SNS Mock to return an "InvalidInputError" (or whatever the AWS SDK returns) when the code tried to invoke a "Publish".

2020-11-23 17:30 UTC, horakj commented on internal/core/alert_delivery/outputs/sns.go
> +	}
We can go one step further and remove an extra line of code
`title := strings.ReplaceAll(generateAlertTitle(alert), "\n", "")`

2020-11-23 18:40 UTC, horakj commented on internal/core/alert_delivery/outputs/sns.go
> +		if reqErr, ok := err.(awserr.RequestFailure); ok {
`if awsErr.Code() == "InvalidParameter"`

2020-11-23 18:41 UTC, horakj commented on internal/core/alert_delivery/outputs/sns.go
> +			zap.L().Error("Failed to send message to SNS topic", zap.Error(err))
removed as many as I could without breaking anything originally defined

2020-11-23 18:56 UTC, nhakmiller approved these changes

2020-11-24 11:07 UTC, kostaspap commented on internal/core/alert_delivery/outputs/sns.go
> +					zap.L().Error("Failed to send message to SNS topic", zap.Error(err))
Logging needs to be removed?

2020-11-24 11:07 UTC, kostaspap commented on internal/core/alert_delivery/outputs/sns.go
> +			if awsErr.Code() == "InvalidParameter" {
We need unit tests for this functionality. 
Basically we need a new unit test that verifies that if the SNS client returns an AWS Error with code `InvalidParameter`, we make a second invocation with the appropriate parameters.

2020-11-24 11:07 UTC, kostaspap commented on internal/core/alert_delivery/outputs/sns_test.go
> +	client.On("Publish", expectedSnsPublishInput).Return(&sns.PublishOutput{}, errors.New("InvalidParameter"))
This doesn't seem to have an effect on the test.

2020-11-24 18:09 UTC, kostaspap commented on internal/core/alert_delivery/outputs/sns.go
> +		return nil, errors.Wrap(err, "failed to parse SNS topic ARN")
The caller is going to log the error - no need for logging here.

2020-11-24 18:12 UTC, kostaspap commented on internal/core/alert_delivery/outputs/sns_test.go
> +func TestTruncateSnsTitle(t *testing.T) {
created new test to verify we do truncate email subjects properly.

2020-11-24 18:12 UTC, kostaspap approved these changes

2020-11-25 15:49 UTC, merged