Theodore edit enhancements
panther-labs/panther pull request #2056
Opened 2020-11-18 18:28 UTC by vorillaz

## Description

This is a big one as it splits the actual Policy and Rule editing in multiple tabs.
Furthermore it add a new look and feel for policy view.
Closes #1887 and #1752.

### Screenshots:
![Screenshot 2020-11-18 at 8 23 47 PM](https://user-images.githubusercontent.com/1022166/99571761-6c36b280-29dc-11eb-941c-3d817e213d15.png)
![Screenshot 2020-11-18 at 8 23 55 PM](https://user-images.githubusercontent.com/1022166/99571769-6e990c80-29dc-11eb-9b2e-e0db1b4898d8.png)
![Screenshot 2020-11-18 at 8 24 06 PM](https://user-images.githubusercontent.com/1022166/99571777-70fb6680-29dc-11eb-9189-44f103771c92.png)
![Screenshot 2020-11-18 at 8 24 15 PM](https://user-images.githubusercontent.com/1022166/99571791-73f65700-29dc-11eb-8a63-c9444c2a2063.png)
![Screenshot 2020-11-18 at 8 24 57 PM](https://user-images.githubusercontent.com/1022166/99571808-78227480-29dc-11eb-8593-3a1e47d4bde4.png)
![Screenshot 2020-11-18 at 8 25 10 PM](https://user-images.githubusercontent.com/1022166/99571818-7ce72880-29dc-11eb-8faf-0281afc7226a.png)
![Screenshot 2020-11-18 at 8 25 17 PM](https://user-images.githubusercontent.com/1022166/99571829-7e185580-29dc-11eb-8148-b1aab277f41f.png)
![Screenshot 2020-11-18 at 8 25 30 PM](https://user-images.githubusercontent.com/1022166/99571835-807aaf80-29dc-11eb-8778-ffc55fc3aa2c.png)

### Checklist:

- [x] Make sure you give an high-level overview of the problem & the solution
- [x] Make sure the related issue is referenced
- [x] Make sure screenshots are added if the UI is changed in any way
- [x] Make sure all of the significant logic is covered by tests
- [x] Make sure your changes are accessible (addition of aria-attributes & correct HTML semantics)

2020-11-19 09:46 UTC, alexmylonas approved these changes
Solid work Theo! Did a code check & UX check and everything looks good.

A couple of comments but nothing too important

2020-11-19 09:46 UTC, alexmylonas commented on web/src/components/buttons/CancelButton/CancelButton.tsx
> +const CancelButton: React.FC<CancelButtonProps> = ({ ...rest }) => {
I understand your reasoning but i think the naming `CancelButton` is misleading. This is dark `LinkButton`.

2020-11-19 09:46 UTC, alexmylonas commented on web/src/pages/PolicyDetails/graphql/policyResources.graphql
> +  resourcesForPolicy(input: $resourcesForPolicyInput) {
👍

2020-11-19 10:32 UTC, vorillaz commented on web/src/components/buttons/CancelButton/CancelButton.tsx
> +const CancelButton: React.FC<CancelButtonProps> = ({ ...rest }) => {
Agreed, I removed the stale component.

2020-11-19 11:18 UTC, 3nvi reviewed
Great work @vorillaz 

Can we please move the changes on the policy details page outside of this PR (issues were related only to creation & edit page)  and put in a separate one after this merges? This is outside the scope of the work and makes reviewing much harder.

Not approving since I need to run the changes, but I'll update my review shortly

2020-11-19 11:18 UTC, 3nvi commented on web/src/components/forms/PolicyForm/PolicyFormAutoRemediationSection/PolicyFormAutoRemediationFields.tsx
> +            data-testid="dropdown-remediation"
nitpick: stop adding test-ids :D we can use `getAllByLabelText('Remediation')[0]`

2020-11-19 11:18 UTC, 3nvi commented on web/src/components/forms/PolicyForm/PolicyFormAutoRemediationSection/PolicyFormAutoRemediationSection.tsx
> +      <Box p={6} data-testid="remediation-loading">
nitpick: you can select by `getByAriaLabel('Loading...')`

2020-11-19 11:18 UTC, 3nvi commented on web/src/components/forms/PolicyForm/PolicyFormAutoRemediationSection/PolicyFormAutoRemediationSection.tsx
> +      <Box p={6} data-testid="remediation-loading">
again, all those boxes can be omitted if you just render the spacing around the place where this component is rendered. IMO this spacing doesn't belong to the component **itself**, but it relates to the specific place where this is rendered.

2020-11-19 11:18 UTC, 3nvi commented on web/src/pages/PolicyDetails/PolicyCardDetails/PolicyCardDetails.tsx
> +const PolicyCardDetails: React.FC<ResourceDetailsInfoProps> = ({ policy }) => {
why did we modify this component? Isn't it ouside the scope of the PR?

Also is this new logic or a copy-paste of the existing one?

2020-11-19 11:36 UTC, vorillaz commented on web/src/components/buttons/SaveButton/SaveButton.tsx
> +const SaveButton: React.FC<SaveButtonProps> = ({ ...rest }) => {
This was repeated more than two times, and eventually all the "Save buttons" will use the same icon. I thought that it might be a good idea overall.

2020-11-19 11:42 UTC, vorillaz commented on web/src/pages/PolicyDetails/PolicyCardDetails/PolicyCardDetails.tsx
> +const PolicyCardDetails: React.FC<ResourceDetailsInfoProps> = ({ policy }) => {
The external wrapper was affecting the component. Since action buttons were moved to the breadcrumb secion the design was looking odd at least, and since the editing was split into tabs I thought that it might be a good idea to pass through the details as the effort was minimal. Obviously, that's just splitting everything into tabs.

2020-11-19 12:36 UTC, 3nvi commented on web/src/components/buttons/SaveButton/SaveButton.tsx
> +const SaveButton: React.FC<SaveButtonProps> = ({ ...rest }) => {
I'm not feeling strongly about it. Do as you see fit 😃

2020-11-19 12:42 UTC, 3nvi commented on web/src/components/forms/BaseRuleForm/BaseRuleFormCoreSection/BaseRuleFormCoreSection.tsx
> +      </Box>
```suggestion
        <Text color="navyblue-100" mb={5} mt={8} mb={2}>Additional Information</Text>
```

2020-11-19 12:46 UTC, 3nvi commented on web/src/components/forms/BaseRuleForm/BaseRuleFormCoreSection/BaseRuleFormCoreSection.tsx
>          )}
The UI doesn't match the designs here

* Reference is not in "additional information"
* Threshold is not in "additional information"

2020-11-19 12:48 UTC, 3nvi requested changes
Holding until tests are visible during rule creation

2020-11-19 12:48 UTC, 3nvi commented on web/src/components/forms/BaseRuleForm/BaseRuleFormTestSection/BaseRuleFormTestSection.tsx
> +import {
For some reason in the creation page this is not displayed

<img width="1311" alt="Screen Shot 2020-11-19 at 2 47 34 PM" src="https://user-images.githubusercontent.com/10436045/99668299-35ad7600-2a76-11eb-88a8-4c30603f4b15.png">

2020-11-19 12:51 UTC, 3nvi commented on web/src/components/forms/BaseRuleForm/BaseRuleFormEditorSection/BaseRuleFormEditorSection.tsx
The editor background should be different according to the designs


<img width="1266" alt="Screen Shot 2020-11-19 at 2 50 57 PM" src="https://user-images.githubusercontent.com/10436045/99668696-bf5d4380-2a76-11eb-972c-53a43f0d0d9b.png">
<img width="702" alt="Screen Shot 2020-11-19 at 2 51 33 PM" src="https://user-images.githubusercontent.com/10436045/99668709-c2583400-2a76-11eb-8ff1-6134e3e11c85.png">

2020-11-19 12:54 UTC, 3nvi commented on web/src/components/forms/BaseRuleForm/BaseRuleFormTestSection/BaseRuleFormTestSection.tsx
> +                  <Flex as="ul" wrap="wrap" spacing={4} gridColumn="1/10">
The vertical alignment seems a bit off

<img width="1305" alt="Screen Shot 2020-11-19 at 2 53 29 PM" src="https://user-images.githubusercontent.com/10436045/99668963-1400be80-2a77-11eb-951e-38850f65abbe.png">
<img width="716" alt="Screen Shot 2020-11-19 at 2 53 34 PM" src="https://user-images.githubusercontent.com/10436045/99668966-15ca8200-2a77-11eb-808c-051fa54837b1.png">

2020-11-19 12:58 UTC, 3nvi commented on web/src/components/forms/PolicyForm/PolicyFormAutoRemediationSection/PolicyFormAutoRemediationFields.tsx
>    const autoRemediationSelected = !!autoRemediationSelection[0];
Default value during creation seems off

<img width="1353" alt="Screen Shot 2020-11-19 at 2 56 32 PM" src="https://user-images.githubusercontent.com/10436045/99669311-8a052580-2a77-11eb-8356-17328a75a7d5.png">

2020-11-30 18:52 UTC, vorillaz commented on web/src/components/forms/BaseRuleForm/BaseRuleFormTestSection/BaseRuleFormTestSection.tsx
> +                  <Flex as="ul" wrap="wrap" spacing={4} gridColumn="1/10">
I know right, but initially when there are some tests in place the "create test" is getting weird, thus the "arrow", the test names, and the button are vertically aligned on top.

![Screenshot 2020-11-30 at 8 49 25 PM](https://user-images.githubusercontent.com/1022166/100651321-f3294a80-334d-11eb-9af2-f0765df6ab5a.png)

2020-11-30 18:53 UTC, vorillaz commented on web/src/components/forms/PolicyForm/PolicyFormAutoRemediationSection/PolicyFormAutoRemediationFields.tsx
>    const autoRemediationSelected = !!autoRemediationSelection[0];
Nothing has hanged here, you should pick up remediation first and the editor will show up.

2020-11-30 18:59 UTC, vorillaz commented on web/src/components/forms/BaseRuleForm/BaseRuleFormEditorSection/BaseRuleFormEditorSection.tsx
I know, I tried changing the background according to the designs but using a more light background has visual conflicts with the Ace editor's theme, it's nearly impossible to see the results.
Changing the editor theme requires lots of effort and testing before releasing and lots of thinking, as we should tackle down lots of issues like padding for the editor which is a bit tedious. 
I guess we should change the editor's theme in the near future.

2020-11-30 19:47 UTC, vorillaz commented on web/src/components/forms/PolicyForm/PolicyFormAutoRemediationSection/PolicyFormAutoRemediationSection.tsx
> +      <Box p={6} data-testid="remediation-loading">
Replying to this one for all the spacing related issues mentioned above.
Removed all inner paddings and added `<Flex spacing={6} direction="column" />` and `<Box p={6} />` on the `RuleForm` and `PolicyForm`

2020-11-30 19:50 UTC, vorillaz commented on web/src/components/forms/BaseRuleForm/BaseRuleFormTestSection/BaseRuleFormTestSection.tsx
> +import {
That's definitely a stale screen as the arrow icon has the wrong background. I invited you to my demo environment for testing purposes.

2020-12-03 11:24 UTC, 3nvi requested changes

2020-12-03 11:24 UTC, 3nvi commented on web/src/components/forms/BaseRuleForm/BaseRuleFormTestSection/BaseRuleFormTestSection.tsx
>  import { DetectionTestDefinition, DetectionTestDefinitionInput } from 'Generated/schema';
we can rename this to `DetectionFormTestSection` and put it under `forms/DetectionForm`

2020-12-03 11:24 UTC, 3nvi commented on web/src/components/forms/PolicyForm/PolicyForm.tsx
> +                    <TabPanel data-testid="policy-functions-tabpanel" lazy>
again let's investigate whether `unmountWhenInactive` is worth it

2020-12-03 11:24 UTC, 3nvi commented on web/src/components/forms/PolicyForm/PolicyFormAutoRemediationSection/PolicyFormAutoRemediationFields.tsx
>    const autoRemediationSelected = !!autoRemediationSelection[0];
Still seeing this and I'm on the latest commit on `theodore-edit-enhancements` branch

2020-12-03 11:24 UTC, 3nvi commented on web/src/components/forms/PolicyForm/PolicyFormAutoRemediationSection/PolicyFormAutoRemediationSection.tsx
> +      <Box data-testid="remediation-loading">
optional: we don't need this `<Box>`. We can just as easy do `getByAriaLabel('Loading...')` which is part of `TablePlaceholder` internals

2020-12-03 11:24 UTC, 3nvi commented on web/src/helpers/utils.tsx
> +
This is no longer needed, that's why it has been removed

2020-12-03 11:24 UTC, 3nvi commented on web/src/pages/PolicyDetails/PolicyDetails.tsx
> +      }),
we shouldn't need `convertObjArrayValuesToCsv` anymore. Leave it as is.

2020-12-03 11:24 UTC, 3nvi commented on web/src/pages/PolicyDetails/PolicyDetailsResources/PolicyDetailsResources.tsx
> +      resourcesForPolicyInput: convertObjArrayValuesToCsv({
no need for `convertObjArrayValuesToCsv`

2020-12-10 19:30 UTC, vorillaz commented
Closing this one in favor of smaller upcoming PRs

2020-12-10 19:30 UTC, closed without merging