Refactor glue schema generation and decouple logtypes module from awsglue
panther-labs/panther pull request #2068
Opened 2020-11-19 09:36 UTC by alxarch

## Background

Why are you making this change? Please provide a reference to any related issues and PRs

## Changes

- List your changes here in more detail

## Testing

- How did you test your change?

2020-11-19 15:13 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/columns.go
> +var columnNamesReplacer = strings.NewReplacer(
What about the $ symbol?

2020-11-19 17:48 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/columns.go
> +var columnNamesReplacer = strings.NewReplacer(
Good catch that  got dropped in the merge probably.

2020-11-19 17:50 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/columns.go
> +var columnNamesReplacer = strings.NewReplacer(
Fixed

2020-11-20 08:38 UTC, kostaspap requested changes
This is a good change - but also touches critical parts of the system. How has this been tested E2E? I am mostly worried for the changes in the `mappings`. 

One way I can think of to compare this with the old method is by generating the schemas in the docs - if there's any difference compared to docs generated by the old version, there's an issue :)

2020-11-20 08:38 UTC, kostaspap commented on deployments/log_analysis.yml
> -    MinLength: 1
Why is this removed?

2020-11-20 08:38 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +func inferStructColumns(typ reflect.Type, path []string, names collisions) ([]Column, error) {
What is the `path`? Can you add description/comments that explain the logic?

2020-11-20 08:38 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +	mappings := names.caseSensitiveMappings()
The mappings AFAIK are no needed only for collisions but for all fields but I might be wrong. Have you verified this works E2E?

2020-11-20 08:38 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +		}
Can you elaborate? Why are we excluding it?

2020-11-20 08:38 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +		}
Interesting. Can this really happen? Shouldn't we just throw an error if that happens, why allow it?

2020-11-20 08:38 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +	return !strings.Contains(tag, "omitempty")
Seems this should be "return True".

A field might as well be:
```
Field string `json:",omitempty" validate:"required"`
```
in which case we should mark it as required.

2020-11-20 08:38 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +			return "", newSchemaError(path, "invalid map key %q", key)
I would expand to something like "...only strings allowed as map keys"

2020-11-20 08:38 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +		path = append(path, "[]")
Should this be `{}` or something? `[]` is used for arrays.

2020-11-20 08:38 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/glueschema_test.go
> +		"at_sign_remap":          "at_sign_remap",
can you add test cases for the other conversions as well?

2020-11-20 08:38 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +}
1. Tests for this? Seems like it should be unit tested
2. Have you verified E2E this functionality?

2020-11-20 08:38 UTC, kostaspap commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +		meta := awsglue.NewGlueTableMetadata(models.LogData, desc.Name, desc.Description, awsglue.GlueTableHourly, eventSchema)
Hmmmm, why `models.LogData` here? or it doesn't matter in this context? Can you add a comment to that extend?

2020-11-20 08:38 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/numerics/numerics.go
> +	glueschema.MustRegisterMapping(reflect.TypeOf(Int64(0)), glueschema.TypeBigInt)
We've had this discussion before - we didn't want to do the registration here but do it in a single place. We'll eventually have `snowflakeschema` - should we go and update every "type" to make sure it is registered as well?

2020-11-20 08:38 UTC, kostaspap commented on internal/log_analysis/log_processor/registry/internal/generate.go
> -	availableLogTypes.MustRegister(nativeLogTypes)
👍

2020-11-20 09:14 UTC, alxarch commented on deployments/log_analysis.yml
> -    MinLength: 1
Talked to russ about it. It is not used anymore.

2020-11-20 09:19 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +func inferStructColumns(typ reflect.Type, path []string, names collisions) ([]Column, error) {
Path, is the field path inside the struct tree. We pass it as an arg so we can get helpful error messages when things go wrong. Since this code runs recursively, a stack trace is useless for discovering which field produced the error.  Normal error wrapping would end up with something like: 
```
failed to parse struct "Foo": failed to parse slice "Bar": failed to parse slice element "Bar[]": failed to parse struct field "Baz": invalid field type "function(string){}"
```
With `path` and `newSchemaError` we get:
```
schema error at "Foo.Bar[].Baz": invalid field type "function(string)"
```

2020-11-20 09:21 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +	mappings := names.caseSensitiveMappings()
This produces mappings for all field names. `names` contain all field names discovered in the schema, not only the colliding ones.

2020-11-20 09:22 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +		}
unesported fields are not serializable to/from JSON (unless they are embedded structs, which is covered before this check.

2020-11-20 09:32 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +func inferStructColumns(typ reflect.Type, path []string, names collisions) ([]Column, error) {
You posted few seconds before me it seems :) 
I think it's still useful to have a brief comment about this in the description so readers don't have to go deep into the code to understand its usefulness!

2020-11-20 09:33 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +	return !strings.Contains(tag, "omitempty")
A test would be useful as well

2020-11-20 09:37 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +		}
Yes, it is the skip case. I am updating the `fieldColumnName` function to be more readable.

2020-11-20 09:48 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +	return !strings.Contains(tag, "omitempty")
The example above is not valid for schema purposes. 

Fields marked "omitempty" in JSON, must use "omitempty" for validate also, otherwise they should not have `omitempty` in JSON in the first place.

Nevertheless, the field gets marked as required, appropriately. The `tag` in that function is not `json`, it is `validate`.

What this check tries to achieve, is to catch most `validate` cases where `required` is not used explicitly. 

This was a mistake in the old code. 

If I use
```go
type T struct {
   Foo sting `validate:"eq=Foo"`
}
```
then field `Foo` is required, implicitly.

Keep in mind that `Column.Required` is only relevant for generating docs.

2020-11-20 09:51 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +		path = append(path, "[]")
`[]` is used to index maps as well. For example `foo["bar"]`. The `[]` is meant as a helper to understand that the problematic path is inside the _element_ of  a map/array, not on the field itself. This is only relevant to the error messages displayed so I wouldn't worry about it.

2020-11-20 10:00 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +		meta := awsglue.NewGlueTableMetadata(models.LogData, desc.Name, desc.Description, awsglue.GlueTableHourly, eventSchema)
This is one of the complexities that needs to be addressed in a separate PR for cloudsecurity. The place where this function is used only cares about the 'base' table. It 'magically' derives the `rule_errors` and `rule_matches` tables inside `gluetables` and `athenaviews` functions. This is a mistake in code structure IMO. The helpers in those packages should be oblivious to the connections between tables and only use explicit arguments for names, columns etc. We should investigate better logic separation in a subsequent PR. The scope for this is to achieve decoupling.

2020-11-20 10:02 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/numerics/numerics.go
> +	glueschema.MustRegisterMapping(reflect.TypeOf(Int64(0)), glueschema.TypeBigInt)
Yes, this is the only way we won't end up with cyclic dependencies.
Once we get to `snowflakeschema`, the translation needs to happen based on `logschema` and not reflection. All this is a temporary, complex solution based on `reflect` until then.

2020-11-20 10:03 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/numerics/numerics.go
> +	glueschema.MustRegisterMapping(reflect.TypeOf(Int64(0)), glueschema.TypeBigInt)
The `numerics` should be removed anyway. Did not want to affect the relevant parsers to do it in this PR.

2020-11-20 10:06 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +}
1. Will add a unit test for each case on the `ColumnName` function. For the `InferColumns`, even a single case suffices. 
2. E2E tests for this are my main task for the day, once complete the PR will be undrafted.

2020-11-20 10:07 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/glueschema_test.go
> +		"at_sign_remap":          "at_sign_remap",
Will add on the `ColumnName function`

2020-11-20 10:09 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +			return "", newSchemaError(path, "invalid map key %q", key)
fixed

2020-11-20 10:36 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +		path = append(path, "[]")
Yup, I realized it's for the error message. Was just thinking that maybe having the same symbol both for arrays and maps might be confusing to the user.  Not strong for this one though, up to you.

2020-11-23 18:38 UTC, alxarch commented
After some tests on the current Panther code I concluded that we don't really support case sensitive column names. Glue only accepts [lower case column names](https://docs.aws.amazon.com/athena/latest/ug/glue-best-practices.html#schema-names).
JSON SerDe (the variant we use) allows to have case sensitive mappings from JSON to Glue columns. This actually requires to use different column names in Glue than the field names in JSON to be able to support names that collide (i.e. `userAgent` - `UserAgent`). The collisions only occur at the same depth (i.e. `userAgent` and `event.userAgent` do not collide). With all this combined *it is not possible to support 'transparent' mappings for column names that collide*. What we try to do, is avoid JSON SerDe from failing to parse `jsoniter.RawMessage` because of colliding names. But to keep the 'transparent' mapping of column names, we **need to enforce that no colliding column names exist at the same depth for the defined part of the schema**. 
This PR fails to infer Glue columns if such collisions exist. This is the only way to have a predictable behavior for schemas when Querying with Athena. The schemas defined in OSS all seem to comply. We will have to also check the EE-only ones during sync.

2020-11-24 09:04 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +	mappings := names.caseSensitiveMappings()
Resolved using a different strategy. See below

2020-11-24 09:06 UTC, alxarch commented
Updated the `ColumnName` function to transliterate non-ASCII letters and to handle any non-valid character not in our named character definitions by replacing it with `_`.

2020-11-24 09:07 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +}
The mapping strategy has changed, see comment below.

2020-11-24 12:05 UTC, kostaspap reviewed
Can you add more information? How did you verify that the new mechanism outputs the same Glue schemas as the previous mechanism?

2020-11-24 12:05 UTC, kostaspap commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +		meta := awsglue.NewGlueTableMetadata(models.LogData, desc.Name, desc.Description, awsglue.GlueTableHourly, eventSchema)
Can you add a comment in the code describing that the `LogData` is really irrelevant here?

2020-11-24 12:05 UTC, kostaspap commented on internal/log_analysis/log_processor/logtypes/entry.go
> +	cols, _, _ := glueschema.InferColumnsWithMappings(schema)
Just `glueschema.InferColumns(schema)`.

2020-11-24 12:05 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/columns.go
> +func ColumnName(name string) string {
We need to use the same renaming strategy when writing the data to S3 as JSON we follow here. I don't think the code does it currently.

2020-11-24 12:12 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/columns.go
> +func ColumnName(name string) string {
We do use `ColumnName` in the `ConfigForDataLakeWriters`

2020-11-24 12:19 UTC, alxarch commented on internal/log_analysis/log_processor/logtypes/entry.go
> +	cols, _, _ := glueschema.InferColumnsWithMappings(schema)
fixed

2020-11-24 12:23 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +		meta := awsglue.NewGlueTableMetadata(models.LogData, desc.Name, desc.Description, awsglue.GlueTableHourly, eventSchema)
fixed

2020-11-24 12:29 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/glueschema.go
> +func inferStructColumns(typ reflect.Type, path []string, names collisions) ([]Column, error) {
Added comments for the path argument wherever it is passed to a recursive function.

2020-11-24 12:32 UTC, alxarch commented
> Can you add more information? How did you verify that the new mechanism outputs the same Glue schemas as the previous mechanism?

The new mechanism does not output the same schemas as the old code. The old code had problematic cases. 

What I will try to verify though is that any changes that might show up in generated docs won't be backwards incompatible (i.e. datacatalog updater will have problems). This is hard because we moved docs to EE.
Also I am in the middle of E2E testing this on a clean deployment.

2020-11-24 12:39 UTC, kostaspap commented
> > Can you add more information? How did you verify that the new mechanism outputs the same Glue schemas as the previous mechanism?
> 
> The new mechanism does not output the same schemas as the old code. The old code had problematic cases.

Where are the differences? Are the differences in any of the built-in data types or in specific Custom logs usecases? See my comment on how we can verify that the new schemas are the same as the old ones. See my [comment](https://github.com/panther-labs/panther/pull/2068#pullrequestreview-535192732) on how we could do that - of course you could do it in a different way if we find one such. 

If the schemas coming out of the new mechanism are different from the ones output by the previous mechanism, this will make the data unqueryable. We definitely don't want that.

2020-11-24 12:43 UTC, alxarch commented
> > > Can you add more information? How did you verify that the new mechanism outputs the same Glue schemas as the previous mechanism?
> > 
> > 
> > The new mechanism does not output the same schemas as the old code. The old code had problematic cases.
> 
> Where are the differences? Are the differences in any of the built-in data types or in specific Custom logs usecases? See my comment on how we can verify that the new schemas are the same as the old ones. See my [comment](https://github.com/panther-labs/panther/pull/2068#pullrequestreview-535192732) on how we could do that - of course you could do it in a different way if we find one such.
> 
> If the schemas coming out of the new mechanism are different from the ones output by the previous mechanism, this will make the data unqueryable. We definitely don't want that.

If there are changes in comments, or order of fields, there is no problem to be had. if *types* change for the native logs, we do have a problem but to fix it we should alter the structs to output the correct type, not the schema generation to have wrong logic. I will make a throwaway branch to bring over doc generation from EE so that I can compare.

2020-11-24 12:45 UTC, kostaspap commented
> > > > Can you add more information? How did you verify that the new mechanism outputs the same Glue schemas as the previous mechanism?
> > > 
> > > 
> > > The new mechanism does not output the same schemas as the old code. The old code had problematic cases.
> > 
> > 
> > Where are the differences? Are the differences in any of the built-in data types or in specific Custom logs usecases? See my comment on how we can verify that the new schemas are the same as the old ones. See my [comment](https://github.com/panther-labs/panther/pull/2068#pullrequestreview-535192732) on how we could do that - of course you could do it in a different way if we find one such.
> > If the schemas coming out of the new mechanism are different from the ones output by the previous mechanism, this will make the data unqueryable. We definitely don't want that.
> 
> If there are changes in comments, or order of fields, there is no problem to be had. if _types_ change for the native logs, we do have a problem but to fix it we should alter the structs to output the correct type, not the schema generation to have wrong logic. I will make a throwaway branch to bring over doc generation from EE so that I can compare.

Agree with that overall. Only one thing I don't agree: 
>  if _types_ change for the native logs, we do have a problem but to fix it we should alter the structs to output the correct type, not the schema generation to have wrong logic. 

This will change the scope of this PR though since it will require data migration scripts to be in place. I don't want to do this now.

2020-11-24 14:49 UTC, alxarch commented
After allowing '-' the docs are the same except for the required columns that don't affect the Glue stuff. We had some columns that were required but not showing as such in the docs.

2020-11-24 14:56 UTC, kostaspap approved these changes

2020-11-24 14:56 UTC, kostaspap commented on internal/log_analysis/awsglue/glueschema/columns_test.go
> +		{"συνθηματικό", "synthimatiko"},
I was hoping to see `Μύκονοοοος` in here since it seems to be our go-to Greek reference in log processing :P

2020-11-24 18:21 UTC, kostaspap commented on internal/log_analysis/athenaviews/athenaviews.go
> +	columns, _ := glueschema.InferColumns(table.EventStruct())
We shouldn't ignore the error here. This points to a problem.

2020-11-24 18:28 UTC, alxarch commented on internal/log_analysis/athenaviews/athenaviews.go
> +	columns, _ := glueschema.InferColumns(table.EventStruct())
The main problem is that this code does not return an error in the first place. I can only panic, or refactor this as well.
The error won't be a problem here since we have already checked the log types on registration/creation.

2020-11-24 18:35 UTC, kostaspap commented on internal/log_analysis/athenaviews/athenaviews.go
> +	columns, _ := glueschema.InferColumns(table.EventStruct())
The `glueschema.InferColumns` returns an error . Even if it now panics instead of returning one, this behavior might be altered in the future. 
The `InferColumns` will change overtime and it will rely on the callers to handle errors appropriately.

2020-11-24 18:36 UTC, alxarch commented on internal/log_analysis/athenaviews/athenaviews.go
> +	columns, _ := glueschema.InferColumns(table.EventStruct())
refactored to return errors

2020-11-25 09:21 UTC, kostaspap approved these changes

2020-11-25 10:55 UTC, alxarch commented on internal/log_analysis/awsglue/glueschema/columns_test.go
> +		{"συνθηματικό", "synthimatiko"},
fixed

2020-11-25 11:12 UTC, merged