Sort by displayName by default instead of ID
panther-labs/panther pull request #2087
Opened 2020-11-20 22:30 UTC by AlexPanther

**Description in progress**

## Background

Why are you making this change? Please provide a reference to any related issues and PRs

## Changes

- List your changes here in more detail

## Testing

- How did you test your change?

2020-11-20 23:57 UTC, austinbyers requested changes
You accidentally committed all of the old `api/gateway` files! After I worked so hard to remove them, now you want to add them back 😭 

Just `git rm -r api/gateway` and that should fix it.

Then please update the PR body with a description and steps for how you tested. You can add "closes: https://github.com/panther-labs/panther-enterprise/issues/434" to automatically close the associated issue when the PR merges

2020-11-21 00:06 UTC, austinbyers reviewed
Implementation looks pretty good though! Just some comments about documentation and testing

2020-11-21 00:06 UTC, austinbyers commented on internal/core/analysis_api/handlers/list.go
> +		panic("Unexpected sortBy: " + sortBy)
Let's add a comment here, something like:

```go
// Input validation for the caller already happens in the struct validate tags.
// If we reach this code, it means there is a sortBy allowed in the input validation,
// but not supported in the backend, which should never happen
```

2020-11-21 00:06 UTC, austinbyers commented on internal/core/analysis_api/handlers/list.go
> +		}
Let's add a comment about why we're doing this, since it isn't obvious by looking at it.

E.g.

```go
// The frontend shows display name *or* ID (when there is no display name)
// So we sort the same way it is shown to the user - displayName if available, otherwise ID
```

2020-11-21 00:06 UTC, austinbyers commented on internal/core/analysis_api/handlers/list_rules.go
> +	if input.SortBy == "" {
Nitpick: let's keep the fields in alphabetical order, so this would go before `input.SortDir`

2020-11-21 00:06 UTC, austinbyers commented on internal/core/analysis_api/handlers/list_test.go
> +	paging, truncation := pageItems(items, 1, 1)
Here you're actually testing two different functions. The `pageItems` function already has unit tests; let's keep the unit tests as isolated as possible and test just the `sortByDisplayName` function.

So you would sort the items, and then just verify their sorted order:

```go
	items := []tableItem{
		{ID: "a", DisplayName: "z"},
		{ID: "h", DisplayName: "b"},
		{ID: "c", DisplayName: "y"},
		{ID: "e", DisplayName: "a"},
		{ID: "g", DisplayName: "b"},
		{ID: "b", DisplayName: ""},
	}

	sortByDisplayName(items, true)

	expected := []tableItem{
		{ID: "...", DisplayName: "..."},
	}
	assert.Equal(t, expected, items)
```

2020-11-23 15:17 UTC, AlexPanther commented on internal/core/analysis_api/handlers/list.go
> +		panic("Unexpected sortBy: " + sortBy)
- [ ] Add comment

2020-11-23 15:17 UTC, AlexPanther commented on internal/core/analysis_api/handlers/list.go
> +		}
- [ ] Add comment

2020-11-23 15:18 UTC, AlexPanther commented on internal/core/analysis_api/handlers/list_rules.go
> +	if input.SortBy == "" {
- [ ] Reorder

2020-11-23 15:18 UTC, AlexPanther commented on internal/core/analysis_api/handlers/list_test.go
> +	paging, truncation := pageItems(items, 1, 1)
- [ ] Only test `sortByDisplayName`

2020-11-23 15:37 UTC, AlexPanther commented
> You accidentally committed all of the old `api/gateway` files! After I worked so hard to remove them, now you want to add them back 😭
> 
> Just `git rm -r api/gateway` and that should fix it.
> 
> Then please update the PR body with a description and steps for how you tested. You can add "closes: [panther-labs/panther-enterprise#434](https://github.com/panther-labs/panther-enterprise/issues/434)" to automatically close the associated issue when the PR merges

Well said 😆

2020-11-23 17:56 UTC, austinbyers approved these changes
Congrats on your first change!! 🎉

2020-11-23 18:42 UTC, merged