Fix tests
panther-labs/panther pull request #2088
Opened 2020-11-22 10:28 UTC by kostaspap

## Background

- Fixes #1600 
- Simplifies test logic (100 line reduction!)

## Changes

- Fixes flaky test 'TestSendDataIfTimeLimitHasBeenReached'
- Code reduction

## Testing

- mage test:ci

2020-11-22 10:33 UTC, kostaspap commented on internal/log_analysis/log_processor/destinations/s3_test.go
>  		}
Previously we were giving the goroutine that flushes the buffers only 10ms to complete its operation. Under high CPU load (experienced while running the test suite) sometimes the goroutine wouldn't complete in time, thus the issues reported in #1600 . I'm now giving it more time (100ms) while not slowing down the test execution since i lowered the maxDuration to 100ms from 250ms

2020-11-22 11:17 UTC, kostaspap commented on internal/log_analysis/log_processor/destinations/s3.go
> +	if bs.numBuffers > bs.maxBuffers {
`len(bs.set)` was not the correct way to calculate number of buffers in memory, since it is a `map[time.Time]map[string]*s3EventBuffer`

2020-11-22 11:46 UTC, kostaspap commented on internal/log_analysis/log_processor/destinations/s3_test.go
>  func TestSendDataWhenExceedMaxBuffers(t *testing.T) {
This test would fail with the old code.

2020-11-22 11:50 UTC, kostaspap commented on internal/log_analysis/log_processor/destinations/s3.go
> +		buffersToRemove := (bs.maxBuffers + 1) / 2
In case the maxBuffers was `1`, the previous code wouldn't work.

2020-11-22 12:28 UTC, kostaspap commented on internal/log_analysis/log_processor/destinations/s3_test.go
> +			time.Sleep(2 * destination.maxDuration)
Previously we were giving the goroutine that flushes the buffers only 10ms to complete its operation. Under high CPU load (experienced while running the test suite) sometimes the goroutine wouldn't complete in time, thus the issues reported in #1600 . I'm now giving it more time (100ms) while not slowing down the test execution since i lowered the maxDuration to 100ms from 250ms

2020-11-22 13:06 UTC, alxarch requested changes
The changes seem to be fixing the error we were encountering but we need to make sure that the buffer was actually deleted when decrementing the `numBuffers` counter. 
Overall I want to point out that the code handling this is  very hard to follow and feels like more race conditions are lurking in the shadows. We should rewrite this  ASAP to use context.Context and have clear channel and goroutine flow.

2020-11-22 13:06 UTC, alxarch commented on internal/log_analysis/log_processor/destinations/s3.go
> +	bs.numBuffers--
We are not certain at this point that we actually deleted a buffer. We need another check to see if `buffer.logType` exists in `logTypeToBuffer`

2020-11-23 07:04 UTC, kostaspap commented on internal/log_analysis/log_processor/destinations/s3.go
> +	bs.numBuffers--
I added a check. The way the code is right now this cannot happen (we will always remove an existing buffer from a bufferset) but added for safety. 

I am thinking to eventually move the buffers/buffersets to their own file in the package and have more unit tests to verify their behavior.

2020-11-23 07:12 UTC, kostaspap commented
> Overall I want to point out that the code handling this is very hard to follow and feels like more race conditions are lurking in the shadows. We should rewrite this ASAP to use context.Context and have clear channel and goroutine flow.

Yes, this code and overall log processor code could take some cleanup. Using context.Context and improving code readability is one thing, managing cancellation of all the major goroutines (poller, parsing, destination) is another, better memory management etc 
I don't think its super urgent, but definitely good to do when we get more confident about how the processing flow should look like.

2020-11-23 10:04 UTC, giorgosp approved these changes

2020-11-23 12:20 UTC, alxarch approved these changes
LGTM

2020-11-23 19:37 UTC, austinbyers approved these changes
Thanks so much for the fix!

2020-11-25 13:00 UTC, merged