Add parsers for Duo logs
panther-labs/panther pull request #2112
Opened 2020-11-25 21:34 UTC by giorgosp

## Background

Add parsers for Duo logs.

## Changes

- Add parsers for Duo authentication (v2), administrator, telephony and offine enrollments logs.

## Testing

-  Unit

2020-11-26 08:31 UTC, kostaspap approved these changes

2020-11-26 08:31 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/duologs/authentication.go
> +	IsFirewallEnabled   pantherlog.Bool     `json:"is_firewall_enabled" description:"Reports the firewall state as detected by the Duo Device Health app. One of \"true\", \"false\", or \"unknown\"."`
Bool will not work in the case where it is `unknown`. Should this be string?

2020-11-26 08:31 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/duologs/authentication.go
> +	IsPasswordSet       pantherlog.Bool     `json:"is_password_set" description:"Reports the system password state as detected by the Duo Device Health app. One of \"true\", \"false\", or \"unknown\"."`
See above

2020-11-26 10:58 UTC, giorgosp commented
Added parser for Duo offline enrollment logs. It has an interesting caveat since its fields are the same as the administrator log.

2020-11-26 14:20 UTC, kostaspap commented on internal/log_analysis/log_processor/logtypes/logtesting/logtesting.go
> -	require.False(t, actual.IsZero(), "zero timestamp")
Why was this removed?

2020-11-26 14:20 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/duologs/authentication.go
> +	IsFirewallEnabled   pantherlog.Bool     `json:"is_firewall_enabled" description:"Reports the firewall state as detected by the Duo Device Health app. One of \"true\", \"false\", or \"unknown\"."`
I have contacted Duo support to clarify the content of these logs. 
You should add a FIXME on these fields and we should update once Duo replies.

2020-11-27 11:52 UTC, alxarch commented on internal/log_analysis/log_processor/logtypes/logtesting/logtesting.go
> -	require.False(t, actual.IsZero(), "zero timestamp")
Yup, this is critical to have.

2020-11-27 12:03 UTC, alxarch requested changes
Need to change the `Administrator.Description` to `pantherlog.String`

2020-11-27 12:03 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/duologs/administrator.go
> +	Description  pantherlog.RawMessage `json:"description" description:"String detailing what changed, either as free-form text or serialized JSON."`
The description tag is not a RawMessage. It is a `pantherlog.String`. It states so in the description. When it has JSON form, it is _serialized JSON_. Which means that `RawMessage` not useful here.
The case of 'embedded' JSON is something we do not handle well now. In this particular case where it could also be 'free-form text' it is even harder to solve. I suggest we just use `pantherlog.String` for now.

2020-11-27 12:29 UTC, giorgosp commented on internal/log_analysis/log_processor/logtypes/logtesting/logtesting.go
> -	require.False(t, actual.IsZero(), "zero timestamp")
It produces a cryptic error message. Reverting for now to merge this, but we should improve it.

2020-11-27 12:31 UTC, giorgosp commented on internal/log_analysis/log_processor/parsers/duologs/administrator.go
> +	Description  pantherlog.RawMessage `json:"description" description:"String detailing what changed, either as free-form text or serialized JSON."`
Updated

2020-11-27 12:31 UTC, giorgosp commented on internal/log_analysis/log_processor/parsers/duologs/authentication.go
> +	IsFirewallEnabled   pantherlog.Bool     `json:"is_firewall_enabled" description:"Reports the firewall state as detected by the Duo Device Health app. One of \"true\", \"false\", or \"unknown\"."`
Done

2020-11-27 12:31 UTC, giorgosp commented on internal/log_analysis/log_processor/parsers/duologs/authentication.go
> +	IsPasswordSet       pantherlog.Bool     `json:"is_password_set" description:"Reports the system password state as detected by the Duo Device Health app. One of \"true\", \"false\", or \"unknown\"."`
Done

2020-11-27 12:38 UTC, kostaspap commented on internal/log_analysis/log_processor/logtypes/logtesting/logtesting.go
> -	require.False(t, actual.IsZero(), "zero timestamp")
@giorgosp  update the error message?

2020-11-27 12:50 UTC, giorgosp commented on internal/log_analysis/log_processor/logtypes/logtesting/logtesting.go
> -	require.False(t, actual.IsZero(), "zero timestamp")
Updated. Test error is now:
```
Error:      	Should not be zero, but was 0001-01-01 00:00:00 +0000 UTC
        	Test:       	TestDuoParsers/authentication_logs
        	Messages:   	invalid event time
```

was
```
Error:      	Should be false
        	Test:       	TestDuoParsers/authentication_logs
        	Messages:   	zero timestamp
```

2020-11-27 12:54 UTC, alxarch approved these changes
LGTM

2020-11-27 12:54 UTC, alxarch commented on internal/log_analysis/log_processor/logtypes/logtesting/logtesting.go
> -	require.False(t, actual.IsZero(), "zero timestamp")
GoodEnough

2020-11-27 14:09 UTC, merged