Refactor log processor to use logstream.Stream and context.Context
panther-labs/panther pull request #2145
Opened 2020-11-30 09:46 UTC by alxarch

## Background

Closes #2131 

## Changes

- Adds `logstream` module
- Adds `logstream.LineStream` to parse a log line by line
- Handle gzip auto-detection in `s3pipe` transparently, to avoid unnecessary double buffering
- Pass `context.Context` all the way through to the `processor.run()` method.

## Testing

- mage test:go
- E2E pending

2020-12-02 12:09 UTC, kostaspap requested changes

2020-12-02 12:09 UTC, kostaspap commented on internal/log_analysis/log_processor/s3pipe/s3pipe.go
> +	}
Interesting edge case! Is it possible to add a unit test for it?

2020-12-02 15:47 UTC, rleighton commented on internal/log_analysis/log_processor/processor/logstream/linestream.go
> +	line, isPrefix, err := s.r.ReadLine()
If not, add a comment about `isPrefix`. Not clear to a new reader what is happening here.

2020-12-02 15:47 UTC, rleighton commented on internal/log_analysis/log_processor/processor/processor.go
> +					}
Doesn't closing the channel have the same effect with less code?

2020-12-02 15:47 UTC, rleighton commented on internal/log_analysis/log_processor/processor/stream.go
> +					// This is a temporary workaround to ensure all S3 streams are readable.
I still do not understand the purpose of this ... can you add more to the comment to elaborate?

2020-12-02 16:26 UTC, giorgosp commented on internal/log_analysis/log_processor/processor/logstream/linestream.go
> +	if err := s.err; err != nil {
just `if s.err !=nil` ?

2020-12-02 16:26 UTC, giorgosp commented on internal/log_analysis/log_processor/processor/logstream/linestream.go
> +		// Check for valid UTF8 stream on first read.
Maybe update the comment as to why we do this check if numlines == 0??

2020-12-02 16:26 UTC, giorgosp commented on internal/log_analysis/log_processor/processor/stream.go
> +func readZero(r io.Reader) error {
what is the point of `readZero()` ?

2020-12-02 21:25 UTC, alxarch commented on internal/log_analysis/log_processor/processor/processor.go
> +		p.processLogLine(ctx, string(line), outputChan)
the parsers expect a string. Until that interface changes, the allocation cannot be avoided.

2020-12-02 21:25 UTC, alxarch commented on internal/log_analysis/log_processor/processor/logstream/linestream.go
> +	line, isPrefix, err := s.r.ReadLine()
`ReadBytes` copies the bytes. `ReadLine` returns slices out of the 'live' buffer.

2020-12-02 21:26 UTC, alxarch commented on internal/log_analysis/log_processor/s3pipe/s3pipe.go
> +	}
Not sure if it's easy to time, I'll try

2020-12-02 21:27 UTC, alxarch commented on internal/log_analysis/log_processor/processor/logstream/linestream.go
> +		// Check for valid UTF8 stream on first read.
The comment says 'on first read'. I can move it above if.

2020-12-02 21:29 UTC, alxarch commented on internal/log_analysis/log_processor/processor/processor.go
> +					}
The `ok` here will be true when `dataStreams` has closed. We want to return then and not wait for `ctx.Done()` so that `resultsChannel` closes ASAP.

2020-12-03 07:29 UTC, kostaspap commented on internal/log_analysis/log_processor/s3pipe/s3pipe.go
> +	}
I guess I am not seeing the issue that this is trying to solve. Why is `peek` required? What's the condition that can trigger it?

2020-12-03 07:37 UTC, kostaspap commented on internal/log_analysis/log_processor/processor/stream.go
> +					// This is a temporary workaround to ensure all S3 streams are readable.
This is something I've asked @alxarch to include. 
We have seen the following cases in the past (the reason for this one: https://github.com/panther-labs/panther-enterprise/issues/1454 )
1. User will onboard a new log source
2. User will not give the appropriate KMS permissions to the role assumed by Panther
3. When we try to read the data, we will get "AccessDeniedExceptions". 

The code before this PR, we would read the first chunk of data *inside* the `generateDataStreamsFunc`. So KMS/Access errors would cause line 127 to return an error. We would skip this error and continue with the proper execution. This means that permissions issue for a single S3 object wouldn't fail the batch. 

This PR modifies the way the stream works so that we try to read data at a later stage, when we start to parse the first line. 
This can have the side effect that we detect errors like AccessDenied at a later stage - and right now the way the log processor works, such errors will cause the whole batch to fail. 

This extra code added by @alxarch was to make sure we trigger the read operation earlier (like we were doing until now) to make sure we don't lose the ability to detect issues "early" and react on them.

2020-12-03 07:49 UTC, alxarch commented on internal/log_analysis/log_processor/s3pipe/s3pipe.go
> +
We don't. This is intentional. We want an independent copy of the struct so we can 'normalize' the fields with our buffer provider without affecting the original.

2020-12-03 07:52 UTC, kostaspap commented on internal/log_analysis/log_processor/s3pipe/s3pipe.go
> +
Oh. Can you put a BIG warning sign there? This is a bug waiting to happen

2020-12-03 07:55 UTC, alxarch commented on internal/log_analysis/log_processor/s3pipe/s3pipe.go
> +
Added comment explaining

2020-12-03 07:55 UTC, kostaspap commented on internal/log_analysis/log_processor/s3pipe/s3pipe.go
> +
Or even make it more explicit by using a new New() method or something that initializes the struct accordingly.

2020-12-03 07:58 UTC, alxarch commented on internal/log_analysis/log_processor/s3pipe/s3pipe.go
> +	}
What we are trying to achieve here is to not block forever on the read side of things. 
`peek` is a good name since it 'peeks into' the first chunk. In our particular case, it also closes the `ready` channel once done. All reads will continue only after `ready` is closed. One of the shortcomings of Golang's channels is that you can only close a channel once. So we *have* to call `peek` for the read to proceed, even if it returns an error to the one reading.

2020-12-03 08:01 UTC, alxarch commented on internal/log_analysis/log_processor/processor/logstream/linestream.go
> +	if err := s.err; err != nil {
fixed

2020-12-03 08:02 UTC, alxarch commented on internal/log_analysis/log_processor/processor/logstream/linestream.go
> +		// Check for valid UTF8 stream on first read.
Added longer explanation

2020-12-03 08:06 UTC, alxarch commented on internal/log_analysis/log_processor/processor/stream.go
> +func readZero(r io.Reader) error {
Glad you asked :)
`readZero` is used to kick off the S3 download and get the first chunk *before* reading data from the reader. What this enables us to do, is to detect if the stream is gzipped and 'transparently' swap the underlying `io.Reader` from  `*io.PipeReader`  to `*gzip.Reader`. This way, we can handle gzip streams transparently without having to do unnecessary buffering. (We already have quite a lot of buffering being done to download in chunks)

2020-12-03 08:12 UTC, alxarch commented on internal/log_analysis/log_processor/processor/stream.go
> +					// This is a temporary workaround to ensure all S3 streams are readable.
Also this was not put inside 'generateDataStreamsFunc' so that once we have proper SQS messsage tracking, we can easily remove it here and have the per-message processing happen in a separate goroutine.

2020-12-03 08:55 UTC, kostaspap commented on internal/log_analysis/log_processor/s3pipe/s3pipe.go
> +	}
Ok, I have to say looking at the code more closely I was able to identify the issue you are trying to address here.

I have to say it is a bit challenging to follow the code logic and identify this issue. This edge case is really... hidden.

It seems that a lot of the challenges here are because we try to avoid by all means reading any data when `Download` is called. But do we really need to do this? 
1. The way the code is written right now, we anyway read the first chunks serially
2. We can easily parallelize the code in the future to read them in parallel, we just have to make sure that the `Download` function is invoked by different go routines. 

I am worried that we are sacrificing some "ease of maintenance" here to get an edge which we would achieve in a different way. 

Maybe best to chat offline?

2020-12-03 09:55 UTC, alxarch commented on internal/log_analysis/log_processor/s3pipe/s3pipe.go
> +
Added comment explaining the use of a non-pointer receiver. It is common to use the 'pass-by-copy' for structs that will need to be modified for this particular method.

2020-12-03 09:59 UTC, alxarch commented on internal/log_analysis/log_processor/s3pipe/s3pipe.go
> +	}
Wiring up the chunked reader is a separate concern from actually reading from it. Even if we decide to read files in parallel, we might want to restrict the number of concurrent readers. The separation of initialization and execution is crucial for controlling parallel code. The edge cases are adressed in this PR and I don't think 'dumping it down' will help when we reach the point where concurrency is handled. Sometimes things are complex by nature. I was recently looking for a good solution to the 'singleflight' problem

2020-12-03 10:06 UTC, kostaspap commented on internal/log_analysis/log_processor/s3pipe/s3pipe.go
> +	}
> Sometimes things are complex by nature 

We can definitely choose which path to take. I am not sure I understand the reason why we cannot handle this in a performant way. Or what are the differences in performance between the options. 

I definitely know though that if we happen to hit an edge case here, it will be tough to fix it. It is already tough to read and understand it. We are the maintainers of the code, so understanding any piece of it is important, hiding it behind an interface is going to make is easier to use but not easier to debug.

2020-12-03 10:10 UTC, alxarch commented on internal/log_analysis/log_processor/s3pipe/s3pipe.go
> +	}
The separation is important so that you can control which goroutine will be doing the blocking I/O stuff. 
You want to 'prepare' the work in a 'main' goroutine and then fan out the blocking stuff to 'worker' goroutines.

2020-12-03 16:40 UTC, alxarch commented on internal/log_analysis/log_processor/processor/logstream/linestream.go
> +	line, isPrefix, err := s.r.ReadLine()
Commented the function heavily, since people are not familiar with `bufio.Reader.ReadLine`

2020-12-03 17:27 UTC, kostaspap commented on internal/log_analysis/log_processor/processor/logstream/linestream.go
> +		if !isValidUTF8(line, isPrefix) {
is it possible that the `line` here has size < utf8.UTFMax?

2020-12-03 17:28 UTC, kostaspap commented on internal/log_analysis/log_processor/processor/logstream/linestream.go
> +			break
return false?

2020-12-03 17:39 UTC, kostaspap approved these changes
LGTM

2020-12-03 17:39 UTC, kostaspap commented on internal/log_analysis/log_processor/processor/logstream/linestream.go
> +	line, isPrefix, err := s.r.ReadLine()
Is it possible to add a unit test that tests the scenarios where `isPrefix` is true? I am not sure we have any testing for this part of the code.

2020-12-08 13:47 UTC, merged