fix: references either stable or pre-release version templates
panther-labs/panther pull request #2158
Opened 2020-11-30 18:44 UTC by s0l0ist

## Background

Fixes an issue when downloading CF templates, we only reference the stable version string. This PR changes the FE constants so we can always download CF templates for internal development/pre-release and production/stable releases.

## Changes

- Use regex to extract the proper version strings

## Testing

- Manually/Visually

2020-11-30 19:00 UTC, austinbyers commented on web/src/constants.ts
> +export const STABLE_PANTHER_VERSION = PANTHER_VERSION_MATCH[1]; // e.g. "v1.13.0"
So there are now 3 exported version strings:

* `pantherConfig.PANTHER_VERSION`
* `FULL_PANTHER_VERSION`
* `STABLE_PANTHER_VERSION`

Looking at those 3 variable names, I would have no idea what the difference is between them.

-----

I would say let's rename like this:

* `STABLE_PANTHER_VERSION` => `PANTHER_PATCH_VERSION` ("v1.13.0")
* `FULL_PANTHER_VERSION` => `QUALIFIED_PANTHER_PATCH_VERSION` ("v1.13.0-RC")

2020-11-30 19:01 UTC, austinbyers commented on web/src/constants.ts
> +export const STABLE_PANTHER_VERSION = PANTHER_VERSION_MATCH[1]; // e.g. "v1.13.0"
This is following the "major/minor/patch" terminology from semver

2020-12-01 11:27 UTC, 3nvi approved these changes
Approved, but just a minor user-debugging concern. Other than that, it looks good

2020-12-01 11:27 UTC, 3nvi commented on web/src/constants.ts
> +export const QUALIFIED_PANTHER_PATCH_VERSION = PANTHER_VERSION_MATCH[0]; // e.g. could be "v1.13.0" or "v1.13.0-RC"
if we have multiple RCs, all users will report that they are using `v1.13.0-RC` although in reality therre may be multiple different RCs.

Is that something that we are ok with?

2020-12-01 18:56 UTC, austinbyers commented on web/src/constants.ts
> +export const QUALIFIED_PANTHER_PATCH_VERSION = PANTHER_VERSION_MATCH[0]; // e.g. could be "v1.13.0" or "v1.13.0-RC"
We will still show the commit sha to distinguish this case

2020-12-01 18:57 UTC, austinbyers requested changes
I thought I had commented somewhere in this PR, but I guess not:

This change doesn't work for the master template, I'm going to take over the PR (or replace it with another one) that fixes all of the versioning problems more holistically

2020-12-03 14:36 UTC, alexmylonas commented
@austinbyers Keep in mind the issue #2149 which i am not sure this versioning fix will resolve!

2020-12-03 19:50 UTC, austinbyers commented
> @austinbyers Keep in mind the issue #2149 which i am not sure this versioning fix will resolve!

All of the S3 template issues we've seen are the same: we published `v1.14.0-RC` and the app was expecting `v1.14.0`.  The fix, which we've done, is to just re-publish the S3 templates with the latter version. The problem only exists for base versions with a dash in them.

This PR, as written, is a quick hack to fix this more permanently by parsing out the full base version with a regex. So yes, the changes would address the issue you linked. However, this fix is fragile and doesn't work for master-stack deployments.

I am working on a more holistic fix (which will supersede this PR) which will pass the base version everywhere as a separate variable so we don't have to use string parsing to pull it out

2020-12-05 00:54 UTC, closed without merging