OS Custom logs
panther-labs/panther pull request #2185
Opened 2020-12-03 13:13 UTC by vorillaz

## Background

Moving custom logs from Enterprise to OS.

## Changes
- Move all files from custom logs PR from [enterprise](https://github.com/panther-labs/panther-enterprise/commit/848039fa639ef9d1610ad9763a0e24c5f86d06f7) 
- Fix schema dependencies.
- Fix package.lock dependencies
- Remove RBAC checks and enterprise-specific  changes

2020-12-03 13:16 UTC, 3nvi commented on api/graphql/schema.graphql
> +}
@vorillaz This is the issue I think

2020-12-07 10:45 UTC, alexmylonas requested changes
Solid work Theo! I have left a couple of comments and i also notice license from enterprise is remnant on most cp files

2020-12-07 10:45 UTC, alexmylonas commented on api/graphql/schema.graphql
> +}
`AddCustomLogOutput` & `GetCustomLogOutput` are identical consider changing them to `CustomLogOutput`

2020-12-07 10:45 UTC, alexmylonas commented on web/src/constants.ts
> +export const CUSTOM_LOG_TYPES_DOC_URL = `${PANTHER_DOCS_LINK}/enterprise/custom-log-types`;
This link wont (or shouldnt) be valid, neither here nor enterprise

2020-12-07 10:45 UTC, alexmylonas commented on web/src/helpers/analytics.ts
> +interface AddLogSourceError {
This should be a duplicated interface no?

2020-12-07 10:45 UTC, alexmylonas commented on web/src/helpers/analytics.ts
> +interface DeleteCustomLogError {
optional: 
```suggestion
interface CustomLogError {
  event: TrackErrorEnum.FailedToAddCustomLog | TrackErrorEnum.FailedToDeleteCustomLog;
  src: SrcEnum.CustomLogs;
}

interface DeleteCustomLogError extends CustomLogError {
  event: TrackErrorEnum.FailedToDeleteCustomLog;
}
interface AddCustomLogError extends CustomLogError {
  event: TrackErrorEnum. FailedToAddCustomLog;
}
```

2020-12-07 10:45 UTC, alexmylonas commented on web/src/hooks/useFormSessionRestoration.tsx
> +  React.useEffect(syncStorage, [dirty, values]);
Is this change safe for every usage?

2020-12-07 10:45 UTC, alexmylonas commented on web/src/pages/CreateCustomLog/index.tsx
> + */
Duplicate license

2020-12-07 10:45 UTC, alexmylonas commented on web/src/pages/CustomLogDetails/CustomLogDetails.test.tsx
> + */
Duplicate license

2020-12-07 10:45 UTC, alexmylonas commented on web/src/pages/CustomLogDetails/index.tsx
> + */
Duplicate license

2020-12-07 13:19 UTC, 3nvi reviewed
Overall really good @vorillaz . Some small bugfixes here and there, but nothing major 😃

2020-12-07 13:19 UTC, 3nvi commented on api/graphql/schema.graphql
> +}
I'd actually prefer to keep them as is, since I wouldn't wanna create another set of changes on Enterprise

2020-12-07 13:19 UTC, 3nvi commented on web/src/constants.ts
> +export const CUSTOM_LOG_TYPES_DOC_URL = `${PANTHER_DOCS_LINK}/enterprise/custom-log-types`;
In 1.13, this link is still valid, but I think it will change for sure. Perhaps this should be a change in a separate PR, since the docs link will need to change in enterprise as well (i.e. we'd want to sync this change)

2020-12-07 13:19 UTC, 3nvi commented on web/src/hooks/useFormSessionRestoration.tsx
> +  React.useEffect(syncStorage, [dirty, values]);
Yeah I think I was the one to write it. The `isSubmitting` presence was creating a bug there, where a failed submission would be wrongly "cached"

2020-12-07 13:19 UTC, 3nvi commented on web/src/pages/CustomLogDetails/CustomLogDetails.test.tsx
> + */
This is present  in multiple files so @vorillaz try to clean them all 😃

2020-12-07 13:19 UTC, 3nvi commented on web/src/urls.ts
> +    customLogs: {
this snippet is duplicated below

2020-12-10 19:09 UTC, vorillaz commented on web/src/pages/CustomLogDetails/CustomLogDetails.test.tsx
> + */
Hey, thanks both of you. I took the chance and cleared tons of duplicate entries with enterprise licencing. So you can skip an entire commit during the review [4abac1ea2ff518652dd57334472d78faf7316b53](https://github.com/panther-labs/panther/commit/4abac1ea2ff518652dd57334472d78faf7316b53)

2020-12-10 19:10 UTC, vorillaz commented on api/graphql/schema.graphql
> +}
This one is not gonna change against the enterprise tho, I guess it will only affect future conflicts and as Aggelos suggested I wanted to avoid collisions 💥

2020-12-11 09:18 UTC, 3nvi approved these changes
LGTM 🎉

2020-12-11 09:18 UTC, 3nvi commented on api/graphql/schema.graphql
> +}
Agreed. We can proceed as is in order to keep the flow of our work going

2020-12-11 09:18 UTC, 3nvi commented on web/src/constants.ts
> +export const CUSTOM_LOG_TYPES_DOC_URL = `${PANTHER_DOCS_LINK}/enterprise/custom-log-types`;
We agreed to leave it as is and let @mattthetraveler move it during cleanup

2020-12-11 09:38 UTC, alexmylonas approved these changes
LGTM!

2020-12-11 09:38 UTC, alexmylonas commented on web/src/helpers/analytics.ts
> +  CustomLogDetails = 'Custom Log Details Screen',
optional: we should check first for the `List Custom Logs`

2020-12-14 12:32 UTC, merged