Fix version bugs
panther-labs/panther pull request #2192
Opened 2020-12-04 02:28 UTC by austinbyers

## Background

#1785 created a shared VERSION file in an attempt to consolidate all version references to the same source of truth. However, the final version string has 4 parts: "(VERSION file)-(branch)-(commit)-(dirty)". This meant services which only needed part of the version had to do string splitting to get just the base version at the beginning. The problem is that when there is a "-" in the VERSION, e.g. "v1.14.0-RC", the string splitting logic no longer works. #2158 attempted to fix this parsing with regexes, but that's clearly just a hack to work around an underlying problem that needs to be addressed.

The main bug affecting the last two releases is that the S3 aux templates were not loading correctly during source onboarding (#2149, https://github.com/panther-labs/panther-enterprise/issues/1594, https://github.com/panther-labs/panther-enterprise/issues/1590):
* The `source-api` was using the CUSTOM_RESOURCE_VERSION instead of the true panther version as the basis of the template URL.
* The frontend was doing a string split to pull out the base version, which discarded the `-RC` suffix we use for release testing
* Worse still, `mage deploy` and `mage master:deploy` were passing the repo version differently and almost led to a completely broken 1.13 release publish

----
Now, instead of passing a single string which has to be split later, we pass the component version pieces and only combine them at the very end when they are needed. I've also simplified the parts: we only care about the VERSION base ("1.14.0") and the commit sha ("12345678").

Those two parts are now passed directly to every service that needs a version. There is no "v" prefix anymore; we add that when the version is actually used (e.g. to generate a template URL)

Closes: #2158 (this is a more holistic solution)

## Changes

- `source-api` is passed the contents of the VERSION file, not the CustomResourceVersion. The VERSION file does not have a "v" prefix, so it has been added when the source-api generates the URL in the Go code.
- "PantherVersion" and "PantherCommit" parameters in CloudFormation now have regex validation to ensure they always have the correct format. PantherVersion looks like "1.X.Y" or "1.X.Y-RC" (no "v" prefix) and PantherCommit is the 8-digit short commit tag
- The default CustomResourceVersion is now the same as the version string shown to the user in the general settings page: VERSION-COMMIT, e.g. "1.14.0-RC (12345678)"
    - This way, every deployment will re-trigger the custom resources if there are new commits. This is helpful during release testing, since we may republish many different `-RC` variants and need to re-apply the changes
    - The same custom resource version is used for both deployment methods
- The commit and the semantic version are passed separately to the web stack. The "v" prefix has been dropped when showing it to the user
- We really only care about the branch and the dirty repo state when we're publishing a release. So those have been removed from the full version string and are instead checked directly during `mage master:publish`
- Fix environment when running web server locally (`npm start`)

### Versions Before
General Settings
![Screen Shot 2020-12-03 at 5 41 41 PM](https://user-images.githubusercontent.com/3608925/101112623-98ccfb80-3592-11eb-907c-da8915982b35.png)

Profile Popup
![Screen Shot 2020-12-03 at 5 41 53 PM](https://user-images.githubusercontent.com/3608925/101112624-99659200-3592-11eb-9094-2ff464fff48d.png)

(from our 1.14 release environment)

### Versions After

<img width="156" alt="Screen Shot 2020-12-03 at 6 07 46 PM" src="https://user-images.githubusercontent.com/3608925/101112652-a5e9ea80-3592-11eb-9bf9-4ed815b15ef9.png">
<img width="147" alt="Screen Shot 2020-12-03 at 6 07 32 PM" src="https://user-images.githubusercontent.com/3608925/101112650-a5515400-3592-11eb-932c-39a15effa0fe.png">

Note the simplified versions, and that the profile now shows the full base version (with the -RC suffix)

## Testing

- `mage deploy` and `npm start`
    - verified the version in the profile popup, the general settings page, and the CloudFormation tags
    - verified log analysis and cloud security source onboarding can generate templates correctly (and are loading the correct template versions)
- Ran all the same tests again for `mage master:deploy`

2020-12-04 02:30 UTC, austinbyers commented
This is too big a change for me to be comfortable syncing to the release. We've already tested 1.14.0-RC with the hardcoded version fixes, let's just leave it that way so we don't have to re-test

2020-12-04 02:49 UTC, austinbyers commented on tools/mage/util/version.go
> -func LatestPublishedVersion() (string, error) {
This is a chunk of code that has never been used; it was originally intended for end-to-end release testing

2020-12-04 08:45 UTC, 3nvi approved these changes
Amazing work @austinbyers . That was much needed since regex parsing was indeed fragile. I'm always amazed how you're able to make perfect FE changes; you've even updated the snapshots. Props 🎉 

Approving the web changes

2020-12-04 12:17 UTC, rleighton approved these changes
LGTM. Nice cleanup. Splitting the commit and the version makes this much more maintainable.

2020-12-04 12:58 UTC, alexmylonas commented
Confirmed functionality locally!

2020-12-04 17:17 UTC, nhakmiller approved these changes

2020-12-04 17:17 UTC, nhakmiller commented on tools/mage/util/version.go
> -func LatestPublishedVersion() (string, error) {
The Destroyer of Code living up to his epithet.

2020-12-04 17:36 UTC, austinbyers commented on tools/mage/util/version.go
> -func LatestPublishedVersion() (string, error) {
It's a conspiracy: I just add junk code so I can look good for removing it later

2020-12-04 17:37 UTC, austinbyers commented
> This is too big a change for me to be comfortable syncing to the release. We've already tested 1.14.0-RC with the hardcoded version fixes, let's just leave it that way so we don't have to re-test

On second thought, the published template itself is subject to a similar version problem (`mage master:publish` will publish v1.14.0 instead of v1.14.0-RC), so we are going to sync this to the release after all. It has already been tested extensively, and we will continue to test it as we upgrade accounts.

I'm more worried about lingering version bugs than the effects of this change

2020-12-04 17:53 UTC, s0l0ist requested changes
Minor changes, overall really good! This will help a lot!

2020-12-04 17:53 UTC, s0l0ist commented on deployments/core.yml
> +    AllowedPattern: '^1\.\d+\.\d+(-.+)?$'
I don't like this hard match for `1`, lets just make this another `\d+`

2020-12-04 17:53 UTC, s0l0ist commented on deployments/web_server.yml
> +    AllowedPattern: '^1\.\d+\.\d+(-.+)?$'
same as above here

2020-12-04 17:53 UTC, s0l0ist commented on tools/mage/deploy/deploy.go
> +	return fmt.Sprintf("%s (%s)", util.Semver(), util.CommitSha())
nice

2020-12-04 17:53 UTC, s0l0ist commented on tools/mage/master/publish.go
> +	if !strings.HasPrefix(branch, "release-1.") {
Can we make this less about a major version `1`? It will eventually break... Maybe some other regex match?

2020-12-04 17:53 UTC, s0l0ist commented on web/src/components/Navigation/ProfileIcon/ProfileIcon.tsx
> +                Panther&nbsp;<b>{pantherConfig.PANTHER_VERSION}</b>
We should not pull from `Source/config` directly. Instead, we should make a const inside `Source/constants` so we have a single source of truth.

2020-12-04 17:53 UTC, s0l0ist commented on web/src/components/wizards/ComplianceSourceWizard/StackDeploymentPanel/StackDeployment.tsx
> +    `?templateURL=https://s3-us-west-2.amazonaws.com/panther-public-cloudformation-templates/panther-cloudsec-iam/v${pantherConfig.PANTHER_VERSION}/template.yml` +
Pull from `Source/constants`

2020-12-04 17:53 UTC, s0l0ist commented on web/src/components/wizards/S3LogSourceWizard/StackDeploymentPanel/StackDeployment.tsx
> +    `?templateURL=https://panther-public-cloudformation-templates.s3-us-west-2.amazonaws.com/panther-log-analysis-iam/v${pantherConfig.PANTHER_VERSION}/template.yml` +
Pull from `Source/constants`

2020-12-04 17:53 UTC, s0l0ist commented on web/src/helpers/__tests__/analytics.test.tsx
> +import { pantherConfig } from 'Source/config';
Pull from `Source/constants` and for the other changes in this file

2020-12-04 17:53 UTC, s0l0ist commented on web/src/helpers/analytics.ts
> +import { pantherConfig } from 'Source/config';
Pull from `Source/constants`

2020-12-04 18:00 UTC, s0l0ist approved these changes

2020-12-04 19:01 UTC, austinbyers commented on deployments/core.yml
> +    AllowedPattern: '^1\.\d+\.\d+(-.+)?$'
Sure

2020-12-04 19:02 UTC, austinbyers commented on tools/mage/master/publish.go
> +	if !strings.HasPrefix(branch, "release-1.") {
I'll just limit to a prefix of `release-`

2020-12-04 19:03 UTC, austinbyers commented on web/src/components/Navigation/ProfileIcon/ProfileIcon.tsx
> +                Panther&nbsp;<b>{pantherConfig.PANTHER_VERSION}</b>
I considered that, but:

* We already use `pantherConfig.AWS_REGION` and `pantherConfig.AWS_ACCOUNT_ID` throughout the web source
* It seems redundant to `export const PANTHER_VERSION = pantherConfig.PANTHER_VERSION` in the constants file

I'll leave this as is for now since @3nvi approved it as-is and it's consistent with the existent usage, but I'm happy to change this later if we want a different style

2020-12-05 00:54 UTC, austinbyers commented
Deployed again, found a rare bug where the commit was being interpreted by CloudFormation as scientific notation 😅 

Bug fixed, verified version strings are still correct

2020-12-05 00:54 UTC, merged