WIP
panther-labs/panther pull request #2194
Opened 2020-12-04 09:47 UTC by kostaspap

## Background

Why are you making this change? Please provide a reference to any related issues and PRs

## Changes

- List your changes here in more detail

## Testing

- How did you test your change?

2020-12-08 10:33 UTC, giorgosp approved these changes
Nice work! Left some comments

2020-12-08 10:33 UTC, giorgosp commented on cmd/devtools/customlogs/customlogs/infer.go
> +func inferFromFile(logger *zap.SugaredLogger, file string) (logschema.Schema, error) {
Is the logger really needed as a param to every function? Adds a bit of noise

2020-12-08 10:33 UTC, giorgosp commented on cmd/devtools/customlogs/customlogs/infer.go
> +	scanner := bufio.NewScanner(fd)
Maybe use `bufio.Reader` that has an auto-growing buffer? Scanner will error if a log line is too big

2020-12-08 10:33 UTC, giorgosp commented on cmd/devtools/customlogs/customlogs/infer.go
> +		logger.Fatal("failed to read input file", zap.Error(err))
Since this function has an error return argument, why not return the error and let it be handled in one place higher in the stack?

2020-12-08 10:33 UTC, giorgosp commented on cmd/devtools/customlogs/customlogs/infer.go
> +	// sorts the fields by name. Useful so that re-runs of the same tool will generate the same schema
nice

2020-12-08 10:33 UTC, giorgosp commented on cmd/devtools/customlogs/customlogs/infer.go
> +		// Just skip it.
Perhaps it's useful to map it as an uknown object? (Not sure if we support this). So that the existence of this empty object is depicted in the schema, although we don't know its fields yet.

2020-12-08 10:33 UTC, giorgosp commented on cmd/devtools/customlogs/customlogs/infer.go
> +		return logschema.TypeBigInt, true
I think we should describe numbers as float64 for a more accurate schema. Even if the field can be parsed as integer in 1 log line, we can't be sure it will be int for all similar events. float64 is also the default decoding for json.

2020-12-08 10:46 UTC, kostaspap commented on cmd/devtools/customlogs/customlogs/infer.go
> +	scanner := bufio.NewScanner(fd)
Sure. Updating

2020-12-08 10:48 UTC, kostaspap commented on cmd/devtools/customlogs/customlogs/infer.go
> +		logger.Fatal("failed to read input file", zap.Error(err))
Ah yes. I missed that one. Removed.

2020-12-08 10:48 UTC, kostaspap commented on cmd/devtools/customlogs/customlogs/infer.go
> +func inferFromFile(logger *zap.SugaredLogger, file string) (logschema.Schema, error) {
Actually it was not needed here, removed. 
It is now only present at the top-level function `func Infer(logger *zap.SugaredLogger, opts *InferOpts)`

2020-12-08 10:49 UTC, kostaspap commented on cmd/devtools/customlogs/customlogs/infer.go
> +		// Just skip it.
That's actually not possible... a field of type `object` requires some `fields` to be present. 
I had it like that initially but ran into the issue. The unit test tests for this specific case as well.

2020-12-08 11:07 UTC, giorgosp commented on cmd/devtools/customlogs/customlogs/infer.go
> +func inferFromFile(logger *zap.SugaredLogger, file string) (logschema.Schema, error) {
It is not needed there too if we only use a logger initialized in main.

2020-12-08 11:09 UTC, giorgosp commented on cmd/devtools/customlogs/customlogs/infer.go
> +			if err == io.EOF {
line might still be populated even if EOF is returned (see ReadString docs)

2020-12-08 11:48 UTC, kostaspap commented on cmd/devtools/customlogs/customlogs/infer.go
> +		return logschema.TypeBigInt, true
I have to say I am not a huge fan of this one... usually in the logs, if the field is of "float" type, even if the decimal part is 0, they will display it e.g. `1.0`. So it is easy to understand the type. The majority of the number fields tend to be integers as well, floats are usually just a small set e.g. duration, scores etc

2020-12-08 11:56 UTC, kostaspap commented on cmd/devtools/customlogs/customlogs/infer.go
> +			if err == io.EOF {
Good catch! Updated

2020-12-08 12:03 UTC, kostaspap commented on cmd/devtools/customlogs/customlogs/infer.go
> +func inferFromFile(logger *zap.SugaredLogger, file string) (logschema.Schema, error) {
The `Infer` function needs to log messages though, so it needs a logger. The other option would be to make it global var and access it from there, I am thinking passing it to the function is more clear.

2020-12-08 12:07 UTC, giorgosp commented on cmd/devtools/customlogs/customlogs/infer.go
> +func inferFromFile(logger *zap.SugaredLogger, file string) (logschema.Schema, error) {
I think a global var is fine except if we want different logging config/behavior in different circumstances (like tests etc). This doesn't seem the case here so I'd just make it a global.

2020-12-08 12:16 UTC, giorgosp commented on cmd/devtools/customlogs/customlogs/infer.go
> +		return logschema.TypeBigInt, true
Not a hard opinion, it would just be safer to use a float type. Users have the incentive to reduce their costs too so I would expect they review and optimise the types.

2020-12-09 16:24 UTC, alxarch requested changes

2020-12-09 16:24 UTC, alxarch commented on cmd/devtools/customlogs/customlogs/infer.go
> +		if _, ok := leftMap[schema.Name]; ok {
This could only happen in case the input JSON is invalid? This seems like something to be extracted into a separate function.

2020-12-09 16:24 UTC, alxarch commented on cmd/devtools/customlogs/customlogs/infer.go
> +func mergeArrayElementSchema(left, right *logschema.ValueSchema) (*logschema.ValueSchema, error) {
This seems like an error in the flow of recursion. There shouldn't be a specific function for array elements.

My suggestion is that we have an `mergeValues(left, right *logschema.ValueSchema) (*logschema.ValueSchema, error)` *entry point*.
It should have a single `switch` on type and handle the cases from there. 
Field values and array elements should be re-entering into `mergeValues`. 
Otherwise, we will end up with duplicate code and bugs will be hard to control in various cases such as in the glue schema case.

For the 'root' object, we can be wrapping a `[]logschema.FieldSchema` into a 'fake'  `logschema.ValueSchema` of type `object`. 

Another thing to note is that we should be passing a `path []string` argument into the recursive functions so that errros can be helpful.

2020-12-09 16:24 UTC, alxarch commented on cmd/devtools/customlogs/customlogs/infer.go
> +		case logschema.TypeObject:
This switch is duplicated here and in mergeFieldSchema. This is the problem I am talking about above.

2020-12-09 17:58 UTC, alxarch commented on cmd/devtools/customlogs/customlogs/infer.go
> +func mergeArrayElementSchema(left, right *logschema.ValueSchema) (*logschema.ValueSchema, error) {
A gist following a 'structured recursion' flow. The important part is how functions call each other so that we only have one type switch for infer and one for merge.
https://gist.github.com/alxarch/b3f30c68193f6bda1126ed89fb385f72

2020-12-09 17:59 UTC, alxarch commented on cmd/devtools/customlogs/customlogs/infer.go
> +func mergeArrayElementSchema(left, right *logschema.ValueSchema) (*logschema.ValueSchema, error) {
I would suggest to add this as an exported function in `logschema` so it can be reused.

2020-12-10 10:54 UTC, kostaspap commented on cmd/devtools/customlogs/customlogs/infer.go
> +	return &logschema.ValueSchema{
That's a good idea, but we can add it later. This is the first iteration of the CLI tool, we can make further improvements later.

2020-12-11 13:14 UTC, kostaspap commented on cmd/devtools/customlogs/customlogs/infer.go
> +func mergeArrayElementSchema(left, right *logschema.ValueSchema) (*logschema.ValueSchema, error) {
Updated.

2020-12-11 13:15 UTC, kostaspap commented on cmd/devtools/customlogs/customlogs/infer.go
> +		case logschema.TypeObject:
Updated.

2020-12-11 13:15 UTC, kostaspap commented on cmd/devtools/customlogs/customlogs/infer.go
> +		if _, ok := leftMap[schema.Name]; ok {
Removed.

2020-12-11 13:15 UTC, kostaspap commented on cmd/devtools/customlogs/customlogs/infer.go
> +		valueSchema, ok := inferValueSchema(array[0])
Fixed

2020-12-11 13:41 UTC, alxarch approved these changes

2020-12-11 13:41 UTC, alxarch commented on cmd/devtools/customlogs/main.go
> +			Schema: flag.String("s", "", "File file"),
Schema file?

2020-12-11 13:41 UTC, alxarch commented on cmd/devtools/customlogs/customlogs/infer.go
> +func validateSchema(valueSchema *logschema.ValueSchema, file string) error {
I don't see any point in re-reading the file through. Parsing won't fail if the schema was infered correctly. It's entirely possible that the fields end up as just `json` types and we are just verifying that jsoniter works. My understanding of the process is that it is a two step thing. First create the schema, and then to test the schema, the user needs to see the results to be able to tell if the schema is fine.

2020-12-11 13:44 UTC, kostaspap commented on cmd/devtools/customlogs/main.go
> +			Schema: flag.String("s", "", "File file"),
ah! yes. Renaming gone wrong.

2020-12-11 13:54 UTC, merged