Filter rules by creator
panther-labs/panther pull request #2218
Opened 2020-12-07 19:25 UTC by AlexPanther

## Background

Closes: https://github.com/panther-labs/panther/issues/1078

## Changes

- Add `createdBy`, `lastModifiedBy`, and `initialSet` to policy+rules schema
- Add/update test
- Add logic to filter based on if a rule was created by Panther

## Testing

- This PR does not include frontend changes, so integration tests were used to test

2020-12-07 19:27 UTC, AlexPanther commented on internal/core/analysis_api/main/integration_test.go
>  			TotalItems: 1,
considering there should be no user with ID "nil", `TotalItems` should be 0?

2020-12-07 21:39 UTC, austinbyers requested changes
Good start! Missing the `createdBy` and `lastModifiedBy` filter implementations though

2020-12-07 21:39 UTC, austinbyers commented on internal/core/analysis_api/handlers/list.go
> +	tags []string,
Nit: if these are on separate lines, but the type twice so it's easier to read:

```suggestion
	types []string,
	tags []string,
```

2020-12-07 21:39 UTC, austinbyers commented on internal/core/analysis_api/handlers/list.go
> +				expression.Value("00000000-0000-4000-8000-000000000000"))
I thought there was already a constant defined somewhere in the `analysis-api` with this value, but I can't find it, so maybe not.

Let's add a constant for this (e.g. in `clients.go`):

```go
const systemUserID = "00000000-0000-4000-8000-000000000000"
```

Then we can use it here as

```
expression.Value(systemUserID)
```

2020-12-07 21:39 UTC, austinbyers commented on internal/core/analysis_api/handlers/list.go
> +		if !*initialSet {
This should be an `else` clause, you don't need to explicitly check if its value is false because you already know it isn't true.

```suggestion
		} else {
```

2020-12-07 21:39 UTC, austinbyers commented on internal/core/analysis_api/handlers/list_policies.go
> +		input.InitialSet)
What about filtering by the user? `createdBy` or `lastModifiedBy`?

----

When we add those, there will be too many arguments to this function, in my opinion. You could make a separate struct for these:

```go
// Filters common to ListPolicies and ListRules
type pythonFilters struct {
    CreatedBy string
    Enabled *bool
    InitialSet *bool
    LastModifiedBy string
    NameContains string
    Severity string
    ResourceTypes []string
    Tags []string
}

func pythonListFilters(input *pythonFilters) { ... }
```

2020-12-08 00:06 UTC, AlexPanther commented on internal/core/analysis_api/handlers/list_policies.go
> +	}
I think there may be a better way to do this through the use of the spread operator?

2020-12-08 00:49 UTC, austinbyers commented on internal/core/analysis_api/handlers/list_policies.go
> +	}
You mean the variadic operator? `myFunc(...string)`. That will expand an array into multiple function arguments, but I don't see how that will help here.

What could have helped reduce the duplication is if we created a shared `ListInput` struct that was [embedded](https://golang.org/doc/effective_go.html#embedding) in the two input structs:

```go
type PythonCommon struct {
    // fields common to ListPolicies and ListRules
    Enabled *bool 
    NameContains string

   // etc
}

type ListPoliciesInput struct {
    PythonCommon
   
    // Other fields specific to policies
    Severity
    ComplianceStatus
}
```

But when I tried that during the gateway refactor, reviewers felt it was too confusing, so we reverted back to the separate models as you see them today. That does mean there is a bit of duplication to get from the input struct into the filter creation, but that's not a big deal. It's simple and efficient, even if a little awkward.

2020-12-08 19:51 UTC, austinbyers reviewed
I deployed, the existing list policies page still works fine, I was able to filter in the Lambda function, but the integration tests are failing for me:

```
--- FAIL: TestIntegrationAPI (4.42s)
    --- FAIL: TestIntegrationAPI/List (0.00s)
        --- FAIL: TestIntegrationAPI/List/ListFilteredNoUser (0.03s)
            integration_test.go:1761:
                	Error Trace:	integration_test.go:1761
                	Error:      	Not equal:
                	            	expected: models.ListPoliciesOutput{Paging:models.Paging{ThisPage:1, TotalPages:1, TotalItems:1}, Policies:[]models.Policy{models.Policy{AutoRemediationID:"fix-it", AutoRemediationParameters:map[string]string{"hello":"goodbye"}, Body:"# Panther is a Cloud-Native SIEM for the Modern Security Team.\n# Copyright (C) 2020 Panther Labs Inc\n#\n# This program is free software: you can redistribute it and/or modify\n# it under the terms of the GNU Affero General Public License as\n# published by the Free Software Foundation, either version 3 of the\n# License, or (at your option) any later version.\n#\n# This program is distributed in the hope that it will be useful,\n# but WITHOUT ANY WARRANTY; without even the implied warranty of\n# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n# GNU Affero General Public License for more details.\n#\n# You should have received a copy of the GNU Affero General Public License\n# along with this program.  If not, see <https://www.gnu.org/licenses/>.\n\n\ndef policy(resource):\n    return True\n", ComplianceStatus:"PASS", CreatedAt:time.Time{wall:0x2333a2d5, ext:63743053847, loc:(*time.Location)(nil)}, CreatedBy:"test-panther-user", Description:"Matches every resource", DisplayName:"AlwaysTrue", Enabled:true, ID:"Test:Policy:JSON", LastModified:time.Time{wall:0x2333a361, ext:63743053847, loc:(*time.Location)(nil)}, LastModifiedBy:"test-panther-user", OutputIDs:[]string{}, Reference:"", Reports:map[string][]string{"Test":[]string{"Value1", "Value2"}}, ResourceTypes:[]string{"AWS.S3.Bucket"}, Runbook:"", Severity:"MEDIUM", Suppressions:[]string{}, Tags:[]string{}, Tests:[]models.UnitTest{models.UnitTest{ExpectedResult:true, Name:"This will be True", Resource:"{\"Bucket\":\"empty\"}"}}, VersionID:"Leq6fpejVS4dC6bXxlg2.xjOsy6ABFha"}}}
                	            	actual  : models.ListPoliciesOutput{Paging:models.Paging{ThisPage:0, TotalPages:0, TotalItems:0}, Policies:[]models.Policy{}}

                	            	Diff:
                	            	--- Expected
                	            	+++ Actual
                	            	@@ -2,57 +2,7 @@
                	            	  Paging: (models.Paging) {
                	            	-  ThisPage: (int) 1,
                	            	-  TotalPages: (int) 1,
                	            	-  TotalItems: (int) 1
                	            	+  ThisPage: (int) 0,
                	            	+  TotalPages: (int) 0,
                	            	+  TotalItems: (int) 0
                	            	  },
                	            	- Policies: ([]models.Policy) (len=1) {
                	            	-  (models.Policy) {
                	            	-   AutoRemediationID: (string) (len=6) "fix-it",
                	            	-   AutoRemediationParameters: (map[string]string) (len=1) {
                	            	-    (string) (len=5) "hello": (string) (len=7) "goodbye"
                	            	-   },
                	            	-   Body: (string) (len=799) "# Panther is a Cloud-Native SIEM for the Modern Security Team.\n# Copyright (C) 2020 Panther Labs Inc\n#\n# This program is free software: you can redistribute it and/or modify\n# it under the terms of the GNU Affero General Public License as\n# published by the Free Software Foundation, either version 3 of the\n# License, or (at your option) any later version.\n#\n# This program is distributed in the hope that it will be useful,\n# but WITHOUT ANY WARRANTY; without even the implied warranty of\n# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n# GNU Affero General Public License for more details.\n#\n# You should have received a copy of the GNU Affero General Public License\n# along with this program.  If not, see <https://www.gnu.org/licenses/>.\n\n\ndef policy(resource):\n    return True\n",
                	            	-   ComplianceStatus: (models.ComplianceStatus) (len=4) "PASS",
                	            	-   CreatedAt: (time.Time) {
                	            	-    wall: (uint64) 590586581,
                	            	-    ext: (int64) 63743053847,
                	            	-    loc: (*time.Location)(<nil>)
                	            	-   },
                	            	-   CreatedBy: (string) (len=17) "test-panther-user",
                	            	-   Description: (string) (len=22) "Matches every resource",
                	            	-   DisplayName: (string) (len=10) "AlwaysTrue",
                	            	-   Enabled: (bool) true,
                	            	-   ID: (string) (len=16) "Test:Policy:JSON",
                	            	-   LastModified: (time.Time) {
                	            	-    wall: (uint64) 590586721,
                	            	-    ext: (int64) 63743053847,
                	            	-    loc: (*time.Location)(<nil>)
                	            	-   },
                	            	-   LastModifiedBy: (string) (len=17) "test-panther-user",
                	            	-   OutputIDs: ([]string) {
                	            	-   },
                	            	-   Reference: (string) "",
                	            	-   Reports: (map[string][]string) (len=1) {
                	            	-    (string) (len=4) "Test": ([]string) (len=2) {
                	            	-     (string) (len=6) "Value1",
                	            	-     (string) (len=6) "Value2"
                	            	-    }
                	            	-   },
                	            	-   ResourceTypes: ([]string) (len=1) {
                	            	-    (string) (len=13) "AWS.S3.Bucket"
                	            	-   },
                	            	-   Runbook: (string) "",
                	            	-   Severity: (models.Severity) (len=6) "MEDIUM",
                	            	-   Suppressions: ([]string) {
                	            	-   },
                	            	-   Tags: ([]string) {
                	            	-   },
                	            	-   Tests: ([]models.UnitTest) (len=1) {
                	            	-    (models.UnitTest) {
                	            	-     ExpectedResult: (bool) true,
                	            	-     Name: (string) (len=17) "This will be True",
                	            	-     Resource: (string) (len=18) "{\"Bucket\":\"empty\"}"
                	            	-    }
                	            	-   },
                	            	-   VersionID: (string) (len=32) "Leq6fpejVS4dC6bXxlg2.xjOsy6ABFha"
                	            	-  }
                	            	+ Policies: ([]models.Policy) {
                	            	  }
                	Test:       	TestIntegrationAPI/List/ListFilteredNoUser
        --- FAIL: TestIntegrationAPI/List/ListProjection (0.03s)
            integration_test.go:1895:
                	Error Trace:	integration_test.go:1895
                	Error:      	Not equal:
                	            	expected: models.ListPoliciesOutput{Paging:models.Paging{ThisPage:1, TotalPages:1, TotalItems:3}, Policies:[]models.Policy{models.Policy{AutoRemediationID:"", AutoRemediationParameters:map[string]string{}, Body:"", ComplianceStatus:"", CreatedAt:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, CreatedBy:"", Description:"", DisplayName:"", Enabled:false, ID:"AWS.CloudTrail.Log.Validation.Enabled", LastModified:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, LastModifiedBy:"", OutputIDs:[]string{}, Reference:"", Reports:map[string][]string{}, ResourceTypes:[]str [...]

2020-12-08 21:56 UTC, austinbyers approved these changes
Integration tests look good! One last note about a comment I missed, but after that LGTM! 🚀

2020-12-08 21:56 UTC, austinbyers commented on api/lambda/analysis/models/rules.go
> +	// Only include policies whose creator matches this user ID (which need not be a uuid)
Sorry I missed this earlier - let's make sure the comments in this file refer to "rules," not "policies"

2020-12-08 22:16 UTC, merged