Backend: Allow users to specify multiple s3 prefix->logtypes mappings per s3 log source
panther-labs/panther pull request #2232
Opened 2020-12-09 13:01 UTC by giorgosp

## Background

As part of improving the s3 onboarding process, we decided to allow users specify multiple s3 prefixes in the same source.
This is a step towards allowing users to define the s3 prefixes and logtypes for their onboarded s3 sources without having to update the stack, but there is still a very long way to go. See this [commit message](https://github.com/panther-labs/panther/commit/8304c08b32a53e810e550c8b906a9be7fd725dc8) for details.

## Changes

- Added a new field `S3PrefixLogTypes` that deprecates the `S3Prefix` and `LogTypes` fields for an s3 source
- Remove the s3 prefix filter from the log processing CFN template. 

## Testing

- unit + manual

2020-12-09 20:19 UTC, austinbyers reviewed
Looks like a nice improvement! I know there was some confusion on how best to test the new aux template in a live deployment. I'd recommend the following:

* Publish the new aux template manually in your own dev account (e.g. to your `bootstrap-source` bucket)
* Change the URL for loading this template in the `source-api` [here](https://github.com/panther-labs/panther/blob/master/internal/core/source_api/api/get_integration_template.go#L132-L145) and in the frontend [here](https://github.com/panther-labs/panther/blob/master/web/src/components/wizards/ComplianceSourceWizard/StackDeploymentPanel/StackDeployment.tsx#L48-L50) and [here](https://github.com/panther-labs/panther/blob/master/web/src/components/wizards/S3LogSourceWizard/StackDeploymentPanel/StackDeployment.tsx#L50-L52)

This will also help you understand exactly how the aux templates are referenced during onboarding, and lets you test without having to mess with the real public bucket where we publish these templates

2020-12-09 20:19 UTC, austinbyers commented on api/lambda/source/models/api.go
> +	S3PrefixLogTypes S3PrefixLogtypes `json:"s3PrefixLogTypes,omitempty"`
Changes to the Go input structs also need to be reflected in the GraphQL file (`api/graphql/schema.graphql`), or AppSync and the frontend will break, since the type is now different

2020-12-09 20:19 UTC, austinbyers commented on api/lambda/source/models/integration.go
> +	Logtypes []string `json:"logtypes,omitempty" validate:"omitempty,min=1"`
`validate:"omitempty,min=1"` makes no sense - you're saying the array is optional, but if it's defined, it has to have at least one element? That is essentially always true.

If you expect at least one log type, do `validate:"required,min=1"`. If log types are optional, then you could either remove the validation tag completely or validate the strings inside the slice: `validate:"omitempty,dive,required"`

2020-12-09 20:19 UTC, austinbyers commented on api/lambda/source/models/integration.go
> +	Logtypes []string `json:"logtypes,omitempty" validate:"omitempty,min=1"`
You name this field `LogTypes` in the other API struct, let's do the same here. (instead of `Logtypes`)

2020-12-09 20:19 UTC, austinbyers commented on api/lambda/source/models/integration.go
> +	// We use a switch to avoid git conflicts with enterprise
Don't need this comment anymore

2020-12-09 20:19 UTC, austinbyers commented on internal/core/source_api/api/utils.go
> +			// Backwards compatibility: Use the old fields, maybe the info is there.
Interesting, so existing integrations (that use a single S3 prefix) will still work?

2020-12-09 21:35 UTC, giorgosp commented on api/lambda/source/models/api.go
> +	S3PrefixLogTypes S3PrefixLogtypes `json:"s3PrefixLogTypes,omitempty"`
Yes they have been handled in the frontend PR https://github.com/panther-labs/panther/pull/2183/

2020-12-09 22:07 UTC, giorgosp commented on deployments/auxiliary/cloudformation/panther-log-analysis-iam.yml
> +                Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
Yes the only reason to not add the prefixes here is to allow users to *eventually* update without updating the CFN stack.
If they definitely to want to prevent us from having access to unrelated files, they could:
- change the role processing role manually (stack will drift but I *think* it's fine)
- configure the bucket notifications with separate SNS topic per prefix, so that we don't get notified for unwanted files.
There is definitely manual work, but there are solutions if it is very important of them.
I don't have a strong opinion on it though, so up to you guys, whatever you think will be better for users.
We should probably get some user feedback before deciding on such things.

2020-12-09 23:00 UTC, nhakmiller commented on deployments/auxiliary/cloudformation/panther-log-analysis-iam.yml
> +                Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
That's fair. None of our advanced users use these templates anyways, they all use terraform pretty much. This is more for the users who are newer to AWS, in which case making it easy for them to re-configure the source on a whim is probably best.

2020-12-10 09:58 UTC, kostaspap commented on api/lambda/source/models/integration.go
> +func (pl S3PrefixLogtypes) LogTypes() []string {
1. Switch to  `func (pl *S3PrefixLogTypes)`...same below. See: https://github.com/golang/go/wiki/CodeReviewComments#receiver-type

2. Do we even need this method? I think that our codebase outside this package should just stick to `RequiredLogTypes`.

2020-12-10 09:58 UTC, kostaspap commented on api/lambda/source/models/integration.go
> +	case IntegrationTypeAWS3:
Also include IntegrationTypeAWSScan. AWS Scans are also sending data to S3

2020-12-10 09:58 UTC, kostaspap commented on deployments/auxiliary/cloudformation/panther-log-analysis-iam.yml
> -    S3Prefix:
I see that this is not versioned?

If we make this change and publish it, is it possible that a user running an older version of Panther will get this instead of the CFN template meant for their version?

2020-12-10 09:58 UTC, kostaspap commented on internal/core/custom_resources/resources/self_registration.go
> +			S3PrefixLogTypes: models.S3PrefixLogtypes{{S3Prefix: "", LogTypes: logTypes}},
Actually that's a perfect example where having multiple prefixes -> log types for the same source is very useful. 
Can you configure it appropriately? E.g. CloudTrail data go to a separate prefix, GuardDuty as well, VPC FL as well, etc

2020-12-10 09:58 UTC, kostaspap commented on internal/core/source_api/api/update_integration.go
> +			return nil, err
You want to return `updateIntegrationInternalError`

2020-12-10 09:58 UTC, kostaspap commented on api/lambda/source/models/integration.go
> +	}
I imagine you want to bring the unique log types. Check these functions, you might find them useful: https://github.com/panther-labs/panther/blob/master/pkg/stringset/stringset.go

2020-12-10 09:58 UTC, kostaspap commented on internal/core/source_api/api/put_integration.go
> -				}
We want some kind of check here. 
1. A user shouldn't add the same prefix twice in the same S3 source
2. A user shouldn't add a prefix/bucket combination that is configuration in a different source.

2020-12-10 09:58 UTC, kostaspap commented on internal/core/source_api/api/update_integration_test.go
> +func TestS3PrefixLogTypes_BackwardsCompatibility(t *testing.T) {
👍

2020-12-10 09:58 UTC, kostaspap commented on internal/log_analysis/log_processor/sources/s3_client_cache_test.go
> +				IntegrationID:    "1",
Can you add a test with a source that has multiple prefixes?

2020-12-10 21:12 UTC, giorgosp commented on internal/core/source_api/api/put_integration.go
> -				}
Added

2020-12-10 21:12 UTC, giorgosp commented on internal/core/source_api/api/update_integration.go
> +			return nil, err
updated

2020-12-10 21:12 UTC, giorgosp commented on internal/log_analysis/log_processor/sources/s3_client_cache_test.go
> +				IntegrationID:    "1",
yep added

2020-12-11 08:54 UTC, kostaspap commented on api/lambda/source/models/integration.go
> +func (pl S3PrefixLogtypes) LogTypes() []string {
Ah right, didn't realize it was a slice. Fine to leave as is.

2020-12-11 09:12 UTC, kostaspap commented on internal/core/custom_resources/resources/self_registration.go
> +			S3PrefixLogTypes: models.S3PrefixLogtypes{{S3Prefix: "", LogTypes: logTypes}},
We don't create org trail (we couldn't). We create a normal trail. 
Here you can see the details: 
https://github.com/panther-labs/panther/blob/master/deployments/onboard.yml#L77-L86

The prefixes are controlled by us.

2020-12-11 11:08 UTC, giorgosp commented on internal/core/custom_resources/resources/self_registration.go
> +			S3PrefixLogTypes: models.S3PrefixLogtypes{{S3Prefix: "", LogTypes: logTypes}},
I have looked into it more. If we ever decide to change the prefixes in the CFN templates, nobody will remember to update the self_registration.  Narrowing down the prefixes here is very risky. For what benefit?

The log processor also still classifies based on all the source's  logtypes. We need to update it to narrow down the logtypes by the prefix, when possible. But this is not yet implemented.

2020-12-11 11:10 UTC, giorgosp commented on internal/core/custom_resources/resources/self_registration.go
> +			S3PrefixLogTypes: models.S3PrefixLogtypes{{S3Prefix: "", LogTypes: logTypes}},
I could perhaps add a comment in the CFN templates, so that if we change the prefixes, update the `self_registration` too. But the bug will also occur if a new log type is added there.

2020-12-11 11:15 UTC, kostaspap commented on internal/core/custom_resources/resources/self_registration.go
> +			S3PrefixLogTypes: models.S3PrefixLogtypes{{S3Prefix: "", LogTypes: logTypes}},
The benefits are: 
1. Improved performance
2. We experience a bug from time to time where we try to parse JSON data using CSV parser and the CSV parser triggers an OOM exception. 

it is unlikely we will ever change the prefix, and if we ever do we will capture that issue easily. 
A comment in there should be enough. We don't change prefixes that easily. There are many places in the code were some prefix in the CFN template is also used in the code e.g. see SQS source Firehose, EventBridge Firehose, CloudSecurity firehose and so on.

2020-12-11 11:18 UTC, kostaspap commented on internal/core/custom_resources/resources/self_registration.go
> +			S3PrefixLogTypes: models.S3PrefixLogtypes{{S3Prefix: "", LogTypes: logTypes}},
The feature was developed for usecases exactly like this (one bucket, many log types in different prefixes). We recommend users to take the approach of specifying their Prefix -> Log types correctly. Why shouldn't we do it. 
I believe it should be easy to do.

2020-12-11 11:25 UTC, giorgosp commented on internal/core/custom_resources/resources/self_registration.go
> +			S3PrefixLogTypes: models.S3PrefixLogtypes{{S3Prefix: "", LogTypes: logTypes}},
It's easy but time consuming, factoring in deploying and testing etc. But my main concern is it is brittle and we can't easily unit test that these prefixes match all the configurations in the CFN templates.

The only way to find any problems is mis-classification logs and alerts.

I have almost implemented it, needs some testing.

2020-12-11 12:21 UTC, kostaspap approved these changes
LGTM once you address any open comments!

2020-12-11 12:22 UTC, giorgosp commented on internal/core/custom_resources/resources/self_registration.go
> +			S3PrefixLogTypes: models.S3PrefixLogtypes{{S3Prefix: "", LogTypes: logTypes}},
Updated. Deploying now

2020-12-11 14:16 UTC, giorgosp commented on api/lambda/source/models/integration.go
> +	case IntegrationTypeAWS3:
updated, had to deal with some conflicts now that I got your cloud security logs PR

2020-12-16 09:50 UTC, kostaspap requested changes

2020-12-16 09:50 UTC, kostaspap commented on internal/log_analysis/log_processor/processor/processor.go
> +					if strings.HasPrefix(input.S3ObjectKey, m.S3Prefix) {
1. This logic doesn't seem correct. Prefixes might overlap, e.g. you can have prefixes like "test", "test/foo" and S3 key "test/boo/bar.gz". The sources cache in the log processor has logic to deal with this. Maybe you can modify the logic in the sources cache to return you a SourceIntegration only with the appropriate log types. Or, sources cache could just return a different structure and not `SourceIntegration` since that struct is not so useful for the log processor anymore
2. Why do the S3 and AWScan need different logic? In the end, the AWSScan also has S3PrefixLogTypes but has only 1 entry.

2020-12-16 09:50 UTC, kostaspap commented on internal/log_analysis/log_processor/sources/s3_client_cache.go
> +	sourceByPrefix   map[string]*models.SourceIntegration
This doesn't look correct. You can have two sources in different buckets with the same prefixes. They would overlap here.

2020-12-16 10:09 UTC, giorgosp commented on internal/log_analysis/log_processor/processor/processor.go
> +					if strings.HasPrefix(input.S3ObjectKey, m.S3Prefix) {
1. Some fields from `SourceIntegration` are used for logging etc.  Your concern is correct although the source cache's logic doesn't help here. Imagine users define these prefixes and log types, which log types should be available for classification if an object key `prefixA/prefixB/log.json` comes in?
- `prefixA/ -> [Log.A]`
- `prefixA/prefixB/ -> [Log.B]`
- `prefixC/ -> [Log.C]`
- `  ""        -> [Log.D]`
We need to use the union of all the matching prefixes, in the example this would be `[Log.A, Log.B, Log.D]`. This is what the code does now.

2. `AWSScan` doesn't have the `S3PrefixLogTypes` field, it's `prefix` and `logtypes` fields are static (`cloudsecurity` prefix and `snapshotlogs.LogTypes()`).

2020-12-16 10:13 UTC, giorgosp commented on internal/log_analysis/log_processor/sources/s3_client_cache.go
> +	sourceByPrefix   map[string]*models.SourceIntegration
Hmm valid concern, will add a unit test and take it from there

2020-12-16 10:17 UTC, kostaspap commented on internal/log_analysis/log_processor/processor/processor.go
> +					if strings.HasPrefix(input.S3ObjectKey, m.S3Prefix) {
> We need to use the union of all the matching prefixes, in the example this would be [Log.A, Log.B, Log.D]. This is what the code does now.

That's not how the application works now. The way the application works now is that longer prefixes get priority over shorter ones. We had a test specifically for this see : https://github.com/panther- labs/panther/blob/master/internal/log_analysis/log_processor/sources/s3_client_cache_test.go#L205

This solves cases like the ones we have in our self-onboarding. We have a bucket where: 
1. Cloudtrail data get in <bucket>/AWS/<AccountID>/CloudTrail/
2. S3 Server Access data get in <bucket>/*

For this purpose, we have two prefix mappings:
1. A prefix mapping "/AWS/<AccountID>/CloudTrail/" -> AWS.CloudTrail
2. A prefix mapping for "" -> AWS.S3ServerAccess

Since longer prefix gets priority, any CloudTrail events will use only the CloudTrail parser, S3 server access events will use the S3 Server access parser.

2020-12-16 10:38 UTC, alxarch requested changes
The longest prefix needs to have priority.
The changes to source cache code seem incorrect.

2020-12-16 10:38 UTC, alxarch commented on internal/log_analysis/log_processor/sources/sources.go
> -
The BuildClassifier was left here on purpose.
We don't want the classifier module to depend on the mess that is models.SourceIntegration.
The goal is to replace classifier altogether with a `pantherlog.LogParser` interface at some point.
It is also difficult to track the changes without inline diffs.
Please put it back.

2020-12-16 10:38 UTC, alxarch commented on internal/log_analysis/log_processor/processor/processor.go
> +					if strings.HasPrefix(input.S3ObjectKey, m.S3Prefix) {
Longer prefixes override shorter ones.
One of the reasons to use prefixes (and to make it easier to add new ones with this PR) is to be able to use the same S3 bucket for conflicting log types. If we don't 'specialize' log types based on prefix length, we will not be able to classify correctly or add 'catch all' log types with `""` prefix.

2020-12-16 10:38 UTC, alxarch commented on internal/log_analysis/log_processor/sources/s3_client_cache.go
> +	sourceByPrefix   map[string]*models.SourceIntegration
The cache logic relies on sourceByPrefix mapping to multiple sources.

2020-12-16 10:38 UTC, alxarch commented on internal/log_analysis/log_processor/sources/s3_client_cache.go
> +func (c *sourceCache) FindS3(bucket, objectKey string) *models.SourceIntegration {
I would suggest to keep the old logic of the cache and return `(src *models.SourceIntegration, logTypes []string)` here.

2020-12-16 14:10 UTC, giorgosp commented on internal/log_analysis/log_processor/sources/sources.go
> -
Moved it back

2020-12-16 14:11 UTC, giorgosp commented on internal/log_analysis/log_processor/processor/processor.go
> +					if strings.HasPrefix(input.S3ObjectKey, m.S3Prefix) {
Updated. Fixed to use the longest prefix

2020-12-16 14:11 UTC, giorgosp commented on internal/log_analysis/log_processor/sources/s3_client_cache.go
> +	sourceByPrefix   map[string]*models.SourceIntegration
Update it to return the correct source. Added a test case

2020-12-16 14:12 UTC, giorgosp commented on internal/log_analysis/log_processor/sources/s3_client_cache.go
> +func (c *sourceCache) FindS3(bucket, objectKey string) *models.SourceIntegration {
Ended up adding a method `S3PrefixLogTypes.LongestPrefixMatch()` to avoid adding many changes

2020-12-16 14:43 UTC, kostaspap requested changes

2020-12-16 14:43 UTC, kostaspap commented on api/lambda/source/models/integration.go
> +func (pl S3PrefixLogtypes) LongestPrefixMatch(objectKey string) *S3PrefixLogtypesMapping {
Could switch it to return `(S3PrefixLogTypesMapping, bool)`. See https://github.com/golang/go/wiki/CodeReviewComments#in-band-errors

2020-12-16 14:43 UTC, kostaspap commented on internal/log_analysis/log_processor/processor/processor.go
> +			var availableLogTypes []string
instead of having a case statement and then an `if` inside, maybe it will be more clean if you create two different case statements, 
```
case models.IntegrationTypeAWS3:
....
case models.IntegrationTypeAWSScan:
....
```

2020-12-16 14:43 UTC, kostaspap commented on internal/log_analysis/log_processor/sources/s3_client_cache.go
> +			byBucket[bucket] = append(bucketSources, prefixSource{prefix: prefix, source: source})
This should be `byBucket[bucket] = append(byBucket[bucket], prefixSource{prefix: prefix, source: source})`.

You can verify the bug by changing the line 305 of the unit test to be:
```
src := cache.FindS3("bar", "foo/foo/foo/prefix/qux.json")
```
The test will fail, even though it shouldn't

2020-12-16 16:15 UTC, giorgosp commented on internal/log_analysis/log_processor/sources/s3_client_cache.go
> +			byBucket[bucket] = append(bucketSources, prefixSource{prefix: prefix, source: source})
Good catch! fixed

2020-12-16 16:15 UTC, giorgosp commented on internal/log_analysis/log_processor/processor/processor.go
> +			var availableLogTypes []string
updated

2020-12-16 16:15 UTC, giorgosp commented on api/lambda/source/models/integration.go
> +func (pl S3PrefixLogtypes) LongestPrefixMatch(objectKey string) *S3PrefixLogtypesMapping {
Good idea, updated

2020-12-17 11:47 UTC, kostaspap approved these changes
LGTM

2020-12-17 14:17 UTC, merged