Implement custom log type updates without considering race conditions
panther-labs/panther pull request #2235
Opened 2020-12-09 15:42 UTC by alxarch

## Background

Implement updates for custom log types

## Changes

- Adds diff for logschema.Schema
- Blocks backward incompatible updates
- Sends UpdateTable event to datacatalog updater

## Testing

- mage test:go
- E2E pending

2020-12-17 15:43 UTC, kostaspap requested changes

2020-12-17 15:43 UTC, kostaspap commented on internal/core/logtypesapi/customlogs.go
> +	}
Should these errors be constants here, like we do for the other errors returned to users? internal/core/logtypesapi/api.go

2020-12-17 15:43 UTC, kostaspap commented on internal/core/logtypesapi/customlogs.go
> +	if rev := currentRevision; rev == 0 {
nit: just 
```
if currentRevision == 0 {
...
}
```

2020-12-17 15:43 UTC, kostaspap commented on internal/core/logtypesapi/customlogs.go
> +		result, err := api.Database.CreateCustomLog(ctx, id, &input.CustomLog)
If I get it right, creating a new Custom Log or not relies on the version passed by the client in the request? 
This seems that it could break easily - a misbehaving client can sent requests for the same version. 
Revision (version?) number should be generated by the backend when someone tries to update an existing log type.

2020-12-17 15:43 UTC, kostaspap commented on internal/core/logtypesapi/dynamodb.go
> +	//}
leftovers?

2020-12-17 15:43 UTC, kostaspap commented on internal/core/logtypesapi/dynamodb.go
> +			switch reason := txErr.CancellationReasons[0]; cancellationReasonCode(reason) {
Is this going to have always 1 element?

2020-12-17 15:43 UTC, kostaspap commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +	}
Why bother put all this logic in here? We can just try to create the table in Glue and if it fails with "AlreadyExists" we are good. This should be a low volume operation anyway. It saves us some lines of code to remove this.

2020-12-17 15:48 UTC, alxarch commented on internal/core/logtypesapi/dynamodb.go
> +			switch reason := txErr.CancellationReasons[0]; cancellationReasonCode(reason) {
The TransactionCanceledException has as many elements in CancelationReasons as the items in the TransactWriteItemsInput. So yes, we know we are checking the specific condition for the first element

2020-12-17 15:50 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +	if err := h.createOrUpdateTablesForLogTypes(ctx, logTypes); err != nil {
The createOrUpdateTables handles the creation of ruleErrors and ruleMatches. I tried recreating the function to only create the tables it was given but the result was a lot of code, so I reverted.

2020-12-17 15:57 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +}
Avoiding extra CreateTable calls was added because we rely on the 'auto-updating' createOrUpdateTables function. It limits the posibillity of actually doing an update of the table here. We want updates to only happen when custom logs are updated or when we deploy. There's still a chance that we might do an out-of-place update but it is significantly lower. The alternative was to have an 'only-create' function but handling the related tables there was  more code than this simple check. I am not happy about the state of things either. This is a hail mary kind of think.

2020-12-17 15:58 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/handler.go
> +	tablesCreated map[string]struct{}
Read my reply above as to why this was added

2020-12-17 15:58 UTC, alxarch commented on internal/log_analysis/log_processor/customlogs/updates.go
> +		return errors.Errorf("cannot delete field %q at %q", target, path)
we can't because this opens the door to renaming fields by two consecutive updates

2020-12-17 16:01 UTC, alxarch commented on internal/core/logtypesapi/dynamodb.go
> +		Revision:  revision + 1,
No, it does not work this way. The revision is only for preventing users stepping on each other's toes. The actual guard that does not allow users to override a record is in the id itself. The create transaction (when revision is 0) has a condition that the record does not exist. So a user putting 0 there has no effect.

2020-12-17 16:02 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/main/lambda.go
> +	})
We do need a cached resolver, otherwise we would be hitting the LogTypesAPI on every file we process in the log processor.

2020-12-17 16:03 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +	}
Answered below

2020-12-17 16:05 UTC, alxarch commented on internal/core/logtypesapi/customlogs.go
> +	if rev := currentRevision; rev == 0 {
fixed

2020-12-17 16:07 UTC, alxarch commented on internal/core/logtypesapi/customlogs.go
> +		result, err := api.Database.CreateCustomLog(ctx, id, &input.CustomLog)
The constraint comes from the different transaction conditions on create and update. Create ensures the record does not exist. Update ensures that the record is at this revision (it also reads the entry from DDB so user input is there only for avoiding overwrites).

2020-12-18 10:50 UTC, giorgosp reviewed
LGTM generally, leaving final approval to Kostas

2020-12-18 10:50 UTC, giorgosp commented on internal/core/logtypesapi/customlogs.go
> +	currentRevision := input.Revision
Versioning is implemented so that 2 different users cannot update the same schema simultaneously?

2020-12-18 10:50 UTC, giorgosp commented on internal/core/logtypesapi/customlogs.go
> +	currentRevision := input.Revision
Does the frontend handle revision error gracefully? I mean telling the user that a different version is on the server and handle it accordingly? Or the frontend just shows a "500 retry later"?

2020-12-18 10:50 UTC, giorgosp commented on internal/core/logtypesapi/customlogs.go
> +		return nil, NewAPIError(ErrRevisionConflict, fmt.Sprintf("record %s@%d does not exist", id, currentRevision))
nit: I think someone reading the logs won't understand the id@revision format. Perhaps change the error texts to something like `record %s at revision %d does not exist` and `record %s is on revision %d, not %d`

2020-12-18 10:50 UTC, giorgosp commented on internal/core/logtypesapi/customlogs.go
> +		return nil, err
If sending the SQS message fails, the UI will probably show a "try again later" message but they won't have the new revision number (because saving in db succeeded). Subsequent requests will probably fail with wrong revision error, so we need to make sure the FE handles revision conflicts well and guides makes it easy for the user to proceed.

2020-12-18 10:50 UTC, giorgosp commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +		// We need methods that use abstract Database/Table/Partition structs that can contain info for all backends.
👍

2020-12-18 10:50 UTC, giorgosp commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +	if err := h.createOrUpdateTablesForLogTypes(ctx, logTypes); err != nil {
Since we all agree that a  create-only function is the a cleaner solution I'd suggest we proceed writing it, in the simplest way possible. No need to refactor a lot of code now to make it ideal, we can do small improvements. A copycat of `CreateOrUpdateGlueTables()` would be enough for now imo.
The current logic to avoid updates is more difficult to follow.

2020-12-18 10:50 UTC, giorgosp commented on internal/log_analysis/datacatalog_updater/main/lambda.go
> +	clearCache := cachedResolver.(interface {
Why not just `clearCache := cachedResolver.Forget` ?

2020-12-18 16:29 UTC, alxarch commented on internal/core/logtypesapi/customlogs.go
> +	currentRevision := input.Revision
Yes, the API errors are embedded in the response and they are shown to the user.

2020-12-18 16:31 UTC, alxarch commented on internal/core/logtypesapi/customlogs.go
> +		return nil, err
I don't see any way to avoid returning the erorr here.
Error handling is hard. Our hopes here lie with the retries in the underlying AWS session.
Do you have any suggestion on how to handle this gracefully?

2020-12-18 16:32 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/main/lambda.go
> +	clearCache := cachedResolver.(interface {
cachedResolver is of type `logtypes.Resolver`. We need the cast to access the other function that exists in the underlying value.

2020-12-18 16:40 UTC, alxarch commented
> Since we all agree that a create-only function is the a cleaner solution I'd suggest we proceed writing it, in the simplest way possible. No need to refactor a lot of code now to make it ideal, we can do small improvements. A copycat of CreateOrUpdateGlueTables() would be enough for now imo.
The current logic to avoid updates is more difficult to follow.

I spent 2 hours this morning trying to do this and there is just too much code. The problem once again stems from the non-existent separation of concerns in the `awsglue` package.There's too much code that needs shuffling around to achieve this. 
Factoring in the test changes required, I don't think it's viable for this PR. I will add it as a PR on top of this PR to show the required changes.
With the plan to move to an abstraction layer above Glue/Athena and Snowflake to handle Tables, all that work will be futile.
My suggestion if we insist on this, is to shelve this PR for now and come back to it after we conclude the conversations for the schema management RFC. I agree that having just a good-enough solution with corner cases is not the best option. But this needs bigger changes to be properly fixed.

2020-12-18 18:02 UTC, giorgosp commented on internal/core/logtypesapi/customlogs.go
> +		return nil, err
I know but if `SendUpdateTableForLogType` fails it will leave the system in an inconsistent state. Perhaps show a message to the user to contact Panther support?

2020-12-18 18:03 UTC, giorgosp commented on internal/core/logtypesapi/customlogs.go
> +		return nil, err
It will be happen very rarily but if it happens it will be a frustrating experience for the user.

2020-12-18 18:07 UTC, giorgosp commented on internal/log_analysis/datacatalog_updater/main/lambda.go
> +	clearCache := cachedResolver.(interface {
This is a bit confusing. Why not make `cachedResolver` public and make `CachedResolver()` return a struct instead of interface? This will also follow the idiom of `return structs accept interfaces`.

2021-01-05 13:17 UTC, kostaspap commented
> > Since we all agree that a create-only function is the a cleaner solution I'd suggest we proceed writing it, in the simplest way possible. No need to refactor a lot of code now to make it ideal, we can do small improvements. A copycat of CreateOrUpdateGlueTables() would be enough for now imo.
> > The current logic to avoid updates is more difficult to follow.
> 
> I spent 2 hours this morning trying to do this and there is just too much code. The problem once again stems from the non-existent separation of concerns in the `awsglue` package.There's too much code that needs shuffling around to achieve this.
> Factoring in the test changes required, I don't think it's viable for this PR. I will add it as a PR on top of this PR to show the required changes.
> With the plan to move to an abstraction layer above Glue/Athena and Snowflake to handle Tables, all that work will be futile.
> My suggestion if we insist on this, is to shelve this PR for now and come back to it after we conclude the conversations for the schema management RFC. I agree that having just a good-enough solution with corner cases is not the best option. But this needs bigger changes to be properly fixed.

As I see it the change is: 
1. Add a new method "CreateTable" here https://github.com/panther-labs/panther/blob/master/internal/log_analysis/awsglue/table_metadata.go#L45-L52
2. Add a new method CreateTables here: https://github.com/panther-labs/panther/blob/master/internal/log_analysis/gluetables/gluetables.go#L79
3. Invoke that method from the code above. 

It is a cleaner and more robust solution. I think it could be challenging to refactoring the existing code, but we don't have to do that.

2021-01-05 16:06 UTC, alxarch commented
> As I see it the change is:
> 
> 1. Add a new method "CreateTable" here https://github.com/panther-labs/panther/blob/master/internal/log_analysis/awsglue/table_metadata.go#L45-L52
> 2. Add a new method CreateTables here: https://github.com/panther-labs/panther/blob/master/internal/log_analysis/gluetables/gluetables.go#L79
> 3. Invoke that method from the code above.

The problem is that all the logic to produce the StorageDescriptor is bundled with the CreateOrUpdate stuff. Starting to move things around to extract functions quickly leads to a major overhaul of the awsglue.go file.

2021-01-05 18:10 UTC, kostaspap commented on internal/log_analysis/datacatalog_updater/main/lambda.go
> +	})
Are you sure? Can you point me to the code? When I look at the code, I see that we call the resolver only when we update or create a table. The `HandleS3EventRecord` which handles the partition creation doesn't use the resolver.

2021-01-05 18:18 UTC, kostaspap commented on internal/log_analysis/log_processor/logtypes/resolver.go
> +func CachedResolver(maxAge time.Duration, r Resolver) Resolver {
Tests for this?

2021-01-05 18:22 UTC, kostaspap commented on internal/log_analysis/log_processor/logtypes/resolver.go
> +	reply, err, _ := c.group.Do(name, func() (interface{}, error) {
This looks pretty neat. I assume we have to do this because the resolution could potentially include long running tasks (e.g. including I/O)?

2021-01-05 18:22 UTC, kostaspap commented on internal/log_analysis/log_processor/main/lambda.go
> +		logtypes.CachedResolver(logTypeMaxAge, &logtypesapi.Resolver{
What would be the issue if we use a cached entry that is no longer valid?

2021-01-05 18:33 UTC, kostaspap commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +	if err := h.createOrUpdateTablesForLogTypes(ctx, logTypes); err != nil {
What is the scenario we are trying to protect against using this cache? What will happen if this code gets invoked? 

As as see it, this code will get invoked: every time someone adds a log type (that was already added to one source)  to another source, this code will execute. The cache will not help for many of our scenarios - we have multiple instances of this lambda running, each with their own cache and lambda's get recycled after few hours. What would be the problem if this code gets invoked?

2021-01-07 08:32 UTC, alxarch commented on internal/core/logtypesapi/customlogs.go
> +	}
fixed

2021-01-07 16:43 UTC, alxarch commented on internal/core/logtypesapi/dynamodb.go
> +			switch reason := txErr.CancellationReasons[0]; cancellationReasonCode(reason) {
I refactored the WriteTransaction logic to use `ddbextras` module. It binds the error handlers with each `TransactWriteItem` so that it is more convenient to define them in a declarative way.

2021-01-07 16:43 UTC, alxarch commented on internal/core/logtypesapi/dynamodb.go
> +	//}
fixed

2021-01-07 16:58 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +}
I introduced ``  methods and functions to `awsglue.GlueTableMetadata#CreateTableIfNotExists()` and  `gluetables.CreateTablesIfnotExists` that handle the table creation *only* when a view uses a schema. I also removed the created tables cache logic.

2021-01-07 16:59 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/handler.go
> +	tablesCreated map[string]struct{}
Fixed

2021-01-07 17:01 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/main/lambda.go
> +	})
We need the cached resolver for the log processor. The data catalog could avoid caching the results but since we reolve each available log type multiple times on most requests (resolveTables etc) it would make no sense to rebuild and revalidate the logtype entries over and over again. I can remove it if you want.

2021-01-07 17:46 UTC, alxarch commented on internal/core/logtypesapi/customlogs.go
> +		return nil, err
fixed

2021-01-07 17:47 UTC, alxarch commented on internal/core/logtypesapi/customlogs.go
> +		return nil, err
Just noting that it is still possible for the update to fail once queued. Which is more of a real issue than failing to send a message to SQS. Cannot address this in this PR. We need state for the pending updates to be store in DDB.

2021-01-07 17:54 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +	}
Fixed

2021-01-07 17:55 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +	if err := h.createOrUpdateTablesForLogTypes(ctx, logTypes); err != nil {
I split the logic for each event to createaIfNotExists/updateIfExists

2021-01-07 17:55 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +}
Also UpdateIfExists

2021-01-07 17:55 UTC, alxarch commented on internal/core/logtypesapi/customlogs.go
> +		return nil, NewAPIError(ErrRevisionConflict, fmt.Sprintf("record %s@%d does not exist", id, currentRevision))
fixed

2021-01-07 17:57 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/main/lambda.go
> +	clearCache := cachedResolver.(interface {
Fixed

2021-01-07 18:00 UTC, alxarch commented on internal/core/logtypesapi/customlogs.go
>  	}
It is best to fail early here. A user should be informed that the entry was updated before trying to fix any other errors (validation, invalid update, syntax etc)

2021-01-07 18:02 UTC, alxarch commented on internal/log_analysis/log_processor/logtypes/resolver.go
> +	reply, err, _ := c.group.Do(name, func() (interface{}, error) {
Yes, singleflight avoids multiple API requests firing  when a record is stale.

2021-01-07 18:02 UTC, alxarch commented on internal/log_analysis/log_processor/main/lambda.go
> +		logtypes.CachedResolver(logTypeMaxAge, &logtypesapi.Resolver{
The failure scenario probably involves missing fields/indicators etc.

2021-01-08 12:21 UTC, kostaspap commented on internal/log_analysis/datacatalog_updater/datacatalog/update_table.go
> +		return nil
When can this happen? Probably if we are in inconsistent state? Should it return error here to alert us?

2021-01-08 12:22 UTC, kostaspap commented on internal/log_analysis/log_processor/main/lambda.go
> +		logtypes.CachedResolver(logTypeMaxAge, &logtypesapi.Resolver{
Ok, we can live with that :)

2021-01-08 12:26 UTC, kostaspap commented on internal/log_analysis/datacatalog_updater/main/lambda.go
> +	})
Yeah, we can keep the cached resolved for the log processor. 

As I see, removing the cached Resolver from here simplifies the logic - no more need for the "Forget" functionality and removes the change of wrong resolution. 
The I/O required is 1 I/O operation per log type on ever Update or Create table operation, correct? Sounds negligible.

2021-01-08 12:44 UTC, giorgosp reviewed
Nice work, looks good to me. Only left some comments for better readability for someone new to this code.
Leaving final approval @kostaspap

2021-01-08 12:44 UTC, giorgosp commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +	// TODO: This event needs to ONLY CREATE tables. Updating a table MUST include syncing the partitions.
👍

2021-01-08 12:44 UTC, giorgosp commented on internal/log_analysis/datacatalog_updater/datacatalog/update_table.go
> +	// We need to fetch a fresh entry for this log type
Perhaps update the comment to explain the why we need to fetch a fresh entry?

2021-01-08 13:03 UTC, alxarch commented on internal/log_analysis/log_processor/logtypes/resolver.go
> +func CachedResolver(maxAge time.Duration, r Resolver) Resolver {
added

2021-01-08 13:04 UTC, alxarch commented on internal/core/logtypesapi/ddbextras/ddbextras.go
> +		return true
There is inconsitency in the names of the constants in the dynamodb package. Some cancelation reasons are returned without the 'Exception' suffix from the API.

2021-01-08 13:05 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/update_table.go
> +		return nil
This can happen in normal case when a custom log type is updated but it is not used by any sources.

2021-01-08 13:09 UTC, kostaspap commented on internal/log_analysis/datacatalog_updater/datacatalog/update_table.go
> +		return nil
gotcha

2021-01-08 13:09 UTC, alxarch commented on internal/core/logtypesapi/ddbextras/ddbextras.go
> +type Update struct {
I am addin full comments in the ddbextras package.
The names will remain short as one of the major pain points of the 'official' dynamodb packages are `UnnecessarilyLongNamesAsIfThisWasJAVA`. Always think of the name of the type as `ddbextras.Update` and I would agree that `ddbextras` is a bad name. Maybe something like `transact` would be better.

2021-01-08 13:28 UTC, giorgosp commented on internal/log_analysis/datacatalog_updater/datacatalog/update_table.go
> +		return nil
>This can happen in normal case when a custom log type is updated but it is not used by any sources.
I think it would be helpful if you add this as a comment too

2021-01-08 17:07 UTC, alxarch commented on internal/core/logtypesapi/ddbextras/ddbextras.go
> +	Add          map[string]interface{}
These are actions of the update expression. An update expression modifies attributes. For more information about how dynamo db transactions work see [the API docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactWriteItems.html)
I will add the link in the package doc comment

2021-01-08 17:11 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +	// TODO: This event needs to ONLY CREATE tables. Updating a table MUST include syncing the partitions.
This is resolved, removing the TODO

2021-01-08 17:15 UTC, kostaspap commented on internal/core/logtypesapi/customlogs.go
> +		return nil, err
It's less of an issue. If it reaches the SQS it will be retried for several hours before it gets driven to the DLQ.

2021-01-08 17:16 UTC, kostaspap commented on internal/core/logtypesapi/customlogs.go
>  	}
Sure

2021-01-08 17:16 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/update_table.go
> +	// We need to fetch a fresh entry for this log type
Fixed

2021-01-08 17:16 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/update_table.go
> +		return nil
Added comment

2021-01-08 17:28 UTC, alxarch commented on internal/core/logtypesapi/ddbextras/ddbextras.go
> +func (b WriteTransaction) Check(err error) error {
added

2021-01-08 17:36 UTC, alxarch commented on internal/core/logtypesapi/ddbextras/ddbextras.go
> +func (b WriteTransaction) Check(err error) error {
Fixed

2021-01-08 18:02 UTC, kostaspap approved these changes

2021-01-08 18:04 UTC, merged