feat: add timeout race
panther-labs/panther pull request #2296
Opened 2020-12-16 23:05 UTC by s0l0ist

## Background

The alert delivery pipeline could fail if a destination fails to respond back to Panther within the lambda timeout period (60 seconds). This would cause the batch of SQS events to be retried and any previously successful deliveries would be re-sent again. Closes #1931 

## Changes

- Add a race for each goroutine
- Add two globals, one for the timeout and one for testing.

## Testing

- Added a test for delivery timeouts

2020-12-17 03:59 UTC, s0l0ist commented
I need to make some changes to the tests because the return values are now sometimes out of order which sometimes flags this as a failure.

2020-12-17 07:14 UTC, kostaspap requested changes

2020-12-17 07:14 UTC, kostaspap commented on internal/core/alert_delivery/api/api.go
> +	deliveryTimeoutDuration = 50 * time.Second // Gives 10 seconds to terminate gracefully
The duration of the lambda is available through the Lambda context. We shouldn't hardcode "50" here - we 
should instead fetch the Lambda duration and subtract a number.

2020-12-17 07:14 UTC, kostaspap commented on internal/core/alert_delivery/api/outputs.go
> +	if len(alert.Destinations) > 0 {
Something is wrong with this code. We have 7 for loops, many of them going over the same slices again and again. 
Can this code be organized somehow?

2020-12-17 07:14 UTC, kostaspap commented on internal/core/alert_delivery/api/send.go
> +	for alert, outputIds := range alertOutputs {
Go offers `context.Context` object exactly for cases like this: cancelling tasks. It seems we are trying to work our way around using this and in the way introducing a bug (goroutine leak) for every go routine that didn't finish within the timeout. 

The way to fix the issue: 
1. Update `sendAlert` to accept a `context.Context`. The context we pass with have the appropriate timeout configured.
2. `sendAlert` uses the context for every I/O operation it does. AWS SDK and HTTP Client both allow setting context.Context
3. If the timeout expires, the I/O operation will fail. A `context.DeadlineExceeded` error will be returned.

2020-12-17 07:14 UTC, kostaspap commented on internal/core/alert_delivery/api/send.go
> +			case <-time.After(deliveryTimeoutDuration):
As I mention above this introduces a bug. We can have goroutines leak. 
If the Lambda happens to timeout in the meantime, these routines will ... freeze and restart when the Lambda container runs again.

2020-12-17 14:23 UTC, s0l0ist commented on internal/core/alert_delivery/api/api.go
> +	deliveryTimeoutDuration = 50 * time.Second // Gives 10 seconds to terminate gracefully
Perfect, I didn't know I could get the lambda timeout.

2020-12-23 20:03 UTC, s0l0ist commented on internal/core/alert_delivery/api/outputs.go
> +	if len(alert.Destinations) > 0 {
They're needed, but I've since decoupled all the loops into different functions for readability.

2020-12-23 20:04 UTC, s0l0ist commented on internal/core/alert_delivery/api/send.go
> +			case <-time.After(deliveryTimeoutDuration):
Has been fixed using contexts.

2020-12-24 10:16 UTC, kostaspap reviewed
This is really great work @s0l0ist . I love that we now are passing the context around, this is going to be super useful for many other of our functions. Great job!

Note that I have put few comments marked as `nitpics`. Feel free to ignore any of those if you feel they expand the scope of the PR too much

2020-12-30 16:06 UTC, s0l0ist commented on internal/core/alert_delivery/api/send.go
> +				deliveryStatuses = append(deliveryStatuses, status)
Honestly, as long as we log **something** for the status when the context is cancelled/expired instead of crashing the lambda or timing out the lambda, we are fine. 

I wrote a test for this functionality and didn't see the race condition you're describing, but it's possible that the test cannot cover this exact situation. I will refactor this again to make it more clear and have consistent error messages when the context is cancelled/expired.

2020-12-30 16:14 UTC, s0l0ist commented on internal/core/alert_delivery/api/send_test.go
> +	mockSlowOutputClient.On("Slack", mock.Anything, mock.Anything, mock.Anything).Return(slowResponse).Maybe()
Awesome!

2020-12-30 16:18 UTC, s0l0ist commented on internal/core/alert_delivery/api/deliver_alert.go
> +	}
Yeah this is better. Will fix. 

However in the future, this part is going to always be painful in the event we add more alert types as it isn't obvious we need another test for delivering alerts for each new type. In fact, this is why this part of the code exists in the first place.

2020-12-30 17:36 UTC, s0l0ist commented on internal/core/alert_delivery/api/outputs.go
> +	uniqMap := make(map[*outputModels.AlertOutput]struct{})
After taking a closer look, the older tests were passing and it produced the desired effect; however, you're completely right. I've refactored this to `map[string]*outputModels.AlertOutput`

2020-12-30 17:57 UTC, s0l0ist commented on internal/core/alert_delivery/api/send.go
> +	statusChannel := make(chan DispatchStatus, 1)
This will be garbage collected.

2020-12-30 17:58 UTC, s0l0ist commented on internal/core/alert_delivery/api/send.go
> +	deadlineCtx, cancel := context.WithDeadline(context.Background(), deadlineBuffer)
This was a good catch and was probably why I had a hard time testing things...thanks!

2020-12-30 19:25 UTC, s0l0ist commented on internal/core/alert_delivery/api/deliver_alert.go
> +	}
Yep gonna hold off on this one.

2021-01-04 15:15 UTC, kostaspap commented on internal/core/alert_delivery/api/send.go
> +				deliveryStatuses = append(deliveryStatuses, status)
> Honestly, as long as we log something for the status when the context is cancelled/expired instead of crashing the lambda or timing out the lambda, we are fine.

As I see it, the race condition is real...  to the end user the behavior will be similar (maybe a different error code/message than expected) but still the code should ideally shield against such issues. 

I don't think it's a huge issue, so I don't think it's a reason to block this PR, but nevertheless I think a TODO there it would be useful (the TODO could just reference this discussion)

2021-01-04 15:16 UTC, kostaspap approved these changes
Nice job! The `HandleWithContext` function will prove useful in many other parts of the code!

2021-01-04 20:16 UTC, merged