@rleighton Update gluesync and datacatalog updater for cloudsec
panther-labs/panther pull request #2326
Opened 2020-12-23 21:20 UTC by rleighton

## Before

Gluesync and the datacatalog updater did not have config for cloudsec.

Also, the oplog was missing from datacatalog-updater, this broke the dash board and remove error logging.

## Changes

- Add cloudsec tables where necessary
- Add back oplog to datacatalog updater (needed for error logging and dashboard metrics)

## Testing

- mage test:ci
- mage deploy

2020-12-24 08:51 UTC, kostaspap commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +	if err := athenaviews.CreateOrReplaceLogViews(h.AthenaClient, h.AthenaWorkgroup, deployedLogTables); err != nil {
The views have a 1:1 relationship with databases: 
`panther_logs` -> `panther_views.all_logs`
`panther_rule_matches` -> `panther_views.all_rule_matches`
`panther_rule_errors` -> `panther_views.all_rule_errors`

Since the CloudSec datasets are not "logs", we decided we shouldn't put them in the `panther_logs` database, but in their own database. Following them same concept, we should put them in a different view and not inside the `all_logs` view. 
If we want, we could make eventually a view across *everything* (logs, rule errors, rule matches, cloudsec)

2020-12-26 17:48 UTC, rleighton commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +	if err := athenaviews.CreateOrReplaceLogViews(h.AthenaClient, h.AthenaWorkgroup, deployedLogTables); err != nil {
Agree. We should be consistent. I'll make a view for the cloudsec database. I'll also add a view over all databases, which is easy and just handy.

2020-12-26 20:37 UTC, rleighton commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +	if err := athenaviews.CreateOrReplaceLogViews(h.AthenaClient, h.AthenaWorkgroup, deployedLogTables); err != nil {
Done

2020-12-26 20:41 UTC, rleighton commented
I changed the configuration to allow rules to be written against this data. This is not just cleaner because cloud security is no longer  an exception, it allows rules to be written against specific changes. There are also other benefits I'll write about on Slack.

2020-12-30 16:26 UTC, alxarch requested changes
Overall the changes seem fine. Only exception is the change of signature to the `resolveTables` function.

2020-12-30 16:26 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +			zap.L().Error("unresolved log type", zap.String("name", name), zap.Error(err))
Logging an error here is *not* the correct way to handle an unresolved log type here.
The function should return the error to the caller and it should be handled there.
This introduces a global dependency and silently skips the error.
`zap.L()` usage is almost always the wrong way to handle an error.
Logging of errors should only happen 'close' to the top level of handler code.

2020-12-30 16:30 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/handler.go
> +	// NOTE: this logging is needed for alarming and dashboards!
The `oplog` manager has a horrible API that heavily relies on global variables and scatters it's logic all around the code base instead of wrapping a handler and using `defer`.

2020-12-30 16:39 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/handler.go
> +	// NOTE: this logging is needed for alarming and dashboards!
A top of my mind approach to this would be to have a `OrchestratedHandler` that can wrap types implementing `lambda.Handler`. 
```go
func OrchestrateHandler(h lambda.Handler) lambda.Handler
```
Any labels we want to put in the logger should be part of the context logger, not relevant to the orchestration.
The resulting handler acts like a *middleware* that uses `defer` to log time/mem usage, errors etc.

2020-12-30 21:11 UTC, rleighton commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +			zap.L().Error("unresolved log type", zap.String("name", name), zap.Error(err))
So, the issue is I was able to create some inconsistent data (messing in my account) and this caused everything to fail because this function failed ... debugging this was complicated by the fact that the lambda lost all logging of errors , so there were no alarms or logs.

@alxarch If we do not log here AND we do not want to fail, how do you suggest passing this info back to the caller? We do want to know about this situation but we do not want the whole system to fail. I would say an error is not the right way, since the function did not fail.

2020-12-30 21:11 UTC, rleighton commented on internal/log_analysis/datacatalog_updater/datacatalog/handler.go
> +	// NOTE: this logging is needed for alarming and dashboards!
Changing `oplog` is a task onto itself, happy to have you do it in anther PR. In the end, we want a standard way of logging at the top of the stack , including stats, etc. This was removed here and ALL logging stopped and a dashboard broke. We may have had production issues as a result but we will not know because of no logs.

2021-01-03 15:52 UTC, rleighton commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +			zap.L().Error("unresolved log type", zap.String("name", name), zap.Error(err))
@alxarch I made the function return a slice of warning errors and all callers up to the handler, where it is logged. Seems like over engineering but functionally the same so we have these properties:

 - one bad logType does not cause the whole system to collapse
 - we get paged when there is a bad logType

2021-01-04 09:40 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +			zap.L().Error("unresolved log type", zap.String("name", name), zap.Error(err))
I think having an unresolved log type when creating views/tables *is* an irrecoverable error. The system would not collapse. The views just won't get updated.

2021-01-04 09:43 UTC, alxarch commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +			zap.L().Error("unresolved log type", zap.String("name", name), zap.Error(err))
If we organize the management of log types a bit better by not relying on Glue catalog state for our system state we could avoid even having to resolve the tables multiple times. If you consider when the `resolveTables` function is used we should not have any unresolved log types at that point. It would mean something is really wrong. I would still suggest returning an error (even if using `multierror.Append` to collect all such errors) and fail the operation immediately.

2021-01-04 13:23 UTC, kostaspap commented on internal/core/logtypesapi/main/lambda.go
> +	nativeLogTypes = append(nativeLogTypes, logtypes.CollectNames(snapshotlogs.LogTypes())...)
We went to great lengths and put lots of effort to make sure we didn't have this behavior.  We didn't want these log types to be available when someone chooses to onboard a source from S3/SQS, same as we didn't want them to be available in Rules. Users have Policies for these resources.

2021-01-04 13:23 UTC, kostaspap commented on internal/log_analysis/athenaviews/athenaviews_test.go
> +select 'panther_cloudsecurity' AS databaseName,day,hour,month,NULL AS p_any_aws_account_ids,NULL AS p_any_aws_arns,NULL AS p_any_aws_instance_ids,NULL AS p_any_aws_tags,p_any_domain_names,p_any_ip_ad
Maybe `p_db_name` given that all panther generated fields use this naming format?

2021-01-05 10:00 UTC, rleighton commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
> +			zap.L().Error("unresolved log type", zap.String("name", name), zap.Error(err))
The `multierr.Append` worked but was messy. I found the clean solution, I move the logging into the resolver that is created in the `main` of the lambda.

2021-01-05 10:00 UTC, rleighton commented on internal/log_analysis/athenaviews/athenaviews_test.go
> +select 'panther_cloudsecurity' AS databaseName,day,hour,month,NULL AS p_any_aws_account_ids,NULL AS p_any_aws_arns,NULL AS p_any_aws_instance_ids,NULL AS p_any_aws_tags,p_any_domain_names,p_any_ip_ad
Excellent idea. Done.

2021-01-05 10:43 UTC, alxarch commented on internal/core/logtypesapi/main/lambda.go
> +	nativeLogTypes = append(nativeLogTypes, logtypes.CollectNames(snapshotlogs.LogTypes())...)
I assumed we only needed the snapshot resolver to be chained. Where do we require these logs to be part of the ListAvailableLogTypes endpoint?

2021-01-05 15:45 UTC, alxarch commented on internal/core/logtypesapi/main/lambda.go
> +	nativeLogTypes = append(nativeLogTypes, logtypes.CollectNames(snapshotlogs.LogTypes())...)
After talking on a call with Russ we reached the conclusion that it might be best to include it here for now so that the cloud security feature can be implemented. We will probably split the endpoints for sources and rules when we also manage to separate parsers from schemas. Rules need available schemas (including cloudsecurity) and sources need available parsers (a parser can produce results of multiple types). This will be a section in the centralized schema management RFC.

2021-01-05 15:47 UTC, rleighton commented on internal/core/logtypesapi/main/lambda.go
> +	nativeLogTypes = append(nativeLogTypes, logtypes.CollectNames(snapshotlogs.LogTypes())...)
Resolving. Can you pls approve? I have an enterprise PR that depends on this one.

2021-01-05 15:48 UTC, alxarch approved these changes
If Kostas agrees we should just include the cloudsecurity log types in the list for now so the feature can be unblocked. Otherwise we need to wait for 'harder' PRs like splitting parsers/schemas or find some other weird throwaway solution to only show them in the rules dropdon.

2021-01-05 17:15 UTC, kostaspap commented on internal/log_analysis/athenaviews/athenaviews.go
>  	// the rule match tables share the same structure as the logs with some extra columns
Should you add a. 
```
if table.DatabaseName() == pantherdb. LogProcessingDatabase
```

check here? Similar as you do in the methods above.

2021-01-05 17:26 UTC, kostaspap approved these changes

2021-01-05 17:26 UTC, kostaspap commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
>  	deployedLogTables, err := resolveTables(ctx, h.Resolver, deployedLogTypes...)
nit: This is no longer just log tables right? It also includes cloud security? Maybe rename to `deployedTables` for clarity?

2021-01-05 17:26 UTC, kostaspap commented on internal/log_analysis/datacatalog_updater/main/lambda.go
> +		zap.L().Error("cannot resolve logType", zap.String("logType", name))
Do we need this custom struct here? Why not just log the error in line 100 of internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go ?

2021-01-05 18:07 UTC, rleighton commented on internal/log_analysis/datacatalog_updater/main/lambda.go
> +		zap.L().Error("cannot resolve logType", zap.String("logType", name))
LOL! That's how I originally . Alex _hates_ logging deep in the stack and insisted I pull it up to the top.

2021-01-05 18:07 UTC, rleighton commented on internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
>  	deployedLogTables, err := resolveTables(ctx, h.Resolver, deployedLogTypes...)
Good idea.

2021-01-05 18:38 UTC, kostaspap commented on internal/log_analysis/datacatalog_updater/main/lambda.go
> +		zap.L().Error("cannot resolve logType", zap.String("logType", name))
In general I agree with the idea that we shouldn't log deep in the call stack but this seems lie over-engineering to me.

2021-01-05 18:58 UTC, rleighton commented on internal/log_analysis/datacatalog_updater/main/lambda.go
> +		zap.L().Error("cannot resolve logType", zap.String("logType", name))
There a was a long thread on that (now resolved). If a bad log type is ever put into a source then all log types from the source cannot be onboarded because we fail. Very fragile. Breaks onboarding. It happened to me doing stuff in dev but it could just as easily happen in production from a bug. If it did the customer would be stopped. This way we get alerted and the valid log types all work.

2021-01-05 20:48 UTC, merged