Cloud Security - Sources API & Snapshot Poller - Filtering and Blacklisting
panther-labs/panther pull request #2361
Opened 2021-01-07 17:29 UTC by wey-chiang

## Background

Users have no mechanism to disable a CloudSecurity source integration forcing them to either a) deal with a potentially overwhelming number of errors that provide no meaningful context or b) to delete the CloudSecurity source altogether.

These changes provide BE support for users to be able to disable a CloudSecurity source integration.

Furthermore, these changes also provide support for the following filtering and blacklisting:

- Regional Blacklisting for all individual pollers apart of the snapshot-poller
- Resource Type Filtering for all individual pollers apart of the snapshot-poller
- Regular Expression Filtering for all individual pollers apart of the snapshot-poller that use resource arns in api calls
  - Support added individually for pollers that do not use a fully-qualified resource arn in api calls

## Changes

- List your changes here in more detail

## Testing

- `mage test:ci` 
  - Note: this raised issues around web files and some `E0000` for some of the deployment `.yml` files
- Manual deployment to `us-east-1`
- Manual testing using SQS and CloudWatch

2021-01-07 23:02 UTC, nhakmiller reviewed
Thanks for the quick turn around time on this! A few comments (using the suggestions feature where I could!)

2021-01-07 23:02 UTC, nhakmiller commented on api/lambda/source/models/api.go
> +	ARNRegexFilter     string           `json:"arnRegexFilter" validate:"omitempty"`
I see you've added these to `PutIntegrationSettings`, `UpdateIntegrationSettings`, and `SourceIntegrationMetadata`. Did you update the `PutIntegrationSettings` and `UpdateIntegrationSettings` API endpoints? Not needed right now, but will be needed for eventual frontend support.

2021-01-07 23:49 UTC, austinbyers commented on deployments/cloud_security.yml
> +              Resource: !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:panther-source-api
Combine this with the resources-api invocation permission above rather than creating a new IAM policy

2021-01-07 23:49 UTC, austinbyers commented on internal/compliance/snapshot_poller/pollers/aws/configservice.go
> +	// Check if ResourceID matches the integration's regex filter
For suppressions, we only use glob-style wildcarding rather than full regexes. It seemed to be more intuitive, both for developers and customers.

Consider using glob matching, e.g. `my-dev-bucket-*` rather than a regex `my\-dev\-bucket\-.*` to be consistent with suppressions

2021-01-07 23:49 UTC, austinbyers commented on internal/compliance/snapshot_poller/pollers/aws/poll.go
> +	if scanRequest.ResourceType != nil && pollerInput.ResourceTypeFilter != nil {
The name `ResourceTypeFilter` doesn't make it clear whether you're filtering in or out. Is this the set of resources which are _ignored_? In which case maybe `ResourceTypeIgnore` or similar

2021-01-07 23:49 UTC, austinbyers commented on internal/compliance/snapshot_poller/pollers/utils/source_integration.go
> +		if time.Now().Add(-1 * time.Minute).Before(cachedIntegration.Timestamp) {
The cache time should be a constant at the top of the file for easy identification

2021-01-07 23:49 UTC, austinbyers commented on api/lambda/source/models/api.go
> +	RegionBlacklist    []string         `json:"regionBlacklist" validate:"omitempty"`
Let's use "Denylist" instead of "Blacklist" in the spirit of inclusivity. Similarly, "Allowlist" instead of "Whitelist"

See, for example: https://gitlab.com/gitlab-org/gitlab/-/issues/7554

> While the etymology of the words isn't steeped in racial undertones or history like other problematic tech word choices, there is no harm in changing them to synonyms that as just as understandable and avoid the question entirely

2021-01-08 00:22 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/aws/poll.go
> +	if scanRequest.IntegrationID != nil {
Changed it to check if it is nil and to log an error and return early.

2021-01-08 00:47 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/aws/poll.go
> +		}
Solved this in a number of places

2021-01-08 02:07 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/aws/s3_bucket.go
> +	}
We still need it in the `PollS3Buckets` logic but yeah that makes sense

2021-01-08 02:25 UTC, wey-chiang commented on api/lambda/source/models/api.go
> +	ARNRegexFilter     string           `json:"arnRegexFilter" validate:"omitempty"`
Looks like custom resources needs to be updated if we want to support these options there

2021-01-08 02:52 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/aws/poll.go
> +	if scanRequest.ResourceType != nil && pollerInput.ResourceTypeFilter != nil {
I'll rename to `ResourceTypeBlacklist` to be consistent with `RegionBlacklist`

2021-01-08 03:10 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/utils/source_integration.go
> +		if time.Now().Add(-1 * time.Minute).Before(cachedIntegration.Timestamp) {
Added as a const

2021-01-08 03:15 UTC, wey-chiang commented on api/lambda/source/models/api.go
> +	RegionBlacklist    []string         `json:"regionBlacklist" validate:"omitempty"`
💯

2021-01-08 16:25 UTC, nhakmiller reviewed
A couple nitpicks, and one big issue I missed from last time somehow. Luckily I think there is a fairly straightforward fix that is still aligned with your idea on region filtering

2021-01-08 16:25 UTC, nhakmiller commented on internal/core/custom_resources/resources/self_registration.go
> +				ResourceRegexDenylist: properties.ResourceRegexDenylist,
These fields don't mean anything for log processing sources today, lets not put them in for now.

2021-01-08 16:25 UTC, nhakmiller commented on internal/core/custom_resources/resources/self_registration.go
> +			ResourceRegexDenylist: source.ResourceRegexDenylist,
Same comment as above, these new fields only have meaning for scanning/cloud security sources so lets only reference them there. It's kind of weird because we use the same model for all source integrations, but we only populate certain fields based on whats actually used by that integration.

2021-01-08 16:25 UTC, nhakmiller commented on internal/core/source_api/api/put_integration.go
> +		ResourceRegexDenylist: input.ResourceRegexDenylist,
I would move these down below into the `case models.IntegrationTypeAWSScan` block for the same reasons discussed above.

2021-01-08 16:25 UTC, nhakmiller commented on internal/core/source_api/api/update_integration.go
> +	item.ResourceRegexDenylist = input.ResourceRegexDenylist
Move to `case models.IntegrationTypeAWSScan:` block.

2021-01-08 16:25 UTC, nhakmiller commented on internal/core/source_api/api/utils.go
> +	integration.ResourceRegexDenylist = item.ResourceRegexDenylist
Move to `case models.IntegrationTypeAWSScan:` block.

2021-01-08 16:25 UTC, nhakmiller commented on internal/compliance/snapshot_poller/pollers/aws/clients.go
> +	}
Don't know why I missed this on the last pass, but I don't think this works. I believe this will cause a panic. `getClient` is called in the individual resource pollers (and the group ones, but those ones already get region filtered so it's a non-issue) and if no error is returned then we assert that the client is of the type we expect. I believe assert `nil` is some interface will panic. See this example usage:

```
	client, err := getClient(pollerResourceInput, ConfigServiceClientFunc, "configservice", region)
	if err != nil {
		return nil, err
	}
	return client.(configserviceiface.ConfigServiceAPI), nil
```

In order for this to work, you would need to update each `getXYZServiceClient` function to know how to handle a `nil, nil` response, and you would have to update each `PollXYZService` function to know how to handle not getting a client back. 

If I'm correct, you can get this behavior to happen by creating a source with a region blacklist and then initiating a single resource scan for a resource in that region.

The two best options in my opinion are:

- Have the `getClient` return a custom error instead of `nil, nil`, let the `getXYZServiceClient` pass that error up (no changes), let each `PollXYZService` pass that error up (no changes), then catch that error in `singleResourceScan` in `poll.go`. We already handle rate limit errors as a special case, this logic would be a cousin to the rate limit logic. Something like `if err == customPantherScannerErrorRegionDenied { zap.L().Info("Skipping denied region in single resource scan"); return nil, nil }`.
- Go with our original plan and add a new helper function that determines the region of the resource based on resource ID & type, and applies region deny listing before entering the `PollXYZService` functions

Of the two, the first seems easier & more robust.

2021-01-09 06:33 UTC, nhakmiller approved these changes
LGTM! I think this is actually a really clean solution for the region & resource filtering, nice job.

2021-01-11 09:18 UTC, kostaspap requested changes
The bulk of the logic is added in the snapshot-pollers package. However, it is the `aws_event_processor` that sends notifications to the snapshot pollers to do the polling. 
Shouldn't the ignore logic be in the `aws_event_processor` package? @nhakmiller

2021-01-11 09:18 UTC, kostaspap commented on internal/compliance/snapshot_poller/pollers/aws/poll.go
> +		zap.L().Error("got a malformed scan request - no integration id", zap.Any("scan request", scanRequest))
Why log error here? Why not return error?

2021-01-11 09:18 UTC, kostaspap commented on internal/compliance/snapshot_poller/pollers/aws/poll.go
> +		zap.L().Warn("failed to retrieve integration from source api")
Why log a warning? Why not return an error?

2021-01-11 09:18 UTC, kostaspap commented on api/lambda/source/models/api.go
> +	ResourceRegexDenylist []string         `json:"resourceRegexDenylist" validate:"omitempty"`
What is the regex supposed to match against? ARNs? Names?...?

2021-01-11 09:18 UTC, kostaspap commented on internal/core/source_api/ddb/items.go
> +	SourceEnabled         *bool    `json:"sourceEnabled" validate:"omitempty"`
Why is this a `*bool` and not `bool`?

2021-01-11 09:18 UTC, kostaspap commented on internal/compliance/snapshot_poller/pollers/utils/source_integration.go
> +		matcher, err := regexp.Compile(regex)
This method should be removed from here. `utils` is a bad name for a package in Go. In Go, packages are namespaces. 

1. This check should be removed. Instead, you should create a custom validator for the properties inside `ResourcePollerInput.ResourceRegexDenylist. See an example here of custom validators https://github.com/panther-labs/panther/blob/master/api/lambda/source/models/validator.go. 
2. This method should better be exposed as a function of `ResourcePollerInput`. See relevant comment above.

2021-01-11 09:18 UTC, kostaspap commented on api/lambda/source/models/integration.go
> +	SourceEnabled         *bool    `json:"sourceEnabled,omitempty"`
1. `Source` prefix is redundant, just `Enabled` should be enough. 
2. It seems that this should be just `bool`
3. Is the idea here that users can enable/disable specific sources? Do we really need this, can't the users just delete the integration?

2021-01-11 09:18 UTC, kostaspap commented on internal/compliance/snapshot_poller/pollers/aws/guardduty_detector.go
> +		matched, err := utils.MatchRegexDenylist(pollerInput.ResourceRegexDenylist, *detectorID)
In other places the `ResourceRegexDenylist` is matched against ARNs. Here it is matched against a detectorID. Is the detectorID an arn?

2021-01-11 14:29 UTC, nhakmiller commented
> The bulk of the logic is added in the snapshot-pollers package. However, it is the `aws_event_processor` that sends notifications to the snapshot pollers to do the polling.
> Shouldn't the ignore logic be in the `aws_event_processor` package? @nhakmiller

If we did we would just have to duplicate it here to handle daily scans. It's best to have the logic here so it is centralized for all types of scans.

2021-01-11 14:31 UTC, nhakmiller commented on internal/compliance/snapshot_poller/pollers/aws/clients.go
> +	}
There are two ways to do scans:

- Individual resource scans
- Region wide resource type scans

Region wide scans we can filter before we get here, because we know what region is being requested to be scanned.

For individual resource scans we need this because different resource types sometimes have custom logic to determine what region they are in (IAM resources, s3 resources, guard duty/config resources).

2021-01-11 14:33 UTC, nhakmiller commented on internal/compliance/snapshot_scheduler/scheduler/schedule.go
> +func GetEnabledIntegrations() (integrations []*models.SourceIntegration, err error) {
So we can import it & use it in the `panther-snapshot-poller`. This is the new way we're doing APIs, instead of invoking other lambda functions we just import them and run the code.

2021-01-11 14:34 UTC, nhakmiller commented on api/lambda/source/models/api.go
> +	ResourceRegexDenylist []string         `json:"resourceRegexDenylist" validate:"omitempty"`
Panther resource IDs. If you think  it makes it more clear it could maybe be `ResourceIDRegexDenyList`.

2021-01-11 14:36 UTC, nhakmiller commented on internal/compliance/snapshot_poller/pollers/utils/source_integration.go
> +		matcher, err := regexp.Compile(regex)
I think a customer validator is overkill for this one thing. Maybe the snapshot-poller needs a validator in general (since right now we're just validating all the inputs by checking them in `if` statements) but I don't think that's in scope for this PR. If you'd like, I can open an issue and assign it to myself for this task.

2021-01-11 14:39 UTC, nhakmiller commented on api/lambda/source/models/integration.go
> +	SourceEnabled         *bool    `json:"sourceEnabled,omitempty"`
Re point 3: we've specifically had requests from users for being able to disable problematic sources without deleting them. Sure they could just delete the source & re-add when they're ready to start scanning again, but this has two downsides:

1. They have to step through the source onboarding wizard again (including looking up the account ID since most people don't memorize  that)
2. When you delete a source, all the resources from that source show up with "unable to find source". By disabling the source it means the resources would still be there in Panther just not being scanned

In general I agree with you it wouldn't be needed, but since we're already in here adding this much more complex logic adding this relatively simple part is a nice quality of life improvement for customers.

2021-01-11 14:42 UTC, nhakmiller commented on internal/compliance/snapshot_poller/pollers/aws/guardduty_detector.go
> +		matched, err := utils.MatchRegexDenylist(pollerInput.ResourceRegexDenylist, *detectorID)
Ah good catch, @wey-chiang you should compare to `detectorSnapshot.ID` instead of `detectorID`, as the `detectorSnapshot.ID` is the panther resource ID (which includes the type & region) and is what users would see in the UI under ID.

2021-01-11 14:44 UTC, nhakmiller commented on internal/compliance/snapshot_poller/pollers/aws/poll.go
> +		zap.L().Error("got a malformed scan request - no integration id", zap.Any("scan request", scanRequest))
Returned errors get retried, if the `IntegrationID` in the request is `nil` we cannot ever succeed at the scan so retrying will just cause more errors.

2021-01-11 14:45 UTC, kostaspap commented on api/lambda/source/models/integration.go
> +	SourceEnabled         *bool    `json:"sourceEnabled,omitempty"`
Thanks @nhakmiller , makes sense.

2021-01-11 14:46 UTC, nhakmiller commented on internal/compliance/snapshot_poller/pollers/aws/poll.go
> +		zap.L().Warn("failed to retrieve integration from source api")
Yeah I think returning an error here is probably better, most likely case this would happen:

1. Transient network error meaning communication with the `source-api` is bad
2. The user deleted the source

The second case might be a bit annoying to see a bunch of errors for, but we would also see a bunch of errors if we tried to scan and they had deleted the audit role (and presumably if they delete the source they would prefer not  to have a bunch of inflight messages continue scanning).

2021-01-11 14:49 UTC, kostaspap commented on internal/compliance/snapshot_poller/pollers/utils/source_integration.go
> +		matcher, err := regexp.Compile(regex)
> I think a customer validator is overkill for this one thing. Maybe the snapshot-poller needs a validator in general (since right now we're just validating all the inputs by checking them in `if` statements) but I don't think that's in scope for this PR. If you'd like, I can open an issue and assign it to myself for this task.

Yeah, I see why maybe that's a bit overkill. What about adding a `ResourcePollerInput.CompileRegex() error` method that tries to compile the provided regexes and populates and internal slice of the compiled regexes? This could be invoked towards the entry point of the code. 
That way, the code that tries to match the regexes against the ARNs/IDs doesn't have to deal with error handling - it will just used the already compiled regexes.

2021-01-11 14:55 UTC, kostaspap commented
> > The bulk of the logic is added in the snapshot-pollers package. However, it is the `aws_event_processor` that sends notifications to the snapshot pollers to do the polling.
> > Shouldn't the ignore logic be in the `aws_event_processor` package? @nhakmiller
> 
> If we did we would just have to duplicate it here to handle daily scans. It's best to have the logic here so it is centralized for all types of scans.

Ah right, yeah, makes sense.

2021-01-11 14:59 UTC, kostaspap commented on internal/compliance/snapshot_poller/pollers/utils/source_integration.go
> +}
So the snapshot-poller is invoked by `aws-event-processor` and by `snapshot-scheduler`. Both of those Lambdas reach to the sources-api to retrieve SourceIntegrationMetadata. 
Seems they could be passing the blacklist information to the `snapshot-poller` payload, instead of the snapshot poller having to query the sources-api by itself again? I think it could simplify the code a bit (this method + the cache could be removed) and will also reduce the overall calls we make to the sources-api.

2021-01-11 15:06 UTC, nhakmiller commented on internal/compliance/snapshot_poller/pollers/utils/source_integration.go
> +		matcher, err := regexp.Compile(regex)
Yeah I think that's good, also when scanning several hundred resources just compiling the regex one time then trying to match it 100 times is probably much preferred than compiling & matching 100 times.

2021-01-11 15:09 UTC, nhakmiller commented on internal/compliance/snapshot_poller/pollers/utils/source_integration.go
> +}
Yeah fair enough, the `aws-event-processor` and `snapshot-scheduler` can pass the ignore list information along. Then we also want to change our self re-queue method to re-queue the ignore list information as well.

2021-01-11 15:15 UTC, nhakmiller commented
@kostaspap thanks for the thorough review! We were hoping to have this in for 1.15 but seems we just missed it, I'm hoping we can do a `sync-to-release` ideally today so how would you say about this, we:

1. Address the struct formatting nitpicks (about putting similar fields next to each other)
2. Address the regex compile one time in a function thing
3. Update so that the blacklist information is passed through by the snapshot-scheduler & aws-event-processor functions instead of being looked up by the snapshot-poller (since both these functions already make the list-integrations API call)
4. Add some basic unit tests around blacklisting

If these four things were done today, would you be ok with approving this change? @wey-chiang, I think 1, 2 and 4 should be pretty straightforward and number 3 should be accomplishable today unless there are any unforeseen issues. Let me know if you run into any issues.

2021-01-11 15:18 UTC, kostaspap commented
> @kostaspap thanks for the thorough review! We were hoping to have this in for 1.15 but seems we just missed it, I'm hoping we can do a `sync-to-release` ideally today so how would you say about this, we:
> 
> 1. Address the struct formatting nitpicks (about putting similar fields next to each other)
> 2. Address the regex compile one time in a function thing
> 3. Update so that the blacklist information is passed through by the snapshot-scheduler & aws-event-processor functions instead of being looked up by the snapshot-poller (since both these functions already make the list-integrations API call)
> 4. Add some basic unit tests around blacklisting
> 
> If these four things were done today, would you be ok with approving this change? @wey-chiang, I think 1, 2 and 4 should be pretty straightforward and number 3 should be accomplishable today unless there are any unforeseen issues. Let me know if you run into any issues.

I see, yeah that's sounds good! I will give a pre-approval now so you can address and merge on your own time. #4 is not super urgent if this has been tested E2E already, just good to have in general so don't block the merge just because of it, I imagine it can be addressed later.

2021-01-11 15:19 UTC, kostaspap approved these changes

2021-01-11 15:20 UTC, nhakmiller commented
> I see, yeah that's sounds good! I will give a pre-approval now so you can address and merge on your own time. #4 is not super urgent if this has been tested E2E already, just good to have in general so don't block the merge just because of it, I imagine it can be addressed later.

Thanks! We've done some E2E testing, but a think at least one round of basic unit tests will help keep things steady (and give us a base to grow more unit tests onto later if need be).

2021-01-11 17:14 UTC, wey-chiang commented on api/lambda/source/models/api.go
> +	ResourceRegexDenylist []string         `json:"resourceRegexDenylist" validate:"omitempty"`
Originally, I was using Blacklist which conveyed the intended meaning -- over the course of this PR that has changed; in light of the naming convention we currently use, I think `*Ignore*` makes way more sense, intuitively.

2021-01-11 19:05 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/aws/clients.go
> +	}
There is also the case of non-arn based scans, a good example of this is the `s3_bucket.go`

There, because we have to retrieve the bucket region, we do the region filtering in the for loop iterating through all the buckets for the `PollS3Buckets`

2021-01-11 19:08 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/aws/configservice.go
> +		}
Added a check to both the `PollConfigService` and `PollConfigServices` to handle the `nil` case

2021-01-11 19:12 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/aws/eks_cluster.go
> +	}
@kostaspap 
I'm confused how the `ShouldIgnoreArn` function proposed is any different from the `MatchRegexIgnoreList`

2021-01-11 19:27 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/aws/poll.go
> +		zap.L().Error("got a malformed scan request - no integration id", zap.Any("scan request", scanRequest))
Will add a comment for clarity

2021-01-11 19:38 UTC, wey-chiang commented on internal/core/source_api/ddb/items.go
> +	SourceEnabled         *bool    `json:"sourceEnabled" validate:"omitempty"`
How so? We want to check to ensure that `SourceEnabled` is nil if the user has not specified any option (either enable or disable)
Since `bool` will default to `false`, unless we were to include the enable source option in the source onboarding, this would automatically make all newly created sources as disabled and anytime the integration is updated without this specified, it will also be disabled.

2021-01-11 22:10 UTC, wey-chiang commented on api/lambda/source/models/integration.go
> +	SourceEnabled         *bool    `json:"sourceEnabled,omitempty"`
Renamed `SourceEnabled` to `Enabled`

I am still unsure as to the difference between `bool` and `*bool` here

2021-01-12 01:55 UTC, nhakmiller approved these changes
Mostly some small comments, overall looks good.

2021-01-12 01:55 UTC, nhakmiller commented on internal/compliance/snapshot_poller/models/aws/types.go
> +	return nil
Instead of doing this, you can make the list with a capacity of 0 and just append entries:

```suggestion
	r.CompiledRegexIgnoreList = make([]*regexp.Regexp, 0, len(r.ResourceRegexIgnoreList))

	for _, glob := range r.ResourceRegexIgnoreList {
		if glob == "" {
			continue
		}
		// First,  escape any regex special characters
		escaped := regexp.QuoteMeta(glob)

		// Wildcards in the original pattern are now escaped literals - convert back
		// NOTE: currently no way for user to specify a glob that would match a literal '*'
		regex := "^" + strings.ReplaceAll(escaped, `\*`, `.*`) + "$"
		compiledGlob, err := regexp.Compile(regex)
		if err != nil {
			// We are building the regex, so it should always be valid
			zap.L().Error("invalid regex",
				zap.String("originalPattern", glob),
				zap.String("transformedRegex", regex),
				zap.Error(err),
			)
			return err
		}
		r.CompiledRegexIgnoreList = append(r.CompiledRegexIgnoreList, compiledGlob)
	}
	return nil
```

Then you won't have `nil`/empty entries in the list, which simplifies the work a bit down below (separate suggestion since apparently there's a max size on suggestions.

2021-01-12 01:55 UTC, nhakmiller commented on internal/compliance/snapshot_poller/models/aws/types.go
> +	}
With the above suggestion, you don't have to worry about `nil` entries.

```suggestion
	for _, compiledRegex := range r.CompiledRegexIgnoreList {
		if compiledRegex.MatchString(resourceID) {
			return true, nil
		}
	}
```

2021-01-12 01:55 UTC, nhakmiller commented on internal/compliance/snapshot_poller/pollers/aws/configservice.go
> +		}
These nested `if` statements are now redundant (I'm assuming this is refactoring leftovers)
```suggestion
		if ignore, err := pollerInput.ShouldIgnoreResource(*recorder.Name); ignore || err != nil {
			return nil, err
		}
```

2021-01-12 01:55 UTC, nhakmiller commented on internal/compliance/snapshot_poller/pollers/aws/eks_cluster.go
> +		}
As above:

```suggestion
		if ignore, err := pollerInput.ShouldIgnoreResource(*details.Arn); ignore || err != nil {
			return nil, err
		}
```

2021-01-12 01:55 UTC, nhakmiller commented on internal/compliance/snapshot_poller/pollers/aws/guardduty_detector.go
> +		}
```suggestion
		if ignore, err := pollerInput.ShouldIgnoreResource(*detectorSnapshot.ID); ignore || err != nil {
			return nil, err
		}
```

2021-01-12 01:55 UTC, nhakmiller commented on internal/compliance/snapshot_poller/pollers/aws/password_policy.go
> +	}
```suggestion
	if ignore, err := pollerInput.ShouldIgnoreResource(resourceID); ignore || err != nil {
		return nil, nil, err
	}
```

2021-01-12 01:55 UTC, nhakmiller commented on internal/compliance/snapshot_poller/pollers/aws/poll.go
> +		}
```suggestion
		if ignore, err := pollerInput.ShouldIgnoreResource(*scanRequest.ResourceID); ignore || err != nil {
			return nil, err
		}
```

2021-01-12 01:55 UTC, nhakmiller commented on internal/compliance/snapshot_poller/pollers/aws/s3_bucket.go
> +		}
```suggestion
		if ignore, err := pollerInput.ShouldIgnoreResource(*bucket.Name); ignore || err != nil {
			if err != nil {
				return nil, nil, err
			}
			continue
		}
```

I think we can drop the `if ignore`, we know either `ignore` or `err != nil` is true, and since we didn't enter the above block we know it must be `ignore`.

2021-01-12 01:55 UTC, nhakmiller commented on internal/core/custom_resources/resources/self_registration.go
> +	ResourceRegexIgnoreList []string `json:","`
This is just for self-registration during the initial setup, I think we can just remove these fields.

2021-01-12 01:55 UTC, nhakmiller commented on internal/core/custom_resources/resources/self_registration.go
> +				ResourceRegexIgnoreList: properties.ResourceRegexIgnoreList,
You can just leave these not set/default values, they won't be specified.

2021-01-12 04:41 UTC, merged

2021-01-12 09:17 UTC, kostaspap commented on internal/core/source_api/ddb/items.go
> +	SourceEnabled         *bool    `json:"sourceEnabled" validate:"omitempty"`
Well a source can be either enabled or disabled, there is no 3rd option. `nil` doesn't give any value. You can make the FE set this to true or false depending on what you want to be the default.
Putting a *bool here just makes it more painful to handle this property throughout the code since now we need to be careful not to make nil pointer dereference @wey-chiang

2021-01-12 09:17 UTC, kostaspap commented on api/lambda/source/models/integration.go
> +	SourceEnabled         *bool    `json:"sourceEnabled,omitempty"`
> Renamed `SourceEnabled` to `Enabled`
> 
> I am still unsure as to the difference between `bool` and `*bool` here

@wey-chiang see my comment above.

2021-01-12 09:28 UTC, kostaspap commented on internal/compliance/snapshot_poller/models/aws/types.go
> +			)
You should't log errors so deep in the call stack, please remove. Let the caller decide if they want to log the error or not.

2021-01-12 09:28 UTC, kostaspap commented on internal/compliance/snapshot_poller/models/aws/types.go
> +	}
You can just remove this check. This would greatly simplify the work of the callers of `ShouldIgnoreResource` since they now don't have to handle the error case. 
You could make the call panic if `CompileRegex` hasn't been invoked before `ShouldIgnoreResource` is called.

2021-01-12 09:28 UTC, kostaspap commented on internal/compliance/snapshot_poller/pollers/aws/configservice.go
> +	}
I made this comment in my previous review: 
If you replace `pollerInput *awsmodels.ResourcePollerInput` with `pollerInput awsmodels.ResourcePollerInput` in the call function and make sure that the pollerInput doesn't throw errors, this could just be : 
```
if pollerInput.ShouldIgnoreResource(*recorder.Name){
 return nil
}
```

2021-01-12 09:28 UTC, kostaspap commented on internal/compliance/snapshot_poller/pollers/aws/password_policy.go
> +	if ignore, err := pollerInput.ShouldIgnoreResource(resourceID); ignore || err != nil {
pollerInput could be `nil` and here you will get an exception. I would recommend replacing `PollPasswordPolicy(pollerInput *awsmodels.ResourcePollerInput)` with `PollPasswordPolicy(pollerInput awsmodels.ResourcePollerInput)`. I don't see in the codebase any scenario where the ResourcePollerInput would/should be nil. Also see: https://github.com/golang/go/wiki/CodeReviewComments#pass-values

2021-01-12 09:29 UTC, kostaspap commented on internal/compliance/snapshot_poller/pollers/aws/configservice.go
> +	}
Also see: https://github.com/golang/go/wiki/CodeReviewComments#pass-values

2021-01-12 09:34 UTC, kostaspap commented on internal/compliance/snapshot_poller/models/aws/types.go
> +func (r *ResourcePollerInput) CompileRegex() error {
Searching this function in this PR I see that it is never called? Can you verify?

2021-01-12 09:54 UTC, kostaspap commented
Thanks @wey-chiang, you addressed most of my comments. I've put some new ones, a few of them are style-related but there is also a potential nil-pointer dereference and another issue where we keep compiling the regexes for every new resource scan.

2021-01-14 16:40 UTC, wey-chiang commented on internal/compliance/snapshot_poller/models/aws/types.go
> +func (r *ResourcePollerInput) CompileRegex() error {
It is called in the ShouldIgnoreResource func

2021-01-19 16:59 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/aws/configservice.go
> +	}
Removed the check since it should never be nil by the logic in the caller.

The `pollerInput *awsmodels.ResourcePollerInput` is used in a number of other files -- particularly in the `get*Client` functions. 

I am in favor of keeping this the way it is (besides removing the check) to maintain consistency with similar code

2021-01-19 17:02 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/aws/password_policy.go
> +	if ignore, err := pollerInput.ShouldIgnoreResource(resourceID); ignore || err != nil {
See above comment

2021-01-19 17:07 UTC, wey-chiang commented on internal/compliance/snapshot_poller/models/aws/types.go
> +func (r *ResourcePollerInput) CompileRegex() error {
I've moved it over to the `poll.go:Poll` function, right after the initialize `pollerResourceInput`

2021-01-22 22:41 UTC, wey-chiang commented on internal/core/source_api/api/put_integration.go
> +		metadata.ResourceRegexIgnoreList = input.ResourceRegexIgnoreList
👎

2021-01-22 22:42 UTC, wey-chiang commented on internal/core/source_api/api/put_integration.go
> +		metadata.ResourceRegexIgnoreList = input.ResourceRegexIgnoreList
👎

2021-01-23 02:20 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/aws/poll.go
>  			Entries: []*pollermodels.ScanEntry{
👎

2021-01-23 02:22 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/aws/poll.go
>  			Entries: []*pollermodels.ScanEntry{
:-1-
```
			Entries: []*pollermodels.ScanEntry{
				{
					AWSAccountID:  scanRequest.AWSAccountID,
					IntegrationID: scanRequest.IntegrationID,
					Region:        region,
					ResourceType:  scanRequest.ResourceType,
				},
```
This should include the options passed in by `ScanEntry`