Add CrowdStrike UserIdentity & GroupIdentity parsers
panther-labs/panther pull request #2458
Opened 2021-01-20 12:07 UTC by georgepsarakis

## Background

Why are you making this change? Please provide a reference to any related issues and PRs

## Changes

- List your changes here in more detail

## Testing

- How did you test your change?

2021-01-25 07:52 UTC, alxarch requested changes
I think trace_id is not used correctly in `CommonIdentityFields`
Tests should be in YAML form so we can export them to the managed schemas repository.

2021-01-25 07:52 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity.go
> +	AuthenticationID pantherlog.Uint64 `json:"AuthenticationId" validate:"required" description:"Values: INVALID_LUID (0), NETWORK_SERVICE (996), LOCAL_SERVICE (997), SYSTEM (999), RESERVED_LUID_MAX (10
See comments in the other PR about use of unsigned integers. Uint64 is especially problematic if the value can indeed be too high since we can only store up to Int64 numbers in Athena.

2021-01-25 07:52 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity_test.go
> +func TestUserIdentityParser(t *testing.T) {
Tests should be in YAML form for compatibility with exporting them to a separate repo.

2021-01-25 07:52 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity.go
> +	UserName              pantherlog.String `json:"UserName"`
Maybe add `panther:"username"`?

2021-01-25 07:52 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity.go
> +	UserSid          pantherlog.String `json:"UserSid" panther:"trace_id" validate:"required" description:"The User Security Identifier (UserSID) of the user who executed the command. A UserSID uniquely
I am not sure this should be `trace_id`. `username` seems more appropriate. The `trace_id` tag should be used to 'group' together events that correspond to the same 'master' event (i.e. an HTTP request id). In this case it is my understanding that `UserSid` never changes for a user.

2021-01-25 08:19 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/crowdstrikelogs.go
> +	AID            null.String `json:"aid" panther:"trace_id" description:"The sensor ID. This value is unique to each installation of a Falcon sensor. When a sensor is updated or reinstalled, the host
I don't think this should be a `trace_id` (similar reason to what @alxarch mentions below)

2021-01-25 08:19 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity.go
> +	SessionID             pantherlog.Uint32 `json:"SessionId"`
This seems it could be `trace_id`

2021-01-25 08:53 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity.go
> +	UserName              pantherlog.String `json:"UserName"`
Missed that, wasn't aware of this scanner, thanks!

2021-01-25 08:55 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity_test.go
> +func TestUserIdentityParser(t *testing.T) {
You mean use the log testing automation as described in the [documentation](https://docs.runpanther.io/v/master/development/writing-parsers#step-0-writing-a-test)?

2021-01-25 08:56 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/crowdstrikelogs.go
> +	AID            null.String `json:"aid" panther:"trace_id" description:"The sensor ID. This value is unique to each installation of a Falcon sensor. When a sensor is updated or reinstalled, the host
I see, will fix it, thanks.

2021-01-25 09:01 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity_test.go
> +func TestUserIdentityParser(t *testing.T) {
Yes, our end goal is to define all schemas and parsers in YAML at some point and manage them in `panther-labs/log-analysis` repo.
We call this feature 'Managed Schemas'. It will decouple panther releases from schema updates. To be able to run tests we will only have the YAML form of tests available. I am currently working on a `mage` command that exports the 'native' parsers and schemas to be moved to the repository. For some releases schemas will be living in both repos until we can express all parsers as YAML but that is a different issue.

2021-01-25 09:15 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity_test.go
> +func TestUserIdentityParser(t *testing.T) {
Sure, I just followed the same pattern used for other Crowdstrike parsers (thought that may be part of a larger rewrite process). I'll keep in mind that from now onwards we should use the YAML-configured test cases, thanks 😉  !

2021-01-25 14:12 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity.go
> +	UserSid          pantherlog.String `json:"UserSid" panther:"trace_id" validate:"required" description:"The User Security Identifier (UserSID) of the user who executed the command. A UserSID uniquely
Good observation, will fix!

2021-01-25 15:05 UTC, georgepsarakis commented
All comments addressed in e949b1bac189280657de455a7b03eb582abda545.

2021-01-25 16:10 UTC, kostaspap approved these changes
Nice work! Just two comments regarding data types, everything else looks good overall

2021-01-25 16:10 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity.go
> +	UserIsAdmin           pantherlog.Int32  `json:"UserIsAdmin"`
Should this be a boolean?

2021-01-25 16:10 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity.go
> +	AuthenticationUUIDAsString pantherlog.String `json:"AuthenticationUuidAsString"`
As they really both strings ^^

2021-01-26 08:00 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity.go
> +	UserIsAdmin           pantherlog.Int32  `json:"UserIsAdmin"`
Judging by the name, I would say yes. The documentation specifies the data type as `uint32`, so I thought to leave some margin for unexpected values. As far as I understand there is not much flexibility in modifying AWS Glue table schemas, so once the field is defined as boolean, it may be hard to change later. I can go ahead and change it though, if you think it is fine.

2021-01-26 08:23 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity.go
> +	AuthenticationUUIDAsString pantherlog.String `json:"AuthenticationUuidAsString"`
For `AuthenticationUUID` the documentation mentions `bytes` as the data type. I think it is a string type in JSON, but a different representation:

```python
>>> import uuid
>>> u = uuid.uuid4()
>>> u.bytes
b',O\xf5\xc0\xea\x7fA\xeb\xa2\x8e\x9fI\x87+\x8c0'
>>> str(u)
'2c4ff5c0-ea7f-41eb-a28e-9f49872b8c30'
```

2021-01-26 08:50 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity.go
> +	UserIsAdmin           pantherlog.Int32  `json:"UserIsAdmin"`
> The documentation specifies the data type as uint32, so I thought to leave some margin for unexpected values. 

I agree with that approach, fine to leave as is!

2021-01-26 08:51 UTC, kostaspap approved these changes

2021-01-26 16:03 UTC, alxarch approved these changes
LGTM
I checked on enterprise and there doesn't seem to be anything special you need to do so that Crowdstrike sources return the correct RequiredLogTypes

2021-01-27 09:14 UTC, georgepsarakis commented
Thanks @alxarch !

2021-02-01 09:51 UTC, merged