Verify Policy ResourceType entries before policy create or update
panther-labs/panther pull request #2468
Opened 2021-01-20 20:12 UTC by tatehanawalt

## Background

Policy (cloud-security) create and update calls allow invalid ResourceType entries. 

This change adds a validation check for the policy ResourceType values when a policy is created or updated from bulk uploads and direct lambda invocation apis.

#### Note - This change does not check log types for log analysis. This pr only reflects the validity checks for policy ResourceTypes.

This changes uses static resources (not literally static but the list is a set of strings that we never modify) so this check is much simpler.

This pr relates to (but it does not close) [Validate Log and Resource types #619](https://github.com/panther-labs/panther/issues/619#issuecomment-763845129)

Our discussions on this pr will influence the implementation of the LogTypes portion of the issue.

## Changes

Currently the resource types are a constant set.

I have defined a method which accepts a string slice of ResourceType strings and returns an error. The error will indicate the first element of the set parameter which is not a valid ResourceType.

I chose to call a method for future portability. We could just iterate each time we need to but the method allows us to add the ability to dynamically generate the set of valid possible ResourceTypes.

- List your changes here in more detail

## Testing

Direct lambda invocations
Bulk .zip upload

2021-01-20 20:26 UTC, austinbyers requested changes
Be sure to run the associated integration tests and make sure they pass. Then, add an additional integration test (or update an existing one) to test for this case

2021-01-20 20:26 UTC, austinbyers commented on internal/core/analysis_api/handlers/bulk_upload.go
> +		break
You don't need `break`s in Go switch statements. This one can be removed; the one on the next line is fine because there's no other code

2021-01-20 20:26 UTC, austinbyers commented on internal/core/analysis_api/handlers/create_update_policy.go
> +var ValidResourceTypes = []string{"AWS.ACM.Certificate", "AWS.CloudFormation.Stack", "AWS.CloudTrail", "AWS.CloudTrail.Meta", "AWS.CloudWatch.LogGroup", "AWS.Config.Recorder", "AWS.Config.Recorder.Me
This should be a map for more efficient inclusion testing:

```go
var ValidResourceTypes = map[string]struct{}{
    "AWS.ACM.Certificate":      struct{}{},
    "AWS.CloudFormation.Stack": struct{}{},
    // ...
}
```

The `map[string]struct{}` is marginally more efficient than a `map[string]bool`, it's a common Go idiom for a "stringset". 

Then, to test inclusion:

```go
if _, exists := ValidResourceTypes[type]; exists {
    // found a type match
}
```

2021-01-20 20:26 UTC, austinbyers commented on internal/core/analysis_api/handlers/create_update_policy.go
> +}
This function will not be needed once you convert to a map above

2021-01-20 20:28 UTC, austinbyers commented
Tagging @nhakmiller as the owner of this service - do you see any other easy solution besides just hardcoding these resource types? I figure they don't change very often, we can add some autogeneration code later

2021-01-20 20:30 UTC, austinbyers commented on internal/core/analysis_api/handlers/create_update_policy.go
> +var ValidResourceTypes = []string{"AWS.ACM.Certificate", "AWS.CloudFormation.Stack", "AWS.CloudTrail", "AWS.CloudTrail.Meta", "AWS.CloudWatch.LogGroup", "AWS.Config.Recorder", "AWS.Config.Recorder.Me
Can you add a comment here and in the web resource constants file that point to each other? E.g.

```go
// These constants are also defined in web/src/....
// Be sure that any changes to this list are reflected in the web source and vice versa
```

2021-01-20 20:41 UTC, tatehanawalt commented on internal/core/analysis_api/handlers/bulk_upload.go
> +		break
fixed - thank you

2021-01-20 20:53 UTC, nhakmiller commented
> Tagging @nhakmiller as the owner of cloud security - do you see any other easy solution besides just hardcoding these resource types? I figure they don't change very often, we can add some autogeneration code later

Hmm it's not perfect, but `internal/compliance/snapshot_poller/pollers/aws/poll.go` has a map called `ServicePollers` that has a key for every resource type we support. That list has to be manually updated whenever a new resource type is added, but if it's not updated scans of that resource type will crash hard so it usually doesn't get missed. So you could reference that map directly, or add some function to the snapshot-pollers that lets you reference it more cleanly like `ResourceTypeExists` or something that does the lookup. Problem is then you have to import the poller code, which is massive because it depends on a lot of different AWS service SDKs.

Alternatively as you say we can auto generate it. It would be based off the files located in `internal/compliance/snapshot_poller/models/aws/`.

Those two ways were be more guaranteed to be correct, but also way harder than just hardcoding. They do change fairly infrequently, but if we enforce it like this we probably want to add a comment in `poll.go` or something that says "oh yeah also update `internal/core/analysis_api/handlers/create_update_policy.go` whenever a new resource type is added".

2021-01-20 21:29 UTC, austinbyers commented
> Problem is then you have to import the poller code, which is massive because it depends on a lot of different AWS service SDKs.

Yeah - the snapshot-poller is currently 9.7 MB compared to analysis-api 5.3 MB. Doubling the size is probably not ideal.

Another idea I hadn't initially considered: the snapshot-poller could respond to an API request for "listResourceTypes." That way, the source of truth stays in the snapshot poller, and we don't have to import its codebase. But then every policy update requires another cross-lambda api call (in addition to the policy-engine validation)

----

Since the constants in the web source are already hardcoded, I'd vote for just taking the easy path for now and hardcoding it here as well. Not worth our time to optimize this just yet. Like you say, let's just add comments everywhere we need these  so we remember to update all of the files together.

We could even add a CI check for it - make sure the web constants, the analysis-api validation, and the snapshot poller map all reference the same resource types

2021-01-20 22:02 UTC, tatehanawalt commented
@nhakmiller for simplicity my plan was just to have the simple static set. I'm still using a method to provide the set where it's used for this issue so it will be easy to update in the future.

2021-01-22 07:53 UTC, kostaspap commented on internal/core/analysis_api/handlers/create_update_policy.go
> +var ValidResourceTypes = map[string]struct{}{
The snapshot pollers maintain a map of supported ResourceTypes -> Service Name [here](https://github.com/panther-labs/panther/blob/master/internal/compliance/snapshot_poller/pollers/aws/clients.go#L79-L127)

I think it would be better to move that map to a common location, e.g. `pkg/awsresources` or something like that. Then the code here can reference it verify if a provided ResourceType is supported. With this approach we minimize the chance of forgetting to add some resource to the list here.

2021-01-22 08:04 UTC, kostaspap commented on internal/core/analysis_api/handlers/create_update_policy.go
> +var ValidResourceTypes = map[string]struct{}{
I just saw the comments write above after putting my own comment. For me, the above solution seems really straightforward and future proof. It might be that it adds some extra AWS dependencies, but I am not sure this would have a measurable impact.

2021-01-22 21:52 UTC, austinbyers commented on internal/core/analysis_api/handlers/create_update_policy.go
> +var ValidResourceTypes = map[string]struct{}{
> The snapshot pollers maintain a map of supported ResourceTypes -> Service Name here

Ah, I was only aware of the map from type name to the actual function handlers, which I believe is what Nick was referring to as well.

Yes, it looks like the map(s) you link to could work well. They don't even have to move to the `pkg/` folder - they are still specific to cloud security. They could be `internal/core/compliance/snapshot_poller/awsresources` or something

2021-01-27 00:25 UTC, tatehanawalt commented
Merged valid analysis and resource, Ready to start review. I will be completing more details in the morning

2021-01-27 01:46 UTC, austinbyers commented on internal/core/analysis_api/handlers/create_update_policy.go
> +var ValidResourceTypes = map[string]struct{}{
It turns out there is no existing map in the cloud security source we can leverage: they don't have the meta types. Hardcoding the types is the only feasible option at the moment

2021-01-27 01:58 UTC, austinbyers requested changes
Above and beyond with the integration tests, nice job!

Not sure how it happened, but you've got a bad merge somehow. Either undo every change that you don't intend to include in the PR, or just start over on a new branch and copy over the changes you care about.

You may be able to use `git rebase -i HEAD~10` to throw out bad merge commits, but honestly that's probably more trouble than it's worth :) I usually start over on a new branch when I run into weirdness https://xkcd.com/1597

2021-01-27 01:58 UTC, austinbyers commented on api/graphql/schema.graphql
> +type UploadPoliciesResponse {
I'm guessing you didn't intend to change the graphQL, it was just a bad merge.

Just copy the version of this file from the `master` branch into your branch, then run `mage gen fmt` and that should fix most of the stray web changes

2021-01-27 01:58 UTC, austinbyers commented on internal/compliance/aws_event_processor/processor/elbv2.go
> -		}
Another bad merge? It looks like you did a `git pull` but ignored all upstream changes, I know this was a recent change

2021-01-27 01:58 UTC, austinbyers commented on internal/compliance/snapshot_poller/models/aws/resourceTypes.go
> +var ResourceTypes = map[string]struct{}{
I don't see the `meta` schemas in here, be sure the length of this list matches the `web/src/constants.ts` / UI version

2021-01-27 01:58 UTC, austinbyers commented on internal/compliance/snapshot_poller/pollers/aws/clients.go
> -		// just the elb and elbv2 service, this is not the case. AWS just had to do it to 'em.
Probably need to keep this comment

2021-01-27 01:58 UTC, austinbyers commented on internal/core/analysis_api/handlers/bulk_upload.go
> +		return fmt.Errorf("DataModel contains invalid log type: %s", err.Error())
Use `errors.Errorf` to be consistent with the error handling in this service. The [`errors`](https://godoc.org/github.com/pkg/errors) package provides a nicer way to wrap errors and its stack trace - we try to use it for new code

2021-01-27 01:58 UTC, austinbyers commented on internal/core/analysis_api/handlers/clients.go
> +var ValidResourceTypes = map[string]struct{}{
leftover comment I assume

2021-01-27 01:58 UTC, austinbyers commented on requirements.txt
> +bandit==1.6.2
another bad merge

2021-01-27 01:58 UTC, austinbyers commented on internal/core/analysis_api/main/integration_test.go
> +	})
🎉  Love it

2021-01-27 01:58 UTC, austinbyers commented on internal/core/analysis_api/main/integration_test.go
> +func BulkZipUploadHelper(t *testing.T, fsSourcePath string) (*models.BulkUploadOutput, int, error) {
👍

2021-01-27 20:00 UTC, tatehanawalt commented on internal/core/analysis_api/main/integration_test.go
> +func BulkZipUploadHelper(t *testing.T, fsSourcePath string) (*models.BulkUploadOutput, int, error) {
I was actually going to ask do we have anything against adding an @author tag to method descriptions? Do we avoid doing that because git-blame exists?

2021-01-27 20:26 UTC, tatehanawalt commented on internal/compliance/aws_event_processor/processor/elbv2.go
> -		}
fixed with `git checkout master internal/compliance/aws_event_processor/processor/elbv2.go`

I'm thinking all of my git issues are relating to not setting an upstream. I was avoiding the -u flag  to be explicit which is not working as I intended.

2021-01-27 20:39 UTC, tatehanawalt commented on api/graphql/schema.graphql
> +type UploadPoliciesResponse {
yet another one...

Still getting an error after the fix. I ran:

```
git checkout master api/graphql/schema.graphql
mage clean
mage setup
mage gen fmt
```

But I'm getting a failed gql generation.

Running `npm run graphql-codegen` result error:

```
Error: Unable to find field "uploadPolicies" on type "Mutation"!
```

2021-01-27 20:40 UTC, tatehanawalt commented on internal/core/analysis_api/handlers/create_update_policy.go
> +var ValidResourceTypes = map[string]struct{}{
This has been updated to reflect a hardcoded set sourced from the snapshot_pollers src

2021-01-27 21:00 UTC, tatehanawalt commented on internal/core/analysis_api/handlers/bulk_upload.go
> +		return fmt.Errorf("DataModel contains invalid log type: %s", err.Error())
You mean using the github errors package right? Not the [go native errors package](https://golang.org/pkg/errors/#example_New_errorf)

2021-01-27 21:21 UTC, austinbyers commented on api/graphql/schema.graphql
> +type UploadPoliciesResponse {
Revert all of the web changes first, perhaps? Not just the GraphQL schema

2021-01-27 22:09 UTC, tatehanawalt commented on api/graphql/schema.graphql
> +type UploadPoliciesResponse {
@austinbyers I did a checked out the entire master/web directory before running this command. still getting the unable to find error

2021-01-27 22:39 UTC, tatehanawalt commented on api/graphql/schema.graphql
> +type UploadPoliciesResponse {
Somehow the file `web/src/components/wizards/BulkUploaderWizard/UploadPanel/graphql/uploadPolicies.graphql` made it to my branch but its not in master. file shows its from `7503ee73e (Theodore Vorillas 2020-09-18 19:09:46 +0300`

Removing that file along with the /uploadPolicies.generated.ts fixes the gen

2021-01-28 13:43 UTC, kostaspap reviewed
Nice job! Mostly style comments, code looks good!

2021-01-28 13:43 UTC, kostaspap commented on internal/compliance/aws_event_processor/processor/process.go
> -
Why these changes? They seem unrelated to the purpose of this PR?

2021-01-28 13:43 UTC, kostaspap commented on internal/compliance/snapshot_poller/models/aws/resourceTypes.go
> +package aws
File names in go are `snake_case` so this should be `resource_types.go`

2021-01-28 13:43 UTC, kostaspap commented on internal/core/analysis_api/handlers/bulk_upload.go
> +					results <- writeResult{err: errors.Errorf("panicked goroutine")}
nit: Just `errors.New()`, no need for formatting the string.

2021-01-28 13:43 UTC, kostaspap commented on internal/core/analysis_api/handlers/bulk_upload.go
> +		return nil, errors.Errorf("base64 decoding failed: %s", err)
This actually should have been `errors.Wrapf(err, "base64 decoding failed")` to make sure the the returned error has a stack trace. Since you are already updating this code, it think it would be nice to fix this issue ^^

2021-01-28 13:43 UTC, kostaspap commented on internal/core/analysis_api/handlers/bulk_upload.go
> +		return errors.Errorf("DataModel contains invalid log type: %s", err.Error())
See similar comments above. This could be `return errors.Wrap(err, "DataModel contains invalid log types")`

2021-01-28 13:43 UTC, kostaspap commented on internal/core/analysis_api/handlers/bulk_upload.go
> +			return errors.Errorf("only one LogType may be specified per DataModel")
Hmmm, i'm not sure this is relevant? This is `TypeGlobal`, not DataModel.

2021-01-28 13:43 UTC, kostaspap commented on internal/core/analysis_api/handlers/clients.go
> +const maxRetries = 20
I'm not sure this number make sense. This will cause the code to retry for half an hour.

2021-01-28 13:43 UTC, kostaspap commented on internal/core/analysis_api/handlers/clients.go
> +	lambdaLogTypesClient *lambda.Lambda
1. better use the interface `lambdaiface.LambdaAPI`. That way it can be mocked in tests. 
2. I don't think this variable needs to be shared at all?

2021-01-28 13:43 UTC, kostaspap commented on internal/core/analysis_api/handlers/clients.go
> +	refreshLogTypes()
Log types get created/delete at runtime. We should fetch the list on every Bulk upload operation, not fetch them only once. The operation is pretty fast, so I wouldn't be too concerned about caching them, etc.

2021-01-28 13:43 UTC, kostaspap commented on internal/core/analysis_api/handlers/clients.go
> +func ValidResourceTypeSet(checkResourceTypeSet []string) error {
`client.go` doesn't seem to be the right place for this code. `validate.go` maybe?

2021-01-28 13:43 UTC, kostaspap commented on internal/core/analysis_api/handlers/clients.go
> +	logtypeSetMap map[string]interface{}
nit: We prefer `map[string]struct{}` in such scenarios since it requires less allocations. Allocations don't really matter here, but better change it as a code style best practice.

2021-01-28 17:19 UTC, tatehanawalt commented on internal/compliance/aws_event_processor/processor/process.go
> -
Not sure how this ended up in my commit. Replaced it with the master file.

2021-01-28 17:40 UTC, kostaspap commented on internal/core/analysis_api/handlers/clients.go
> +	refreshLogTypes()
I am assuming these check would run every time someone uploads rules which should be not that frequent.

2021-01-28 17:45 UTC, tatehanawalt commented on internal/core/analysis_api/handlers/bulk_upload.go
> +		return nil, errors.Errorf("base64 decoding failed: %s", err)
i'm moving my changes to a new branch like 90% of these changes came from a bad merge

2021-01-28 17:55 UTC, tatehanawalt commented on internal/core/analysis_api/handlers/clients.go
> +func ValidResourceTypeSet(checkResourceTypeSet []string) error {
Totally agree. I was expecting this would come up in the pr request so I have all my validation code together to move it where it should go. 

validate.go sounds good to me I will have it there in my updated branch

2021-01-28 22:52 UTC, tatehanawalt commented on internal/core/analysis_api/handlers/bulk_upload.go
> +		return errors.Errorf("DataModel contains invalid log type: %s", err.Error())
Shouldn't we return the invalid log type? if someone tries to upload bulk data  and the upload fails how would they know how to fix it?

2021-01-28 22:53 UTC, tatehanawalt commented on internal/core/analysis_api/handlers/clients.go
> +const maxRetries = 20
updated to 5

2021-01-28 23:16 UTC, tatehanawalt commented on internal/core/analysis_api/handlers/clients.go
> +	lambdaLogTypesClient *lambda.Lambda
I have the logtypes client updated to the lambdaiface.LambdaAPI. 

what do you mean in terms of not being shared? I thought clients was a good place for this because it's a client. Are you saying to move it to the logtypes refresh method and create a new client on each refresh or move it to the validations.go file?

Also Note: I am about to open a new pr on a branch with commits on only the files for this feature.

2021-01-28 23:53 UTC, closed without merging

2021-01-29 08:19 UTC, kostaspap commented on internal/core/analysis_api/handlers/bulk_upload.go
> +		return errors.Errorf("DataModel contains invalid log type: %s", err.Error())
Ah no, I agree we should. I didn't realize that this is the error shown to the users ^^

`Wrapf` will concatenate the `err` message returned by the `validateLogtypeSet` error with the error message defined here so that information should be included anyway. But maybe that message is not that clear, so feel free to keep this one yeah.

2021-01-29 08:48 UTC, kostaspap commented on internal/core/analysis_api/handlers/clients.go
> +	lambdaLogTypesClient *lambda.Lambda
Sorry, my comment was not very clear. I've continued the discussion to the new PR.