Crowdstrike parsers: Insight special raw & Discover processed events
panther-labs/panther pull request #2475
Opened 2021-01-21 12:27 UTC by georgepsarakis

## Background

Why are you making this change? Please provide a reference to any related issues and PRs

## Changes

- List your changes here in more detail

## Testing

- How did you test your change?

2021-01-22 13:38 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events.go
> +	LoggedOnHostCount     pantherlog.String `json:"LoggedOnHostCount" description:"The number of hosts logged in at _time."`
Is it possible to convert this field to integer?

2021-01-22 13:39 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events.go
> +	MonthSinceReset       pantherlog.String `json:"monthsincereset" description:"The number of months since this user's password was last reset."`
Same as above, could be converted to integer.

2021-01-25 07:37 UTC, alxarch requested changes
Some details that need to be addressed:
- ~Use 'local' `mustBuild` for the new types so that the unknown event parser can exclude results of known event types.~
- All new tests should be in YAML form.

Also I added some observations around use of unsigned integer types.

2021-01-25 07:37 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events.go
> +	MonthSinceReset       pantherlog.Uint32 `json:"monthsincereset" description:"The number of months since this user's password was last reset."`
I would prefer this to be `pantherlog.Int32`. In general the unsigned variants should be reserved for very specific use cases such as network ports and even then their use is questionable. By using `pantherlog.Uint32` the column will end up being stored as `int64` because our storage backends do not have unsigned integers. There are multiple places in the code base where we use unsigned integer variants as a form of 'validation'. IMO this is problematic in several ways:
- By using unsigned variants we are enforcing log validation on our side. This should not be a concern of Panther. A mistake in some log entry should not prevent us from processing it.
- Validation is _implicit_ and is 'fused' with the JSON decoding process. I'd much rather have a `pantherlog.PortNumber` type instead of just `pantherlog.Uint16`. This uses the go type system to convey the programmer's intent clearly.
- Unsigned integers are rarely used outside of a 'low-level' or binary processing context. In those cases, they are used as 'words', 'bitmasks', or as a single opaque sequence of 4 or 8 bytes. When we want an integer number, regardless of whether the number should always be positive, we should use a 'normal' integer. 
- Using unsigned integers hinders interoperability with other systems such as databases where unsigned variants are not available (i.e. Athena). We risk having to resort to storing numbers as strings to cover the full range of uint64 for example or ending up with undefined behavior of how values outside the supported ranges are actually stored. 

To recap: there's no 'bug' here. You should be conscious as to why unsigned variants of integers are used and how they will be processed. 

Note that this is a point where discussion among us has not led to a consensus in the past.

2021-01-25 07:37 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events_test.go
> +func TestAppInfoParser(t *testing.T) {
We should only add new tests in YAML form. We are in the process of moving schema definitions to an external repo and tests there can only be in the YAML form.

2021-01-25 07:37 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events.go
> +	LocalIPCount         pantherlog.Uint8    `json:"localipCount" validate:"required" description:"The number of local IP addresses."`
Best use `pantherlog.Int32` here. I understand that having more than 255 IP addresses is probably never going to happen but a bug in the 'agent' software might easily push this value outside the range we expect it to be.

2021-01-25 07:37 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events_test.go
> +func TestAIDMasterParser(t *testing.T) {
Same as above, we should add new tests in YAML form.

2021-01-25 07:37 UTC, alxarch commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events.go
> +	TypeAppInfo = logtypes.MustBuild(logtypes.ConfigJSON{
For crowdstike logs we should be using the local `mustBuild`.
This is required so that the unknown event parser is aware of all known log types.
Please update all `TypeFooBar` declarations.

2021-01-25 08:59 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events.go
> +	TypeAppInfo = logtypes.MustBuild(logtypes.ConfigJSON{
Exactly, this was actually deliberate :)

2021-01-25 08:59 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events.go
> +	LocalIPCount         pantherlog.Uint8    `json:"localipCount" validate:"required" description:"The number of local IP addresses."`
Sure, makes sense, will change it.

2021-01-25 09:00 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events.go
> +	// NOTE: this the host local time, which could be unreliable (?)
Great, just noticed it and thought to leave a comment so we can discuss it during review. I'll remove the comments, thanks!

2021-01-25 10:49 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events.go
> +	MonthSinceReset       pantherlog.Uint32 `json:"monthsincereset" description:"The number of months since this user's password was last reset."`
I see, thanks a lot for the detailed explanation!

2021-01-25 13:29 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events.go
> +	UserName              pantherlog.String `json:"UserName" validate:"required" description:"The username of the system."`
Fixed in https://github.com/panther-labs/panther/pull/2475/files#diff-fc2fa41b652fe180a14b92ba2f9ff34f3c8bbeb8c5bbb47259380489a60fa003R62

2021-01-25 13:29 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events.go
> +	// NOTE: this the host local time, which could be unreliable (?)
Fixed in 10efa2fcb9b19a8b9cb93448bd456b3902d98bbe.

2021-01-25 13:29 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events.go
> +	MonthSinceReset       pantherlog.Uint32 `json:"monthsincereset" description:"The number of months since this user's password was last reset."`
Fixed in 10efa2fcb9b19a8b9cb93448bd456b3902d98bbe.

2021-01-25 13:30 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events.go
> +	LocalIPCount         pantherlog.Uint8    `json:"localipCount" validate:"required" description:"The number of local IP addresses."`
Fixed in 10efa2fcb9b19a8b9cb93448bd456b3902d98bbe.

2021-01-25 13:30 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events_test.go
> +func TestAppInfoParser(t *testing.T) {
Fixed in 10efa2fcb9b19a8b9cb93448bd456b3902d98bbe.

2021-01-27 14:41 UTC, alxarch approved these changes
LGTM

2021-01-27 15:04 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events.go
> +	PointerSize        pantherlog.String  `json:"PointerSize" description:"The processor architecture (in decimal, non-hex format): '4' for 32-bit, '8' for 64-bit."`
Should this be an int?

2021-01-27 15:04 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events.go
> +	DetectionCount  pantherlog.Int32  `json:"detectioncount" validate:"required" description:"The number of detections."`
Are we sure about the size or should be Int64? Just double-checking here, have been burned few times from many "counters" that went above their limits :P

2021-01-27 15:04 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events.go
> +	GatewayIP            pantherlog.String `json:"GatewayIP" validate:"required" description:"The gateway of the system where the sensor is installed."`
This can be added as an IP indicator.

2021-01-27 15:04 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events.go
> +	AIPCount             pantherlog.Int32    `json:"aipcount" validate:"required" description:"The number of public-facing IP addresses."`
Int64?

2021-01-27 15:04 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events.go
> +	LocalIPCount         pantherlog.Int32    `json:"localipCount" validate:"required" description:"The number of local IP addresses."`
Same here. Should this be Int64 (e.g. for IPv6)

2021-01-28 08:39 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events.go
> +	DetectionCount  pantherlog.Int32  `json:"detectioncount" validate:"required" description:"The number of detections."`
The exact data type is not specified in the documentation. Not sure what exactly this counter represents, but I assume it is the total number that a specific file has been found within the organization (all sensors). So passing the 2+ Billion threshold would seem a bit unlikely. In any case, sure we can increase it.

2021-01-28 08:40 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events.go
> +	PointerSize        pantherlog.String  `json:"PointerSize" description:"The processor architecture (in decimal, non-hex format): '4' for 32-bit, '8' for 64-bit."`
Sounds good, I'll replace with `Int32`.

2021-01-28 08:45 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events.go
> +	GatewayIP            pantherlog.String `json:"GatewayIP" validate:"required" description:"The gateway of the system where the sensor is installed."`
I thought about it and I wasn't sure if we consider this useful or maybe a bit noisy (we could always add this later). My reasoning was that this would be a specific IP for multiple machines, rather than a specific endpoint. I'll add it to the IP list now, thanks!

2021-01-28 08:48 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events.go
> +	LocalIPCount         pantherlog.Int32    `json:"localipCount" validate:"required" description:"The number of local IP addresses."`
Note that this likely refers to a single machine that is not managed (which I guess translates to not having a sensor installed). Will change it though, thanks.

2021-01-28 08:48 UTC, georgepsarakis commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events.go
> +	AIPCount             pantherlog.Int32    `json:"aipcount" validate:"required" description:"The number of public-facing IP addresses."`
Same reasoning as below, will change it.

2021-01-28 08:59 UTC, georgepsarakis commented
Thanks for the feedback @kostaspap. All changes applied in d1203a774af724532f554a10930ddf9495fdc20b.

2021-01-28 09:43 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events.go
> +	DetectionCount  pantherlog.Int32  `json:"detectioncount" validate:"required" description:"The number of detections."`
Thanks! Not sure how they count the detections here tbh, if they are e.g. IP matches on network logs, this could easily reach big numbers. Better safe than sorry ^^

2021-01-28 09:48 UTC, kostaspap commented on internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events.go
> +	GatewayIP            pantherlog.String `json:"GatewayIP" validate:"required" description:"The gateway of the system where the sensor is installed."`
Yup. If the users go to indicator search and put an IP, if that IP was present in any of the logs, we want to show them to the users. They can decide later if that's important or not ^^

2021-01-28 09:48 UTC, kostaspap approved these changes

2021-02-01 09:23 UTC, merged