Metrics system for system components
panther-labs/panther pull request #2479
Opened 2021-01-21 16:38 UTC by kostaspap

## Background

Why are you making this change? Please provide a reference to any related issues and PRs

## Changes

- List your changes here in more detail

## Testing

- How did you test your change?

2021-01-22 16:52 UTC, kostaspap commented on internal/log_analysis/log_processor/processor/stream.go
> -				if err == nil {
I had to make this change so that I could get metrics per S3 object.

2021-01-22 16:52 UTC, kostaspap commented on internal/log_analysis/log_processor/processor/stream.go
> +						zap.L().Warn("Skipping event due to error", zap.Error(err))
Same logging as few lines above

2021-01-22 16:52 UTC, kostaspap commented on pkg/metrics/counter.go
> +package metrics
Most of the code is from go-kit's metrics library (https://github.com/go-kit/kit/tree/master/metrics)

2021-01-22 16:55 UTC, kostaspap commented on internal/log_analysis/log_processor/common/common.go
> +	GetObject metrics.Counter
Normally if we had a 'handler' the manager would go in there, and I would probably have a struct to keep all metrics

2021-01-22 17:45 UTC, alxarch commented on internal/log_analysis/log_processor/common/common.go
> +		With(metrics.SubsystemDimension, metrics.SubsystemLogProcessing)
We should keep the label _value_ (`metrics.SubsystemLogProcessing`) in this package instead of the `metrics` one. What needs to be consistent across Lambdas is the label itself (`metrics.SubsystemDimension`)

2021-01-22 19:00 UTC, alxarch requested changes
This will greatly improve our observability!
I am conerned about 2 things:
1. The change in `kickoff` is probably a regression
2. I think the `Sync` function needs to take care about holding the lock too long

2021-01-25 12:06 UTC, kostaspap commented on pkg/metrics/cloudwatch.go
> +		Timestamp: c.timeFunc(),
It is actually done once for all the metrics - in line 144, you can see that we actually pass all metrics to that object.

2021-01-25 12:08 UTC, kostaspap commented on pkg/metrics/cloudwatch.go
> +	c.writer.Write(append(c.stream.Buffer(), '\n'))
Nice one! Yeah, I was annoying I had to do the append.

2021-01-25 12:09 UTC, kostaspap commented on pkg/metrics/counter.go
> +	With(dimensionValues ...string) Counter
I could do `dvs`. `lvs` was short for `LabelValues`

2021-01-25 12:15 UTC, giorgosp commented on pkg/metrics/dimensions.go
> +	// SubsystemDimension dimension
Dimensions are known by the users of the `metrics` pkg, wouldn't be better if each dimension was defined close to the code that creates the needed metric?

2021-01-25 12:15 UTC, giorgosp commented on pkg/metrics/dimensions.go
> +	IDDimension = "ID"
What is this `IDDimension` is used for? The comment doesn't help much. Should this be `sourceID` or `customlogID` etc?

2021-01-25 12:58 UTC, kostaspap commented on pkg/metrics/cloudwatch.go
> +func (c *CWEmbeddedMetricsManager) Sync() error {
Updated

2021-01-25 12:58 UTC, georgepsarakis reviewed
Great work! I wonder whether we should consider a more extended metric (dimensions) registry, that would allow consistent relationships with the corresponding alarms. Or will the alarm creation happen automatically, as a completely separate process, by somehow scanning the metric list in regular intervals?

2021-01-25 12:58 UTC, georgepsarakis commented on pkg/metrics/cloudwatch.go
> +	const namespace = "Panther"
Perhaps `namespace` should be a `CWEmbeddedMetricsManager` parameter passed during initialization?

2021-01-25 12:58 UTC, georgepsarakis commented on internal/log_analysis/log_processor/common/common.go
> +	CWMetrics = metrics.NewCWEmbeddedMetrics(os.Stdout)
The great thing about using the STDOUT stream is that we don't have to introduce an AWS API call, that would possibly force mocking the metric collection on several locations in the code for unit testing:

> On Lambda, you do not need to set this header yourself. Writing JSON to standard out in the embedded metric format is sufficient.

Minor since almost all the code runs on Lambda, but one possible future improvement would be to add support for the [`PutLogEvents` API](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html). I am guessing that now this would only apply to operational CLI tools, but again this unnecessary at this stage and can possibly be abstracted (and tested) rather easily later.

2021-01-25 12:58 UTC, georgepsarakis commented on internal/log_analysis/log_processor/processor/stream.go
> +	if strings.Contains(err.Error(), "AccessDenied") {
Isn't this a bit generic? I am guessing that it can become a common method, but I guess this will become apparent with broader usage.

2021-01-25 12:58 UTC, georgepsarakis commented on pkg/metrics/counter.go
> +package metrics
Maybe we should also copy some or all the unit tests?

2021-01-25 12:58 UTC, georgepsarakis commented on pkg/metrics/cloudwatch.go
> +	c.writer.Write(append(c.stream.Buffer(), '\n'))
Are there any size (length) limitations?

2021-01-25 14:02 UTC, kostaspap commented on pkg/metrics/cloudwatch.go
> +	var metrics []Metric
This is called every time we do a sync, which is rather infrequent. The allocation we are looking at is the scale of max few objects (max tens of objects in the future). I don't think there is any performance concern here. I think it's easier to read the code and kinda reduces the complexity of maintaining the `CWEmbeddedMetricsManager` struct

2021-01-25 14:02 UTC, kostaspap commented on pkg/metrics/cloudwatch.go
> +	for i, j := 0, 0; i < len(dimensionValues); i, j = i+2, j+1 {
We shouldn't be concerned too much. These allocations happen when we are about to output the metrics to I/O. The allocations depend on the number of labels and metrics we are going to emit, not on the time volume of processed data or anything.

2021-01-25 14:03 UTC, kostaspap commented on pkg/metrics/cloudwatch.go
> +	for i, j := 0, 0; i < len(dimensionValues); i, j = i+2, j+1 {
> Code to avoid them would be a bit more hard to read though

Yeah, that's the trick. We need the dimensions in two places: top level fields in the JSON (with their values) and also nested inside the `EmbeddedMetric` field.

2021-01-25 14:04 UTC, kostaspap commented on pkg/metrics/cloudwatch.go
> +	const namespace = "Panther"
Not really needed right now. For the foreseeable future, we will be publishing in this namespace.

2021-01-25 14:05 UTC, kostaspap commented on internal/log_analysis/log_processor/processor/stream.go
> +						metrics.IDDimension, s.Source.IntegrationID,
Good idea, will update

2021-01-25 14:09 UTC, kostaspap commented on pkg/metrics/cloudwatch.go
> +		for i := 0; i+1 < len(dms); i = i + 2 {
I just updated the code in there. Seems more work to split it to separate function.

2021-01-25 14:10 UTC, alxarch commented on pkg/metrics/cloudwatch.go
> +	for i, j := 0, 0; i < len(dimensionValues); i, j = i+2, j+1 {
My concern has more to do with holding the lock for too long. While the lock is held *all* goroutines incrementing the metrics are blocked. Reducing allocations and especially doing the actual `Write` **outside the lock**, will minimize this 'stop-the-world' effect. The choice of metrics 'flush' interval should not be affecting the performance of the system overall. If I wanted to log heap memory usage every 200ms for example (heap mem over 1 minute is not very helpful), I should expect that this won't cause the system to block for 10-50ms every 200ms.

2021-01-25 14:14 UTC, kostaspap commented on pkg/metrics/dimensions.go
> +	IDDimension = "ID"
Will update to `SourceIDDimension`

2021-01-25 14:16 UTC, kostaspap commented on internal/log_analysis/log_processor/common/common.go
> +	CWMetrics = metrics.NewCWEmbeddedMetrics(os.Stdout)
I don't think we'll need to support that API tbh. AWS recommends for Lambda to just output to stdout or use a custom Lambda logger when it is available (e.g. for Java Lambdas) or use the CloudWatch agent for non-serverless e.g. EC2 instances.

2021-01-25 14:17 UTC, kostaspap commented on pkg/metrics/dimensions.go
> +	// SubsystemDimension dimension
I think it's better for the Dimensions to be available project-wise. Dimensions essentially define the different "partitions" of the system, so they should be pretty standard. The actual values of those ones, yeah, this should be a bit standard.

2021-01-25 14:19 UTC, kostaspap commented
> Great work! I wonder whether we should consider a more extended metric (dimensions) registry, that would allow consistent relationships with the corresponding alarms. Or will the alarm creation happen automatically, as a completely separate process, by somehow scanning the metric list in regular intervals?

This is a very good question! I think we might end up with a registry as you suggest. I expect to work more on this in the next days - for the moment I want to get a metrics framework out and will likely revisit the how we register the labels/dimensions etc.

2021-01-25 14:21 UTC, kostaspap commented on internal/log_analysis/log_processor/processor/stream.go
> -				if err == nil {
Will update

2021-01-25 14:24 UTC, kostaspap commented on pkg/metrics/counter.go
> +package metrics
Nice idea, will do

2021-01-25 14:29 UTC, georgepsarakis commented on pkg/metrics/cloudwatch.go
> +	c.writer.Write(append(c.stream.Buffer(), '\n'))
Answering my question: the [maximum log entry size seems to be 256KB](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html), so it shouldn't be a problem here.

2021-01-25 15:42 UTC, alxarch commented on pkg/metrics/dimensions.go
> +	// SubsystemDimension dimension
Centralizing label names for labels that are used in multiple packages is the only way to ensure consistency throughout the system. This improves our ability to build useful parametric dashboards (i.e. same dashboard for all components, one component, some components).

2021-01-25 15:43 UTC, alxarch commented on pkg/metrics/dimensions.go
> +	// SubsystemDimension dimension
Now if a label is specific for a single metric, it is ok to be declared close to the code that defines the metric.
https://prometheus.io/docs/practices/naming/

2021-01-25 16:42 UTC, kostaspap commented on pkg/metrics/cloudwatch.go
> +	for i, j := 0, 0; i < len(dimensionValues); i, j = i+2, j+1 {
I agree with putting the `Write` outside of the block. 
Trying to avoid the extra allocations for Metrics and Dimension values seems really like microoptimizations - we are talking about slices with max a handful of elements. 
Given that `CWEmbeddedMetricsManager` is meant to write the metrics to the logs and logs cost, we will never be emitting them that frequently (in the `ms` scale) because it costs. I nevertheless changed the code to reuse the slices.

2021-01-26 15:48 UTC, alxarch approved these changes
This will come in handy!
We can explore ways to define units on metrics in a later PR when we have already had the chance to get a feeling of this in production.
LGTM

2021-01-26 15:48 UTC, alxarch commented on internal/log_analysis/log_processor/processor/stream.go
> +	if strings.Contains(err.Error(), "AccessDenied") {
Splitting hairs here, but I think we could be abit more elaborate here and use
```golang
var awsErr awserr.Error
if errors.As(err, &awsErr) {
   return err.Code()
}
return metrics.StatusErr
```

2021-01-26 15:48 UTC, alxarch commented on internal/log_analysis/log_processor/processor/stream.go
> +	if strings.Contains(err.Error(), "AccessDenied") {
Using the 'standard' error codes aws services return might come in handy when cross-referencing metrics

2021-01-26 15:48 UTC, alxarch commented on pkg/metrics/cloudwatch.go
> +		c.metricsBuf = append(c.metricsBuf, Metric{Name: name, Unit: "Count"})
This is probably too late for this PR but we should devise a way to define units on a counter. Perhaps with a different constructor function. The default would be "Count" but it should be overriddable when creating the metric.

2021-01-26 15:48 UTC, alxarch commented on pkg/metrics/cloudwatch.go
> +	for i, j := 0, 0; i < len(dimensionValues); i, j = i+2, j+1 {
I understand the cost argument but some metrics might require more granular intervals. Especially when debugging/testing a change in a Lambda. This is more relevant with Gauge-like metrics which can have spikes that wouldn't be caught with `time.Minute` intervals. For now we're good though.

2021-01-27 08:56 UTC, kostaspap commented on internal/log_analysis/log_processor/common/common.go
> +		With(metrics.SubsystemDimension, metrics.SubsystemLogProcessing)
Done

2021-01-27 08:57 UTC, kostaspap commented on pkg/metrics/cloudwatch.go
> +	var metrics []Metric
Code updated to avoid extra allocations.

2021-01-27 08:58 UTC, kostaspap commented on pkg/metrics/cloudwatch.go
> +		c.metricsBuf = append(c.metricsBuf, Metric{Name: name, Unit: "Count"})
Completely agree with this. I was thinking to change that part soon, it's easy to add.

2021-01-27 09:04 UTC, kostaspap commented on internal/log_analysis/log_processor/processor/stream.go
> +	if strings.Contains(err.Error(), "AccessDenied") {
I agree, this could be implemented better. Updated to use `awsutils.IsAnyError`. Unfortunately neither `s3` package nor `kms` package define the error code as constant

2021-01-27 09:08 UTC, merged