poll panther analysis
panther-labs/panther pull request #2480
Opened 2021-01-21 17:43 UTC by lindsey-w

## Background

This add support for polling pack data from github and tracking packs in a ddb. 

## Changes

- `github.go` : functionality to poll `panther-labs:panther-analysis` repo for new releases
- pack management:
  - GetPack: return info about a particular pack
  - ListPacks: list pack(s) information 
  - PollPacks: poll the github repo for new releases
  - PatchPack: update a pack to a particular version and/or enabled/disable pack

## Testing

- `mage test:go` : added new unit tests surrounding setting up pack updates
- manual testing (see below)
- integration tests: TBD

To test this manually, I forked the panther-analysis repo, pointed my dev account to it, and created test releases.

<details>
<summary>List Packs</summary>
Input:

```
{
  "ListPacks": {}
}
```

Output:

```
{
  "statusCode": 200,
  "headers": {},
  "multiValueHeaders": {},
  "body": "{\"paging\":{\"thisPage\":1,\"totalPages\":1,\"totalItems\":2},\"packs\":[{\"enabled\":false,\"updateAvailable\":true,\"createdBy\":\"00000000-0000-4000-8000-000000000000\",\"description\":\"This pack groups awesome stuff together\",\"displayName\":\"Totally Awesome Pack\",\"enabledVersion\":{\"id\":36673615,\"name\":\"1.15.1\"},\"id\":\"A.Pack.ID.Two\",\"lastModifiedBy\":\"00000000-0000-4000-8000-000000000000\",\"type\":\"\",\"userId\":\"\",\"versionId\":\"\",\"createdAt\":\"2021-01-20T23:24:23.876168212Z\",\"lastModified\":\"2021-01-21T00:26:16.153829327Z\",\"availableVersions\":[{\"id\":36673615,\"name\":\"1.15.1\"},{\"id\":36684752,\"name\":\"1.15.2\"}],\"detectionPatterns\":{\"IDs\":[\"AWS.Console.LoginFailed\",\"AWS.Console.LoginWithoutMFA\"]}},{\"enabled\":true,\"updateAvailable\":true,\"createdBy\":\"00000000-0000-4000-8000-000000000000\",\"description\":\"This pack groups awesome stuff together\",\"displayName\":\"Totally Awesome Pack\",\"enabledVersion\":{\"id\":36673615,\"name\":\"v1.15.1\"},\"id\":\"A.Pack.ID\",\"lastModifiedBy\":\"00000000-1111-4000-8000-000000000000\",\"type\":\"\",\"userId\":\"\",\"versionId\":\"\",\"createdAt\":\"2021-01-21T00:26:16.161973554Z\",\"lastModified\":\"2021-01-21T16:20:03.586397539Z\",\"availableVersions\":[{\"id\":36673615,\"name\":\"1.15.1\"},{\"id\":36684752,\"name\":\"1.15.2\"}],\"detectionPatterns\":{\"IDs\":[\"AWS.CloudTrail.Created\",\"AWS.Console.LoginFailed\",\"AWS.Console.LoginWithoutMFA\"]}}]}"
}
```

</details>

<details>
<summary>Get Pack</summary>

```
{
  "GetPack": {
    "id": "A.Pack.ID"
  }
}
```

Output:

```
{
  "statusCode": 200,
  "headers": {},
  "multiValueHeaders": {},
  "body": "{\"enabled\":true,\"updateAvailable\":true,\"createdBy\":\"00000000-0000-4000-8000-000000000000\",\"description\":\"This pack groups awesome stuff together\",\"displayName\":\"Totally Awesome Pack\",\"enabledVersion\":{\"id\":36673615,\"name\":\"v1.15.1\"},\"id\":\"A.Pack.ID\",\"lastModifiedBy\":\"00000000-1111-4000-8000-000000000000\",\"type\":\"\",\"userId\":\"\",\"versionId\":\"\",\"createdAt\":\"2021-01-21T00:26:16.161973554Z\",\"lastModified\":\"2021-01-21T16:20:03.586397539Z\",\"availableVersions\":[{\"id\":36673615,\"name\":\"1.15.1\"},{\"id\":36684752,\"name\":\"1.15.2\"}],\"detectionPatterns\":{\"IDs\":[\"AWS.CloudTrail.Created\",\"AWS.Console.LoginFailed\",\"AWS.Console.LoginWithoutMFA\"]}}"
}
```

</details>

<details>
<summary>Poll Packs</summary>

```
{
  "PollPacks": {}
}
```

Output:

```
{
  "statusCode": 200,
  "headers": {},
  "multiValueHeaders": {},
  "body": ""
}
```

</details>

<details>
<summary>Patch (update) Packs</summary>

```
{
  "PatchPack": {
    "enabled": true,
    "id": "A.Pack.ID",
    "userId": "00000000-1111-4000-8000-000000000000",
    "enabledVersion": {
      "id": 36684752,
      "name": "v1.15.2"
    }
  }
}
```

Output:

```
{
  "statusCode": 200,
  "headers": {},
  "multiValueHeaders": {},
  "body": "{\"enabled\":true,\"updateAvailable\":false,\"createdBy\":\"00000000-0000-4000-8000-000000000000\",\"description\":\"This pack groups awesome stuff together\",\"displayName\":\"Totally Awesome Pack\",\"enabledVersion\":{\"id\":36684752,\"name\":\"v1.15.2\"},\"id\":\"A.Pack.ID\",\"lastModifiedBy\":\"00000000-1111-4000-8000-000000000000\",\"type\":\"\",\"userId\":\"\",\"versionId\":\"\",\"createdAt\":\"2021-01-21T00:26:16.161973554Z\",\"lastModified\":\"2021-01-21T16:24:13.4496457Z\",\"availableVersions\":[{\"id\":36673615,\"name\":\"1.15.1\"},{\"id\":36684752,\"name\":\"1.15.2\"}],\"detectionPatterns\":{\"IDs\":[\"AWS.CloudTrail.Created\",\"AWS.Console.LoginFailed\",\"AWS.Console.LoginWithoutMFA\"]}}"
}
```

Dynamo entry for detection in pack has description:
A CloudTrail Trail was created, updated, or enabled. THIS IS A NEW DESCRIPTION.\n

</details>

<details>
<summary>Patch (rollback) Packs</summary>

```
{
  "PatchPack": {
    "enabled": true,
    "id": "A.Pack.ID",
    "userId": "00000000-1111-4000-8000-000000000000",
    "enabledVersion": {
      "id": 36673615,
      "name": "v1.15.1"
    }
  }
}
```

Output:

```
{
  "statusCode": 200,
  "headers": {},
  "multiValueHeaders": {},
  "body": "{\"enabled\":true,\"updateAvailable\":true,\"createdBy\":\"00000000-0000-4000-8000-000000000000\",\"description\":\"This pack groups awesome stuff together\",\"displayName\":\"Totally Awesome Pack\",\"enabledVersion\":{\"id\":36673615,\"name\":\"v1.15.1\"},\"id\":\"A.Pack.ID\",\"lastModifiedBy\":\"00000000-1111-4000-8000-000000000000\",\"type\":\"\",\"userId\":\"\",\"versionId\":\"\",\"createdAt\":\"2021-01-21T00:26:16.161973554Z\",\"lastModified\":\"2021-01-21T16:25:20.53470989Z\",\"availableVersions\":[{\"id\":36673615,\"name\":\"1.15.1\"},{\"id\":36684752,\"name\":\"1.15.2\"}],\"detectionPatterns\":{\"IDs\":[\"AWS.CloudTrail.Created\",\"AWS.Console.LoginFailed\",\"AWS.Console.LoginWithoutMFA\"]}}"
}
```

Dynamo entry for detection in pack has description:
A CloudTrail Trail was created, updated, or enabled.\n

</details>

2021-01-21 17:45 UTC, lindsey-w commented on api/lambda/analysis/models/api.go
>  )
This isn't a detection type; follows the same question from Nick's other PR - if this should be broken out into a different type (especially since it goes into a different table) - but then several of the dynamo func will need to be re-worked.

2021-01-21 18:01 UTC, lindsey-w commented on internal/core/analysis_api/handlers/poll_packs.go
> +func (API) PollPacks(input *models.PollPacksInput) *events.APIGatewayProxyResponse {
The scheduled cloudwatch event isn't included in this PR; considering adding to this one or making a new PR for it.

2021-01-21 23:15 UTC, wey-chiang reviewed
Left some comments -- will probably have more comments tomorrow. Nice work!

2021-01-22 00:04 UTC, lindsey-w commented on api/lambda/analysis/configmodels.go
> +}
> Detections would be a better suited name than DetectionPattern since it's just an array of the detection IDs

I was thinking that the patterns could be expanded at some later date (i.e. today its "IDs" but later it could be like what we specify with `panther_analysis_tool`'s `--filter` option?) If its trying too hard to future-proof, I can simplify it.

> Would we need another field to denote a Panther-managed pack?

I had left that and the 'source' information out on this round to simplify things (and since ddb allows us to add columns arbitrarily). I can add the `managed` flag back in though if you think it'll save us some grief in the future when we do support other sources of packs.

2021-01-22 00:05 UTC, lindsey-w commented on api/lambda/analysis/models/packs.go
> +type Pack struct {
embedded in my other comment

2021-01-22 00:07 UTC, lindsey-w commented on api/lambda/analysis/models/api.go
> +	PollPacks *PollPacksInput `json:"pollPacks,omitempty"`
Yea, like you mention, I was going with `Patch` simply because its not a complete update.  The other update actions may only be updating a few fields, but they still pass the entire object in, so I was just trying to convey the difference.

2021-01-22 16:55 UTC, wey-chiang requested changes
Looking good! 

Will need some work to implement the KMS compensating controls

2021-01-22 16:55 UTC, wey-chiang commented on internal/core/analysis_api/handlers/github.go
> +	for _, zipFile := range zipReader.File {
I think that's largely dependent on what compensating controls we implement i.e. including in the manifest a hash of the detection body

2021-01-22 16:55 UTC, wey-chiang commented on internal/core/analysis_api/handlers/github.go
> +				if len(config.Mappings) > 0 {
You could move this check out to reduce nesting and return early if it is an empty slice

2021-01-22 16:55 UTC, wey-chiang commented on internal/core/analysis_api/handlers/update_pack.go
> +		// or should this be the "system" userid?
Maybe have a separate field, i.e. lastModifiedBy (only users) and lastUpdated ?

2021-01-22 16:58 UTC, nhakmiller reviewed
Long PR! I got about halfway through when my attention got pulled, so I figured I'd leave at least what comments I had and come back later.

If we were to start this again from scratch, I might suggest isolating the put/patch/list packs analysis-api changes from the github polling/downloading changes. Might help with the PR size. At this point though I think we're committed though so no worries.

2021-01-22 16:58 UTC, nhakmiller commented on api/lambda/analysis/models/packs.go
> +	//VersionID string `json:"versionId" validate:"omitempty,len=32"` // TODO: will this be in S3?
Since we're maintaining different versions in GitHub I don't think we'll also need a "local" versioned copy of packs in s3.

2021-01-22 16:58 UTC, nhakmiller commented on api/lambda/analysis/configmodels.go
> +}
In the RFC discussion the other teams were very insistent that lists of IDs would not be sufficient in the long run, and I suppose I've come around to that too. I like the `DetectionPattern` for that reason, leaves an easy place to point to say we are going to support that in a future iteration.

2021-01-22 16:58 UTC, nhakmiller commented on api/lambda/analysis/models/packs.go
> +}
What does `Name` refer to in `Version`? Name of a pack? Name of the version?

2021-01-22 16:58 UTC, nhakmiller commented on internal/core/analysis_api/handlers/dynamo.go
> +// Write a single policy to Dynamo.
```suggestion
// Write a single pack to Dynamo.
```

2021-01-22 16:58 UTC, nhakmiller commented on internal/core/analysis_api/handlers/get.go
> +	//}
I said the same in another comment, but I think a "local" S3 copy is less relevant because we know the source of truth will always be available in GitHub. Especially since users can't modify packs yet.

2021-01-22 16:58 UTC, nhakmiller commented on internal/core/analysis_api/handlers/github.go
> +	signingKeyID     = "2f555f7a-636a-41ed-9a6b-c6192bf55810" // TODO: update: this is a test key
@wey-chiang per your double key suggestion, would we just have a `firstSigningKeyID` and `secondSingingKeyID` here? And then of course the keys would live in two different places.

Also lets prefix these with `panther` so in the future when customers can onboard their own packs it's clear what these keys are for.

2021-01-22 16:58 UTC, nhakmiller commented on internal/core/analysis_api/handlers/github.go
> +		} else if *asset.Name == "panther-analysis-all.zip" {
Let's make `panther-analysis-all.sig` and `panther-analysis-all.zip` constants.

2021-01-22 16:58 UTC, nhakmiller commented on internal/core/analysis_api/handlers/github.go
> +	response, err := http.Get(url) // nolint:gosec
Hmm this one raises some eyebrows. is `http.Get()` not using HTTPS? I would assume it is, but then I'm not sure why `nolint:gosec` is required.

2021-01-22 16:58 UTC, nhakmiller commented on internal/core/analysis_api/handlers/github.go
> +		return err
Error might be nil here, if somehow err is not nil and sourceData or signatureData is nil. Might be helpful for debugging purposes to add somethings like this
```suggestion
		zap.L().Error("GitHub release version download failed", zap.Error(err), zap.Bool("sourceData nil", sourceData == nil), zap.Bool("signatureData nil", signatureData==nil))
		return err
```

2021-01-22 16:58 UTC, nhakmiller commented on internal/core/analysis_api/handlers/github.go
> +	// Unzip in memory (the max request size is only 6 MB, so this should easily fit)
This comment was true because the input was a lambda invocation. I don't believe it is true any longer, since we're pulling zip files from GitHub. Now the average size of all our detections is around 400Kb so I don't think we're at risk of blowing out the memory any time soon, but we should remove this comment or update it.

2021-01-22 16:58 UTC, nhakmiller commented on internal/core/analysis_api/handlers/github.go
> +	// Finish each policy by adding its body and then validate it
```suggestion
	// Finish each detection by adding its body and then validate it
```

2021-01-22 16:58 UTC, nhakmiller commented on internal/core/analysis_api/handlers/github.go
> +	for _, zipFile := range zipReader.File {
Yeah I see a lot of repeated code here, which will be a hassle to maintain. Might be worth to see which bits can be yanked out into a shared function.

2021-01-22 16:58 UTC, nhakmiller commented on internal/core/analysis_api/handlers/github.go
> +			zap.L().Warn("can't parse version", zap.String("version", *release.Name))
Yeah this seems correct
```suggestion
			// if we can't parse the version, just throw it away
			zap.L().Warn("can't parse version", zap.String("version", *release.Name))
```

2021-01-22 16:58 UTC, nhakmiller commented on internal/core/analysis_api/handlers/github.go
> +	}
I like keeping this isolated like this so we can re-work it as needed.

2021-01-22 16:58 UTC, nhakmiller commented on internal/core/analysis_api/handlers/github.go
> +func validateSignature(rawData []byte, signature []byte) error {
Is it possible to differentiate between failed validations and just generic errors? I suppose in general it's hard to tell a malformed signature from a maliciously tampered with one, but I think a wrong signature might deserve more alarms than say a KMS transient network error.

2021-01-22 16:58 UTC, nhakmiller commented on internal/core/analysis_api/handlers/list_packs.go
> +	}
This does work. The alternative is make `EnabledVersion` a struct pointer that is nil when not set, but this method is perfectly acceptable.

2021-01-22 16:58 UTC, nhakmiller commented on internal/core/analysis_api/handlers/poll_packs.go
> +	//} else {
Is this dead code? Let's drop it if so.

2021-01-22 18:17 UTC, lindsey-w commented on api/lambda/analysis/models/packs.go
> +}
Name is the name of the version (e.g. "v1.14.0") 

I only include both an ID and Name here because github only allows retrieving releases based on an ID, there may be a way for me to _only_ store the name/tag of the version, do a query to get the id, then retrieve the release. (If that is preferable)

2021-01-22 18:52 UTC, lindsey-w commented on internal/core/analysis_api/handlers/github.go
> +		}
Were we going to push the manifest in a separate file than the detections? Here I was downloading the "all" zip file which would include the IOCs zip and the manifest, but I can see pulling down just the manifest file vs "everything" each time.  

I'll add one for the public key - so one will live in kms and one will be published with the release?

2021-01-22 19:13 UTC, lindsey-w commented on internal/core/analysis_api/handlers/github.go
> +	response, err := http.Get(url) // nolint:gosec
Yea, it does do https... but I'll add some client config rather than use the default to: (1) add a timeout and (2) also see if I can force https versus leaving it up to the caller to call it with 'https' url

2021-01-22 19:18 UTC, lindsey-w commented on internal/core/analysis_api/handlers/update_pack.go
> +			newItems = append(newItems, detection)
This could be simplified to just call the `writePack()` with the new detections if we want to overwrite everything (no if/else in that case)

2021-01-25 22:59 UTC, lindsey-w commented on internal/core/analysis_api/handlers/poll_packs.go
> +	if isNewReleaseAvailable(latestRelease, currentPacks) {
This is only "forward" looking - it won't retroactively attempt to add any older versions to the pack. 🤔

2021-01-25 23:35 UTC, lindsey-w commented on internal/core/analysis_api/handlers/github.go
> +func validateSignature(rawData []byte, signature []byte) error {
Added specific check for `ErrCodeKMSInvalidSignatureException` - which will log `Error` - other failures will log `Warn`

2021-01-26 12:42 UTC, kostaspap reviewed
This is a lot of code! Thanks for doing this. 
I have put some style comments and few comments about other issues. 

I see that this PR is still a draft, not sure if this is going to become a "real" PR or is it going to be broken down to multiple ones? 
I have to say it is difficult to do meaningful PR over 2k lines of code so in the future it would be better to break it down to smaller chunks.

2021-01-26 12:42 UTC, kostaspap commented on internal/core/analysis_api/handlers/dynamo.go
> +		return nil, err
See comment above. Better:
```
return nil, errors.Wrapf(err, "failed to get item %s from table %s", table, id)
```

Some comment goes for the rest of the new code

2021-01-26 12:42 UTC, kostaspap commented on internal/core/analysis_api/handlers/get.go
> +	itemID, err := url.QueryUnescape(input.ID)
Do you have to do this? This was needed some time ago when we were using GatewayAPI, it shouldn't be required now - AppSync is invoking Lambda directly.

2021-01-26 12:42 UTC, kostaspap commented on internal/core/analysis_api/handlers/github.go
> +	cacheTimeout = 15 * time.Minute
Do we really need a cache here? What is the concern? It would better to avoid using cache if we don't have to. Simplifies code and also ... "caching is hard".

2021-01-26 12:42 UTC, kostaspap commented on internal/core/analysis_api/handlers/github.go
> +	rawAsset, url, err := githubClient.Repositories.DownloadReleaseAsset(context.Background(), pantherGithubOwner, pantherGithubRepo, id)
1. This should be `context.TODO()`
2. If there is an error, we should return early
3. After the error handling, better do `defer rawAsset.Close()`

2021-01-26 12:42 UTC, kostaspap commented on internal/core/analysis_api/handlers/github.go
> +		if *asset.Name == pantherSignatureFilename {
better `aws.String(asset.Name)`. This is a response from an external party, we need to be extra careful to avoid nil pointer dereferences.

2021-01-26 12:42 UTC, kostaspap commented on internal/core/analysis_api/handlers/github.go
> +	}
Instead of defining the client in here on every request, better define one, in the `internal/core/analysis_api/handlers/clients.go` file. Otherwise, testing this code could be very challenging.

2021-01-26 12:42 UTC, kostaspap commented on internal/core/analysis_api/handlers/github.go
> +	if *result.SignatureValid {
```
if aws.BoolValue(result.SignatureValid)
```
for safety since we don't really control that response.

2021-01-26 12:42 UTC, kostaspap commented on internal/core/analysis_api/handlers/github.go
> +func downloadGithubAsset(id int64) ([]byte, error) {
Maybe this code could be inside `pkg/github` package so other parts of the system can re-use. @alxarch

2021-01-26 12:42 UTC, kostaspap commented on internal/core/analysis_api/handlers/update_pack.go
> +	item, err := dynamoGetPack(input.ID, false)
Seems this should be consistent read? Otherwise we might patch with wrong data.

2021-01-26 12:42 UTC, kostaspap commented on internal/core/analysis_api/handlers/update_pack.go
> +	newPack, err := dynamoGetPack(input.ID, false)
Same here. It should be a consistent read. How often is `dynamoGetPack` going to get invoked? Are there cost considerations for allowing it to be inconsistent?

2021-01-26 12:42 UTC, kostaspap commented on internal/core/analysis_api/handlers/update_pack.go
> +			models.TypeGlobal,
Do we have to add everything explicitly here? Is it possible to avoid it? I am thinking that this would be something really easy to miss.

2021-01-26 12:42 UTC, kostaspap commented on internal/core/analysis_api/handlers/util.go
> +func writePack(item *packTableItem, userID string, mustExist *bool) error {
nit: Move this code to `pack.go`? This file ends up having logic from all parts of the analysis api, will be really hard to maintain.

2021-01-26 16:52 UTC, lindsey-w commented
> I see that this PR is still a draft, not sure if this is going to become a "real" PR or is it going to be broken down to multiple ones?
> I have to say it is difficult to do meaningful PR over 2k lines of code so in the future it would be better to break it down to smaller chunks.

I was considering taking in current comments then doing two new PRs - one around the pack definitions/changes and one around the polling/github. Apologies to everyone - this is a pretty ridiculous PR to ask folks to look at in one shot.

2021-01-26 16:58 UTC, lindsey-w commented on api/lambda/analysis/models/packs.go
> +	EnabledVersion Version `json:"enabledVersion"`
I changed the name of this a couple of times because I also didn't like `enabledVersion` or `enabledRelease` (which is why the comment doesn't match the name - I'll fix that).  I have a hard time with naming conventions XD. This is supposed to represent the current version of the pack that is installed.  I didn't think `currentVersion` really fit either since that could also be interpreted as the "latest" release.

2021-01-26 16:58 UTC, lindsey-w commented on deployments/core.yml
> +    Type: AWS::DynamoDB::Table
yea, that's the idea

2021-01-26 17:03 UTC, lindsey-w commented on internal/core/analysis_api/handlers/bulk_upload.go
> +			if analysisItem.Type == models.TypeDataModel && len(config.Mappings) > 0 {
would't make much sense 😆  Updating..

2021-01-26 17:07 UTC, lindsey-w commented on internal/core/analysis_api/handlers/bulk_upload.go
> +		} else if detection.Type != models.TypeDataModel {
Right, this is checking for the `TypeDataModel` - which isn't necessarily a 'detection' is handled like globals and grouped with the other detections.

2021-01-26 17:14 UTC, lindsey-w commented on internal/core/analysis_api/handlers/github.go
> +	cacheTimeout = 15 * time.Minute
I guess just trying to prevent us from having to download a release multiple times when someone updates packs one at a time - where each request to update will download the same release.  Perhaps not that big of a concern since this shouldn't happen that often and `panther-analysis` releases aren't that big.

2021-01-26 17:26 UTC, kostaspap commented on api/lambda/analysis/models/packs.go
> +	EnabledVersion Version `json:"enabledVersion"`
What about just `version` or `packVersion`?

2021-01-26 18:10 UTC, kostaspap commented on internal/core/analysis_api/handlers/github.go
> +func downloadGithubAsset(id int64) ([]byte, error) {
Refactoring the code to be a Client struct might be lot of work and is not critical - I think putting the shared code in a place might be useful though. Better coordinate with @alxarch on the latter, since I am not 100% sure which parts of this he might find useful.

2021-01-26 21:20 UTC, nhakmiller commented on api/lambda/analysis/models/packs.go
> +	EnabledVersion Version `json:"enabledVersion"`
+1 for `packVersion`.

2021-01-27 00:04 UTC, nhakmiller reviewed
Looking good, a few more comments. One more iteration and I think we can merge this into the feature branch, since we're going to be iterating & testing on this a lot before merging to master I think it doesn't need to be perfect.

2021-01-27 00:04 UTC, nhakmiller commented on internal/core/analysis_api/handlers/update_pack.go
> +func updatePackEnabledVersion(input *models.PatchPackInput, item *packTableItem) *events.APIGatewayProxyResponse {
Maybe I'm just tired/low on coffee, but each of the function names in this file seem practically identical and I'm having an extremely difficult time differentiating them/understanding them. Could you add a comment above each function explaining what it does? Like

```
// updatePackEnabledVersion changes what version of a pack is enabled in Dynamo. This function also handles all the additional work needed when updating a pack's version
func updatePackEnabledVersion(input *models.PatchPackInput, item *packTableItem) *events.APIGatewayProxyResponse {
<...>

// updatePackEnablement handles enabling and disabling packs, including enabling/disabling all the detections in that pack
func updatePackEnablement(input *models.PatchPackInput, item *packTableItem) *events.APIGatewayProxyResponse {
```

2021-01-27 00:04 UTC, nhakmiller commented on internal/core/analysis_api/handlers/util.go
> +func writePack(item *packTableItem, userID string, mustExist *bool) error {
I think `writeItem` makes sense here because many different functions call it for many different reasons. I suspect `writePack` will only be called by a few functions related to enabling/disabling packs. I agree with Kostas this could probably live in a separate file or with the rest of the pack code.

2021-01-27 03:54 UTC, lindsey-w commented on internal/core/analysis_api/handlers/update_pack.go
> +func updatePackEnabledVersion(input *models.PatchPackInput, item *packTableItem) *events.APIGatewayProxyResponse {
Nope, it is really confusing.  😆  I'll work on adding comments and always open to suggestions

2021-01-27 07:19 UTC, kostaspap commented on api/lambda/analysis/models/packs.go
> +	Page     int `json:"page" validate:"min=0"`
>  I feel like it would be strange for just this one to use the new method of pagination.

Makes sense

2021-01-27 07:37 UTC, kostaspap commented on internal/core/analysis_api/handlers/github.go
> +	rawAsset, url, err := githubClient.Repositories.DownloadReleaseAsset(context.Background(), pantherGithubOwner, pantherGithubRepo, id)
> What is context.TODO()?

The context object should normally be passed from the APIs entry point down the call stack to be used by functions like this. So in this case, the "proper" way to do it would require the handler method (the entry point to the lambda) passing the `context.Context` object provided by the Lambda runtime down the call stack... until it reached `func downloadGithubAsset(ctx context.Context, id int64) ([]byte, error)`. We would then pass that ctx to the githubClient function.

Since we don't do that, we could pass the `context.TODO` to satisfy the Github Client's requirements. From `context.TODO` docs
<pre>
// TODO returns a non-nil, empty Context. Code should use context.TODO when
// it's unclear which Context to use <b>or it is not yet available (because the
// surrounding function has not yet been extended to accept a Context
// parameter).</b>
</pre>

Ideally: 
1. All new code should be passing `context.Context` object as argument down the call stack. 
2. The top level functions can invoke private functions for the time being with `context.TODO()`
3. Eventually we wire the handler's context with the API public functions context

but that's a bigger change.

2021-01-27 17:45 UTC, lindsey-w commented on internal/core/analysis_api/handlers/update_pack.go
> +	if input.EnabledVersion.Name != "" && input.EnabledVersion.Name != item.EnabledVersion.Name {
If someone is enabling a pack, but not updating it.  I can change the input to make `Enabled` and `PackVersion` `required` on patches - so this would simply to `old version != new version`

2021-01-27 23:37 UTC, lindsey-w commented on internal/core/analysis_api/handlers/update_pack.go
> +func updatePackEnabledVersion(input *models.PatchPackInput, item *packTableItem) *events.APIGatewayProxyResponse {
I decided to (slightly) simplify this by just always calling the same function to update the pack - whether the user is updating enabled/disabled, the pack version, or both.  This removed an if/else and a whole function altogether.  This also has the benefit in that ... if for whatever reason the update/rollback fails in the middle (pack was updated but the detections weren't) - then when calling this again the even though it looks like the pack is on the right version, it will still try to do the update.  This has the downside of doing a complete update every time (even if everything is as it should be) - but I think the benefits outweigh the costs?

2021-01-27 23:38 UTC, lindsey-w commented on internal/core/analysis_api/handlers/update_pack.go
> +			newItems = append(newItems, detection)
Hmm, so enabling a pack in the UI wouldn't enable the detections in it?

2021-01-29 10:08 UTC, alxarch reviewed
I think the approach to listing releases will be problematic due to API rate limiting.

2021-01-29 10:08 UTC, alxarch commented on pkg/github/github.go
> +func downloadURL(client *GithubClient, url string) ([]byte, error) {
We should be passing `context.Context` and use it in the request.
We should use `http.Client.Do()` instead of `Get` to do that. If you take a look into the code of `Get()` it just calls `Do`.

2021-01-29 10:08 UTC, alxarch commented on pkg/github/github.go
> +	rawAsset, url, err := client.Github.Repositories.DownloadReleaseAsset(context.TODO(), owner, repository, id)
We should be passing `context.Context` from an argument here and let `context.TODO()` to be decided by the caller.

2021-01-29 10:08 UTC, alxarch commented on pkg/github/github.go
> +func (c *GithubClient) ListAvailableGithubReleases(owner string, repository string) ([]*github.RepositoryRelease, error) {
We should be passing `context.Context` here and wire it through to all functions.

2021-01-29 10:40 UTC, alxarch commented on pkg/github/github.go
> +func (c *GithubClient) ListAvailableGithubReleases(owner string, repository string) ([]*github.RepositoryRelease, error) {
After some discussion with @georgepsarakis it seems that the API returns the releases in (almost) reverse order basd on `published at`.
This is undocumented in the API but we can rely on it for now.

In this case fetching *only one page* should work. 100 releases back should be of no interest to anyone for our use case.

The order is not very strict as can be seen [here](https://github.community/t/releases-api-cant-figure-out-order/741)

2021-01-29 10:54 UTC, alxarch commented on pkg/github/github.go
> +func (c *GithubClient) ListAvailableGithubReleases(owner string, repository string) ([]*github.RepositoryRelease, error) {
We should make sure that calls to the GitHub API are issued only after _explicit user action_ and automatically (i.e. when accessing a page) to avoid hitting the rate limit.

2021-01-29 23:57 UTC, nhakmiller commented on internal/core/analysis_api/handlers/update_pack.go
> +func updatePackEnabledVersion(input *models.PatchPackInput, item *packTableItem) *events.APIGatewayProxyResponse {
Yeah I think so. Plus this is called fairly rarely so we don't have to worry if it's a bit inefficient.

2021-01-29 23:59 UTC, nhakmiller commented on pkg/github/github.go
> +func (c *GithubClient) ListAvailableGithubReleases(owner string, repository string) ([]*github.RepositoryRelease, error) {
My understanding is this API call is only made once a day, I don't think there will even be a button users can press to initiate it. Sort of a background update process. Might be good to add a comment about this rate limit though so we know not to expand it too much in the future.

2021-01-30 00:12 UTC, nhakmiller commented on internal/core/analysis_api/handlers/update_pack.go
> +			newItems = append(newItems, detection)
basically I want to  be able to support this:
- User enables pack
- User sees one rule in the pack they don't like
- User disables rule they don't like
- User gets updates to pack, rule stays disabled.

Maybe there should be a "userDisabled" field, which overrides the "enabled" field? Probably a future improvement at this point, what you have here seems like a good start.

2021-01-30 00:14 UTC, nhakmiller approved these changes

2021-01-30 00:49 UTC, merged