RegionIgnoreListError TypeAssertionError
panther-labs/panther pull request #2549
Opened 2021-01-28 23:50 UTC by wey-chiang

## Background

While investigating problems in AWS, the following error message was found
`interface conversion: error is *errors.withStack, not *aws.RegionIgnoreListError: TypeAssertionError`
This PR is meant to address that type assertion.

## Changes

- Changed logic from `if err == err.(*RegionIgnoreListError)` to `if errors.As(err, &e)`
- Added test case to s3_bucket_test.go to make sure the `RegionIgnoreListError` is returned when region is ignored.

## Testing

- `mage test:ci`

2021-01-29 00:57 UTC, austinbyers commented on internal/compliance/snapshot_poller/pollers/aws/poll.go
> +		if errors.As(err, &e) {
The `&e` is now a double pointer (`**RegionIgnoreListError`). That might work, but probably not what you want.

```suggestion
		var e RegionIgnoreListError
		if errors.As(err, &e) {
```

2021-01-29 07:16 UTC, kostaspap requested changes

2021-01-29 07:16 UTC, kostaspap commented on internal/compliance/snapshot_poller/pollers/aws/s3_bucket_test.go
> +func TestS3BucketPollerRegionIgnoreListError(t *testing.T) {
This test passes even if the change in the `poll.go` is commented out.

Please first create a test that will trigger the same error we've seen in production, then write the code to fix it.

2021-01-29 17:29 UTC, austinbyers commented on internal/compliance/snapshot_poller/pollers/aws/s3_bucket_test.go
> +func TestS3BucketPollerRegionIgnoreListError(t *testing.T) {
Good catch!

2021-02-02 23:36 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/aws/poll.go
> +		if errors.As(err, &e) {
So upon second review, it appears that I need to use a double pointer here. Following the [Go Blog](https://blog.golang.org/go1.13-errors): 

> `errors.As` will panic if the target is not a non-nil pointer to either a type that implements error, or to any interface type. 

Instantiating `e` as `var e RegionIgnoreListError` causes `errors` to complain: `*target must be interface or implement error`

2021-02-02 23:53 UTC, austinbyers approved these changes

2021-02-03 01:09 UTC, wey-chiang commented on internal/compliance/snapshot_poller/pollers/aws/s3_bucket_test.go
> +func TestS3BucketPollerRegionIgnoreListError(t *testing.T) {
> This test passes even if the change in the poll.go is commented out.

Doh! 😓  Good catch, this should no longer hold true with the latest set of commits.

2021-02-03 10:28 UTC, kostaspap commented on internal/compliance/snapshot_poller/pollers/aws/poll_test.go
> +	assert.Equal(t, nil, err)
nit: 
```suggestion
	assert.NoError(t, err)
```

2021-02-03 10:28 UTC, kostaspap approved these changes

2021-02-03 15:29 UTC, merged