Panther Rules Engine Cross Account IAM Permissions CFNS
panther-labs/panther pull request #2561
Opened 2021-01-29 21:56 UTC by horakj

## Background

Customers have requested a way to create dynamic lists or make third part API calls which can be used in the Rules engine in Panther. This method will create the cross account access need to make the request happen. 

Full resolve below. This will work right now.

Issue: Panther Rules Engine CFN Parameter for Attached Managed Policies ARN #2560 

## Changes

- 1 CFN for a Target or Customer account which creates an IAM role that can be assumed by the Panther Rules engine for read-only s3 and Secrets Manager access
- 1 CFN for the Panther Account Rules Engine IAM role which can assume the role created above

## Testing

- Deployed in Dev Account
- Created Rule that uses boto3's sts and s3 api calls

2021-02-01 20:30 UTC, austinbyers requested changes
Thanks for putting this together! You're becoming a CloudFormation expert in no time

2021-02-01 20:30 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-customer.yml
> +                Resource: !Sub arn:aws:s3:::${TargetBucketName}/*
The `s3:ListBucket` permission actually [requires](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html#amazons3-actions-as-permissions) just the bucket resource. So you would need:

```yml
- Effect: Allow
  Action:
    - s3:Get*
    - s3:List*
  Resource:
    - !Sub arn:aws:s3:::${TargetBucketName}
    - !Sub arn:aws:s3:::${TargetBucketName}/*
```

2021-02-01 20:30 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-customer.yml
> +    Description: Enter the S3 Bucket that the Panther Rules Engine can Read from.
If the bucket is encrypted with KMS, the user will also need to provide the KMS key ID. You can add that as a `TODO` if we don't need it right now

2021-02-01 20:30 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-customer.yml
> +      RoleName: PantherRulesEngineCrossAccountReadOnlyRole
IAM is a global namespace, so hardcoding the role name would mean it would only work in one region. Perhaps we can do

```yml
RoleName: !Sub PantherRulesEngineCrossAccountReadOnlyRole-${AWS::Region}
```

2021-02-01 20:30 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-customer.yml
> +                Resource: arn:aws:secretsmanager:*
This would allow fetching every secret in the account! That's probably far too broad - there should be a secretID that can be passed in instead

2021-02-01 20:30 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-panther.yml
> +            Resource: arn:aws:secretsmanager:*
Why do we need these permissions directly? They're already part of the role we're assuming

2021-02-01 20:30 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-panther.yml
> +Description: Panther Rules Engine Read-only Cross Account Assume Role and Secrets Manager Managed Policy for Panther Account
This stack is meant to be deployed in Panther's account?

I know we're trying to get a solution as fast as possible, but this should really be a setting passed through to the main panther stacks. Otherwise, we'll have to deploy this as a separate template for every customer that needs it, and we'll have two different templates that are affecting the same IAM role, which means they could clobber each other.

Tagging @nhakmiller and @s0l0ist to get their input as well - is this a sufficient solution in the short term?

----

I think it's actually pretty simple to do this the "correct" way:

* Add a top-level `AssumablePythonRoles` parameter in the root stack (`master.yml`). This would be an optional list of IAM roles that both of the python engines are allowed to assume
    * Or we could have different parameters for policy vs rules engine
* Pass that parameter to the `log-analysis` stack (rules-engine) and the `cloud-security` stack (policy-engine)
* Add an inline policy to the rules-engine / policy-engine which allows assuming the roles if one has been defined:

```yml
Statement:
   - !If
     - AssumablePythonRolesDefined
     - Effect: Allow
       Action: sts:AssumeRole
       Resource: !Ref AssumablePythonRoles
     - !Ref AWS::NoValue
```

This way, we can manage this setting the same as all of our other settings on a user deployment. I know you may need help with this, perhaps @s0l0ist can help with that implementation

2021-02-03 18:21 UTC, horakj commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-customer.yml
> +                Resource: !Sub arn:aws:s3:::${TargetBucketName}/*
Thank you, will add that!

2021-02-03 18:22 UTC, horakj commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-customer.yml
> +      RoleName: PantherRulesEngineCrossAccountReadOnlyRole
Nice, Thank you Ill update that.

2021-02-03 18:22 UTC, horakj commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-customer.yml
> +                Resource: arn:aws:secretsmanager:*
Easy fix, wil do.

2021-02-03 18:24 UTC, horakj commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-panther.yml
> +            Resource: arn:aws:secretsmanager:*
The logic here is in case the customer wants to give us a secret to store in the panther account (SaaS) this would allow for quicker processing. Thoughts?

2021-02-03 18:27 UTC, horakj commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-panther.yml
> +Description: Panther Rules Engine Read-only Cross Account Assume Role and Secrets Manager Managed Policy for Panther Account
Yes I would be happy for any help that would be on the main stack. This PR was the now solution but the above is the correct. Should I drop the this PR for Aux templates or keep it?

2021-02-05 17:48 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-panther.yml
> +            Resource: arn:aws:secretsmanager:*
If we're going with the assume role strategy, usually all of the permissions are attached to the role you assume, and only that role. Then this role only allows `sts:AssumeRole`

2021-02-05 17:52 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-panther.yml
> +Description: Panther Rules Engine Read-only Cross Account Assume Role and Secrets Manager Managed Policy for Panther Account
>  Should I drop the this PR for Aux templates or keep it?

We still need the customer template for sure. The one for Panther I think we should combine with #2217 - pass in a list of roles the engines are allowed to assume. I'll let @nhakmiller make the final call as to how to proceed with the Panther side - I can help next week if needed

2021-02-08 23:15 UTC, horakj commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-panther.yml
> +Description: Panther Rules Engine Read-only Cross Account Assume Role and Secrets Manager Managed Policy for Panther Account
I updated both templates to reflect the changes, if good we can proceed with figuring out how to combine with the issue above

2021-02-08 23:16 UTC, horakj commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-customer.yml
> +    Description: Enter the S3 Bucket that the Panther Rules Engine can Read from.
I am going to put that as a TODO for now, TY sir!

2021-02-10 21:49 UTC, austinbyers approved these changes
So here's how we'll move forward (I synced with @nhakmiller )

I will finish https://github.com/panther-labs/panther/pull/2217 - we're going to add a configuration option to Panther which allows users to pass in an arbitrary list of managed IAM policies.

-----

So I think you've got the right setup:

1. The customer deploys an IAM role in their target account which Panther can assume
2. We deploy a managed policy in the Panther account which is allowed to assume that role (or do anything else)
3. The managed policy is passed as a configuration option to Panther. We just redeploy Panther to re-attach the policy

So you've got steps 1 and 2 in this PR and I'll work on step 3 in the [other PR](https://github.com/panther-labs/panther/pull/2217)

But the important point is that we will *not* be manually changing Panther infrastructure. Manually attaching a managed policy to a Panther deployment will be problematic

2021-02-10 21:49 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-customer.yml
> +                  - !Sub arn:aws:s3:::${TargetBucketName}/*
Use `:${AWS::Partition}:` instead of `:aws:`, again

2021-02-10 21:49 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-customer.yml
> +    Type: 'AWS::IAM::Role'
Nit: we don't need quotes here (nor on the version)

2021-02-10 21:49 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-customer.yml
> +    Description: Enter the S3 Bucket that the Panther Rules Engine can Read from.
I don't see the TODO comment... can we add it?

2021-02-10 21:51 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-customer.yml
> +    Default: NoSecret
The better way to do this would be to have an empty default string and then only attach an IAM statement if a secret is defined

2021-02-10 21:52 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-customer.yml
> +    Default: NoSecret
(I'll get that change for you)

2021-02-11 16:02 UTC, horakj commented on deployments/auxiliary/cloudformation/panther-iam-roles-rule-engine-account-customer.yml
> +    Description: Enter the S3 Bucket that the Panther Rules Engine can Read from.
I added to the top of the parameters now so it is easier to find

2021-02-12 21:16 UTC, austinbyers commented
@horakj take a look, I made some changes:

* Turned the secret name into an arn; it's possible it could be in yet another account
* Added the option for KMS decryption
* Added CloudFormation conditions for KMS and Secret access - the policy is added only if their respective parameters were defined
* Removed the Panther managed policy. With #2647, we can pass an IAM role as a top-level Panther parameter (`PythonAssumableRoleArns`) and the Python engines will be allowed to assume it

Review the changes, test them in your account, and then you're good to merge once you're happy with them!

2021-02-12 21:16 UTC, austinbyers approved these changes

2021-02-13 00:03 UTC, merged

2021-02-13 00:03 UTC, horakj commented
Tested in dev environment with no issues