Aux CFN - Athena Third Party BI Connection IAM Permissions
panther-labs/panther pull request #2563
Opened 2021-01-29 22:04 UTC by horakj

## Background

 Generic template the covers multiple BI tools using Athena that require an access key and secret key.

## Changes

- 1 CFN Aux Template

## Testing

- Works with Mode BI and Apache Superset

2021-02-01 20:09 UTC, austinbyers requested changes
Good start!

Doesn't have to be now, but we do maintain terraform copies of all the aux templates as well, if it's easy to add a tf version that'd be awesome

2021-02-01 20:09 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-bi-iam-permissions.yml
> +      UserName: Athena_analytics_readonly
Let's make this a configurable parameter (but you can keep this as the default value).

2021-02-01 20:09 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-bi-iam-permissions.yml
> +            Resource: arn:aws:s3:::panther-bootstrap-athenaresults-*
The bucket names are not so predictable. With the root stack deployment, for example: `myRootStackName-bootstrap-n86t3jcxl5be-athenaresults-1axkels3jum5m`

So our options are:
* Require the entire bucket name as a parameter, or
* Add a parameter for the root stack name (default: "panther") and then allow `${RootStack}-*-athenaresults*`

2021-02-01 20:09 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-bi-iam-permissions.yml
> +            Resource: arn:aws:s3:::panther-bootstrap-historicaldata-*
Since you have the same set of permissions for each bucket, you can combine these 3 statements into one statement with multiple resources:

```suggestion
          - Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:ListMultipartUploadParts
              - s3:PutObject
            Resource:
              - arn:aws:s3:::panther-bootstrap-processeddata-*
              - arn:aws:s3:::panther-bootstrap-historicaldata-*
              - arn:aws:s3:::panther-bootstrap-athenaresults-*
```

(with the caveat about bucket names I mentioned above)

2021-02-01 20:09 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-bi-iam-permissions.yml
> +    Value: !GetAtt AthenaAccessKey.SecretAccessKey
CloudFormation outputs are not encrypted and are visible to anyone with read permissions on the stack - we definitely should not output it here.

> CloudFormation does not redact or obfuscate any information you include in the Outputs section. We strongly recommend you do not use this section to output sensitive information, such as passwords or secrets.

Users may just have to generate the access key themselves after we create the IAM user

2021-02-01 23:55 UTC, nhakmiller commented on deployments/auxiliary/cloudformation/panther-bi-iam-permissions.yml
> +    Value: !GetAtt AthenaAccessKey.SecretAccessKey
I agree. We do this internally because we the the only people/systems that have access to the account at all already have more access than the keys provide. In general, we shouldn't assume that other environments are setup the same as ours.

2021-02-03 18:29 UTC, horakj commented on deployments/auxiliary/cloudformation/panther-bi-iam-permissions.yml
> +      UserName: Athena_analytics_readonly
Sounds good.

2021-02-09 17:12 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-bi-iam-permissions.yml
> +              - !Sub arn:aws:s3:::${RootStackName}-*-historicaldata-*
Replace `:aws:` with `:${AWS::Partition}:` to ensure this can work in AWS China and gov-cloud in the future

2021-02-09 17:12 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-bi-iam-permissions.yml
> +              - s3:ListBucket
GetBucketLocation and ListBucket are already included above, why do we have to grant access to every S3 bucket here?

I think the only one you need to keep in this block is `s3:ListAllMyBuckets`

2021-02-09 18:53 UTC, austinbyers approved these changes

2021-02-09 18:53 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-bi-iam-permissions.yml
> +  RootStackName:
This may not work for customers who deployed directly from source, but that will only apply to the community edition and those deployments will be migrated in a few weeks anyway

2021-02-09 19:54 UTC, horakj commented on deployments/auxiliary/cloudformation/panther-bi-iam-permissions.yml
> +  RootStackName:
My dev is deployed from source and I have no issue but I am using the enterprise repo.

2021-02-09 20:45 UTC, austinbyers approved these changes

2021-02-09 20:45 UTC, austinbyers commented on deployments/auxiliary/cloudformation/panther-bi-iam-permissions.yml
> +  RootStackName:
`mage deploy` direct-stack buckets will look like this:

* `panther-bootstrap-historicaldata-1dagafs5yass5`

There is no "root stack" name in this case, but I see why your panther default is working. We do actually have some production accounts with this setup, and their bucket names will not change even with the migration.

`mage master:deploy` buckets will look like this:

* `myRootStackName-bootstrap-n86t3jcxl5be-historicaldata-1axkels3jum5m`

----

So yes, this pattern

* `!Sub arn:${AWS::Partition}:s3:::${RootStackName}-*-historicaldata-*`

will work for both cases (if you want to be extra certain, you can verify with a `mage master:deploy` setup)

2021-02-09 20:57 UTC, merged