Rule Engine: case-insensitive lookup for event fields
panther-labs/panther pull request #2674
Opened 2021-02-15 07:41 UTC by georgepsarakis

## Background

Apart from making it easier for rule authors to write fields without recalling the exact case-sensitive field name, changes in case should not affect rules. In addition, Athena columns are lowercase.  

`PantherEvent` and its nested objects will now allow case-insensitive lookup.

> Unit tests (via `panther_analysis_tool`) will require using all-lowercase field names for the time being.

## Changes

- Define a mapping from lowercase key name to the original key name.
- Perform a case-sensitive search initially and fall back to case-insensitive lookup through the case-insensitive key mapping. 
- Note that the original field names will still be available.

## Testing

- `mage test:python`

2021-02-15 08:18 UTC, alxarch commented
> ## Background
> Apart from making it easier for rule authors to write fields without recalling the exact case-sensitive field name, changes in case should not affect rules. In addition, Athena columns are lowercase.

What case requirements exist for _Athena_ should not affect the rules engine. The stored JSON data preserves the input case of field names. _Snowflake_ might not have such requirements. We're currently 'dumbing down' Snowflake tables to be compatible with _Athena_ but this will probably change soon.
  
> 
> `PantherEvent` and its nested objects will now allow case-insensitive lookup.

This will add significant overhead _for each row_ and _for each lookup_. Instead of being `O(1)` each lookup will become `O(1+n)` where `n` is the number of keys in the `dict`. This will happen for every step in a _path lookup_. Even if you cache the lower case names on each level lazily, you won't improve this significantly since rules rarely lookup fields more than once for each row.

The only way I would see this work with a similar performance profile as the current rules engine would be if we had a pre-computed mapping of names, based on the event schema, that would allow the case-insensitive lookup to be `O(1+1)`.

Note that since all current rules work with case-sensitive lookups, you cannot observe the performance impact on production now unless you deploy a custom rule set that has all lookups use lower case names.

> 
> > Unit tests (via `panther_analysis_tool`) will require using all-lowercase field names for the time being.
> 
> ## Changes
> * Define a mapping from lowercase key name to the original key name.
> * Perform a case-sensitive search initially and fall back to case-insensitive lookup through the case-insensitive key mapping.
> * Note that the original field names will still be available.
> 
> ## Testing
> * `mage test:python`
> * End-to-end test:
>   
>   * Deploy this branch.
>   * Edit `/detections/rules/GCP.GCS.IAMChanges/edit/?section=functions`
>     ```python
>      def rule(event):
>          return (event['resource'].get('type') == 'gcs_bucket' and
>              event['protopayload'].get('methodname')
>            == 'storage.setIamPermissions')
>     ```
>   * Run tests, still passing.

2021-02-15 08:29 UTC, alxarch requested changes
While I understand the benefits, I am concerned about performance issues. Mitigations:
  1. Ideally the lookup mappings would be pre-computed _once_ per-file on the first event (this would complicate the code by _a lot_ but keep a `O(1)` lookup behavior).
  2. We should lazily initialize the `_case_insensitive` dict once a lookup fails, so we only pay for it when a user is sloppy with field case

2021-02-15 08:29 UTC, alxarch commented on internal/log_analysis/rules_engine/src/immutable.py
> +        self._case_insensitive_keymap = {key.lower(): key for key in self._container}
This will be running _for each event_ being processed by the rules engine, probably recursively on deep `dict` hierarchies. Consider lazily initializing the `_case_insensitive_keymap only if a lookup fails.

2021-02-15 08:49 UTC, georgepsarakis commented
> The stored JSON data preserves the input case of field names. 

I am aware of this, my understanding was that this might happen if you extract data from a query or if the query results during  Scheduled Rule executions contain the fields in lowercase (I may be confusing different problems here, not sure at all).

2021-02-15 08:52 UTC, georgepsarakis commented on internal/log_analysis/rules_engine/src/immutable.py
> +        self._case_insensitive_keymap = {key.lower(): key for key in self._container}
I considered this before adding this calculation in the constructor. Your suggestion might look as an optimal path now, but I am almost certain that as time goes by, more users will rely on case-insensitive field names, thus making this the default branch. I could move this though to `__getitem__` for now.

2021-02-15 09:05 UTC, georgepsarakis commented
> Ideally the lookup mappings would be pre-computed once per-file on the first event (this would complicate the code by a lot but keep a O(1) lookup behavior).

@alxarch this doesn't seem possible, as far as I can think. You would need a way to create a robust cache key to retrieve the mapping from some global registry.

Creating the mapping requires 3μs for an event such as [this](https://github.com/panther-labs/panther-analysis/blob/410dc0a84eef75d64b9828453dc91fb9f86ca568/aws_s3_rules/aws_s3_insecure_access.yml#L34).

2021-02-15 09:09 UTC, georgepsarakis commented
> Another concern I have is that this will lead to weird behavior for the dict when used with other meta methods (i.e. .keys()).

We could provide the lowercased keys when iterating, I just wasn't sure if we would want to hide the real field names. I borrowed some ideas from this [structure](https://github.com/psf/requests/blob/8c211a96cdbe9fe320d63d9e1ae15c5c07e179f8/requests/structures.py#L15).

2021-02-15 09:13 UTC, georgepsarakis commented on internal/log_analysis/rules_engine/src/immutable.py
> +        self._case_insensitive_keymap = {key.lower(): key for key in self._container}
It might be an improvement to account for cases with iteration as well. I think the most used operation would be lookup though in rule functions.

2021-02-15 14:10 UTC, alxarch commented on internal/log_analysis/rules_engine/src/immutable.py
> +        self._case_insensitive_keymap = {key.lower(): key for key in self._container}
> I am almost certain that as time goes by, more users will rely on case-insensitive field names,thus making this the default branch. I could move this though to __getitem__ for now.

My suggestion assumes that to provide the immutable `dict` to a rule, you do a full recursive traversal through it. If that is the case, than `__init__` will be called for every nested `dict` even for values that are irrelevant to the rule itself. Moving it to __getitem__, and supposing you are reusing the same immutable event for all rules that should match against this event,  will reduce the impact significantly as only the `dict` values relevant to the field will be initializing case-insensitive lookups.

2021-02-15 14:14 UTC, alxarch commented
> > Another concern I have is that this will lead to weird behavior for the dict when used with other meta methods (i.e. .keys()).
> 
> We could provide the lowercased keys when iterating

This would probably cause _more_ problems if for example the event is serialized to JSON to be embedded in an alert context.
The iterator meta meta methods are used by various parts of Python stdlib modules AFAIK. Making the `dict` expose its keys as if they were lower case in the first place would make it act as if we were using a new dict with lower case keys in the first place.

2021-02-15 14:20 UTC, georgepsarakis commented on internal/log_analysis/rules_engine/src/immutable.py
> +        self._case_insensitive_keymap = {key.lower(): key for key in self._container}
> My suggestion assumes that to provide the immutable dict to a rule, you do a full recursive traversal through it. 

No this happens on demand, when [the nested object is retrieved](https://github.com/panther-labs/panther/blob/8cf5cf9654a6ae37cd8200096c60847283ab9afc/internal/log_analysis/rules_engine/src/immutable.py#L49).

>  you are reusing the same immutable event for all rules

The same instance is indeed used for all rules. Nested object access requires creating new instances though.

2021-02-15 14:21 UTC, alxarch commented
> > The stored JSON data preserves the input case of field names.
> 
> I am aware of this, my understanding was that this might happen if you extract data from a query or if the query results during Scheduled Rule executions contain the fields in lowercase (I may be confusing different problems here, not sure at all).

You are not confusing different issues. The case insensitive lookup makes a lot of sense from a usability standpoint. We should just make sure it is well-documented and that we also document what happens with collisions.
By collisions I mean if an event has indeed `fooBar` and `FooBar` as separate fields and the user looks up `foobar`, how do we resolve this? Is it random? Does python `json.loads` preserve order of keys as they were in the input JSON?. Do we have control over the order that this key is written in JSON? Is it possible that when processing two different such events, one rule succeeds and another fails due to the order that keys where written in JSON?

2021-02-15 14:26 UTC, rleighton commented
I’m away from my computer, so apologies if this is not an informed
question(s).

First, isn’t it the case that most rules only look up one or two keys? If
so , that should inform the design.

Second, my naive approach would be just a that get() looks up, if found,
return, if not lookup in lower cache dict, if not found lowercase key ,
look up, if found up date lowercase cache, and return

On Mon, Feb 15, 2021 at 9:14 AM Alexandros Sigalas <notifications@github.com>
wrote:

> Another concern I have is that this will lead to weird behavior for the
> dict when used with other meta methods (i.e. .keys()).
>
> We could provide the lowercased keys when iterating
>
> This would probably cause *more* problems if for example the event is
> serialized to JSON to be embedded in an alert context.
> The iterator meta meta methods are used by various parts of Python stdlib
> modules AFAIK. Making the dict expose its keys as if they were lower case
> in the first place would make it act as if we were using a new dict with
> lower case keys in the first place.
>
> —
> You are receiving this because your review was requested.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/panther-labs/panther/pull/2674#issuecomment-779249321>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEMRAMQP4AGBH2VRBDT2HJDS7ET4BANCNFSM4XUGG52A>
> .
>

2021-02-15 14:46 UTC, kostaspap commented
Trying to take a step back... The problem is essentially the following: When querying Athena, it always returns the keys of a dictionary in lowercase. This can be a problem when someone tries to create a rule out of results fetched from Athena.
It might be computationally expensive to support fully case insensitive lookup, but what if we would support the following:

`if event.get(key) is None return event.get(key.toLowerCase())`. 

The above relies on the fact that keys in the `event` will either have the correct case, or they will be lowercase. Thoughts ?

2021-02-15 14:46 UTC, alxarch commented
> Second, my naive approach would be just a that get() looks up, if found,
return, if not lookup in lower cache dict,

I assume this is to save us from lower-casing the key unnecessarily

>  if not found lowercase key ,
look up, if found up date lowercase cache, and return

But this does not match all cases of the key in the end. The second lookup will only match if the field in the original dict _was_ lowercase but the user provided a non-lowercase key.

2021-02-15 14:54 UTC, kostaspap commented
> Trying to take a step back... The problem is essentially the following: When querying Athena, it always returns the keys of a dictionary in lowercase. This can be a problem when someone tries to create a rule out of results fetched from Athena.
> Since it can be computationally expensive to support fully case insensitive lookup, may we should just support the following:
> 
> `if event.get(key) is None return event.get(key.toLowerCase())`.
> 
> The above relies on the fact that keys in the `event` will either have the correct case, or they will be lowercase. Thoughts?

I acknowledge that this suggestion is different that the one we had agreed on the relevant Github issue... However I am thinking that if having fully case insensitive search is challenging/expensive, it might be sufficient just to implement the above.

2021-02-15 15:37 UTC, alxarch commented
> I acknowledge that this suggestion is different that the one we had agreed on the relevant Github issue... However I am thinking that if having fully case insensitive search is challenging/expensive, it might be sufficient just to implement the above.

After a small discussion with @georgepsarakis  I am not that concerned about performance. My main concern is to have a deterministic way to solve collisions. If an event contains both `FooBar` and `fooBar` fields with _different values_, it is important to have a clear rule about which of the two fields will match when I query it with `foobar`. There are two approaches to this:
  1. Do not add mappings for keys that collide, forcing the user to use the correct case when there are collisions.
  2. Make sure you return a stable result by matching the same mapping every time for all events. One way to achieve this is to rely on the order of keys in the JSON value. But this might be volatile if _some fields_ are included _sometimes_. To be completely deterministic this approach would require to have knowledge of the schema. This is what we do when we define the storage descriptor of a _Glue_ table.

2021-02-15 18:16 UTC, kostaspap commented
> > I acknowledge that this suggestion is different that the one we had agreed on the relevant Github issue... However I am thinking that if having fully case insensitive search is challenging/expensive, it might be sufficient just to implement the above.
> 
> After a small discussion with @georgepsarakis I am not that concerned about performance. My main concern is to have a deterministic way to solve collisions. If an event contains both `FooBar` and `fooBar` fields with _different values_, it is important to have a clear rule about which of the two fields will match when I query it with `foobar`. There are two approaches to this:
> 
> 1. Do not add mappings for keys that collide, forcing the user to use the correct case when there are collisions.
> 2. Make sure you return a stable result by matching the same mapping every time for all events. One way to achieve this is to rely on the order of keys in the JSON value. But this might be volatile if _some fields_ are included _sometimes_. To be completely deterministic this approach would require to have knowledge of the schema. This is what we do when we define the storage descriptor of a _Glue_ table.

No1 from above sounds reasonable to me.

2021-02-19 07:38 UTC, georgepsarakis commented
Thanks everyone for the feedback! Let's pause this for a while and revisit it next week.

2021-02-26 16:06 UTC, georgepsarakis commented
Closing, will be transferred with a reference here.

2021-02-26 16:06 UTC, closed without merging