Make sure we don't serialize invalid JSON
panther-labs/panther pull request #2703
Opened 2021-02-17 13:54 UTC by kostaspap

## Background

Fixes https://github.com/panther-labs/panther-enterprise/issues/2286

## Changes

- Avoid serializing invalid JSON if we have an empty event

## Testing

- mage test:go

2021-02-17 14:36 UTC, alxarch requested changes

2021-02-17 14:36 UTC, alxarch commented on internal/log_analysis/log_processor/pantherlog/jsoniter.go
> +	// If the result.Event has no serializable content, it will be serialized to `{}`
If I understand correctly this tries to check `{}`, `[]` and `""` in one go.
If `result.Event` is `nil` it might be `null`.
The check here is hard to get right for all cases that's why the previous code _only_ tried to detect `}` as last byte.
My suggestion would be to modify what happens around `extendJSON`.
The 'real' bug is that `extendJSON` does not check if it is putting the comma `,` at the correct position.


By Resetting _here_, you rely on `extendJSON` doing the right thing with an empty buffer.
I would suggest we change `extendJSON` so that this relation between the two points in code does not cause more bugs in the future.
This could be trivially checked checking the value of `n`.
The check `0 <= n && n < len(data)` can become `2 <= n && n < len(data)`.
If `extendJSON` returns `false` we do `Reset` and `WriteObjectStart` at the same place so that there's no dependencies between the two points in code.

2021-02-17 15:37 UTC, kostaspap commented on internal/log_analysis/log_processor/pantherlog/jsoniter.go
> +	// If the result.Event has no serializable content, it will be serialized to `{}`
I don't think it was possible to have `null` ... but anyway I've updated the code to follow this approach. Note that `extendJSON` was not resetting the buffer, added it as part of the PR.

2021-02-18 09:23 UTC, georgepsarakis commented on internal/log_analysis/log_processor/pantherlog/jsoniter.go
> +	if n := len(data) - 1; 2 <= n && n < len(data) && data[n] == '}' {
Isn't `n < len(data)` always true?

2021-02-18 09:30 UTC, georgepsarakis commented on internal/log_analysis/log_processor/pantherlog/jsoniter.go
> +	if n := len(data) - 1; 2 <= n && n < len(data) && data[n] == '}' {
I can't think of a case that you can have valid JSON object with 3 characters. I think the minimum is 6: `{"a":1}`, but not sure if we need to handle this further here.

2021-02-18 10:47 UTC, giorgosp commented on internal/log_analysis/log_processor/pantherlog/jsoniter.go
> +	// Don't try to do the swap for empty JSON `{}`
Why not? Can't `{}` be extended?

2021-02-18 11:08 UTC, kostaspap commented on internal/log_analysis/log_processor/pantherlog/jsoniter.go
> +	// Don't try to do the swap for empty JSON `{}`
> Why not? Can't `{}` be extended?

What the code does is that it replaces the last `}` of a JSON with `,` so that it can be "extended". 
An empty JSON cannot be extended (we end up with `{,` ), it needs to be ... recreated.

2021-02-18 11:57 UTC, alxarch commented on internal/log_analysis/log_processor/pantherlog/jsoniter.go
> +	if n := len(data) - 1; 2 <= n && n < len(data) && data[n] == '}' {
> Isn't `n < len(data)` always true?

Yes, but having the check explicit in code avoids the runtime check imposed by the go compiler when you do index operations below.
This effectively allows the function to be _inlined_.
We're at a very performance sensitive part of the code here. This operation is running for _every_ event written to Panther.
The function was carefully designed to 'spartan' standards.
For more information see

https://www.ardanlabs.com/blog/2018/04/bounds-check-elimination-in-go.html
https://dave.cheney.net/2020/04/25/inlining-optimisations-in-go

2021-02-18 11:58 UTC, georgepsarakis commented on internal/log_analysis/log_processor/pantherlog/jsoniter.go
> +	if n := len(data) - 1; 2 <= n && n < len(data) && data[n] == '}' {
Aha, nice thanks for the thorough explanation!

2021-02-18 12:00 UTC, alxarch commented on internal/log_analysis/log_processor/pantherlog/jsoniter.go
> +	if n := len(data) - 1; 2 <= n && n < len(data) && data[n] == '}' {
> hat you can have valid JSON object with 3 characters. I think the minimum is 6: `{"a":1}`, but not sure if we need to handle this further here.

The actual _valid_ minimum is `len(s) == 6`:
```json
{"":1}
```

2021-02-18 12:02 UTC, alxarch commented on internal/log_analysis/log_processor/pantherlog/jsoniter.go
> +	// Don't try to do the swap for empty JSON `{}`
We could replace the `,` with ` ` (space) and strill return true but this can be handled with the `Reset()` + `WriteObjectStart` in   the caller. We want this function inlinable.

2021-02-18 12:08 UTC, alxarch approved these changes
LGTM

2021-02-18 12:31 UTC, kostaspap commented on internal/log_analysis/log_processor/pantherlog/jsoniter.go
> +	if n := len(data) - 1; 2 <= n && n < len(data) && data[n] == '}' {
> Isn't `n < len(data)` always true?

I will update the code with @alxarch comments explaining why we want the check in there.

2021-02-18 12:34 UTC, giorgosp commented on internal/log_analysis/log_processor/pantherlog/jsoniter.go
> +	if n := len(data) - 1; 2 <= n && n < len(data) && data[n] == '}' {
Thanks Kostas I was about to suggest it

2021-02-18 12:41 UTC, merged